// Package viewporter contains the bindings for the viewporter protocol,
// which decouples a surface's buffer from the size it occupies on screen.
//
// Bind [ViewporterInterface] from the registry and attach a [Viewport] to
// a wl_surface with [Viewporter.GetViewport]. The viewport sets a source
// rectangle to crop the buffer and a destination size in logical units to
// scale it into, either independently.
//
// The destination size is what makes fractional scaling work: a buffer
// rendered at a non-integer scale has physical dimensions that are not a
// whole multiple of the logical ones, and set_destination is how the
// client states the logical size it meant. See the fractionalscale
// package.
//
// A surface may have only one viewport at a time.
//
// Generated by waygenerator from protocols/viewporter.xml. Do not edit the
// .gen.go files.
package viewporter
