// Code generated by waygenerator. DO NOT EDIT.

package viewporter

import (
	"fmt"

	"github.com/romycode/ggui/wayland/wlcore"
)

// Viewporter: surface cropping and scaling
//
// The global interface exposing surface cropping and scaling
// capabilities is used to instantiate an interface extension for a
// wl_surface object. This extended interface will then allow
// cropping and scaling the surface contents, effectively
// disconnecting the direct relationship between the buffer and the
// surface size.
type Viewporter struct {
	wlcore.ProxyBase
	listener ViewporterListener
}

var _ wlcore.Proxy = (*Viewporter)(nil)

func newViewporter(id, version uint32, conn *wlcore.Conn) *Viewporter {
	return newViewporterFromProxyBase(wlcore.NewProxyBase(id, version, conn))
}

func newViewporterFromProxyBase(base wlcore.ProxyBase) *Viewporter {
	v := &Viewporter{ProxyBase: base}
	return v
}

func (v *Viewporter) SetListener(l ViewporterListener) { v.listener = l }

type ViewporterListener struct {
}

var ViewporterInterface = wlcore.Interface[*Viewporter]{
	Name:       "wp_viewporter",
	MaxVersion: 1,
	New:        newViewporterFromProxyBase,
}

// Destroy: unbind from the cropping and scaling interface
//
// Informs the server that the client will not be using this
// protocol object anymore. This does not affect any other objects,
// wp_viewport objects included.
func (v *Viewporter) Destroy() error {
	err := v.Conn().Send(v.ID(), opReqViewporterDestroy, wlcore.NewEncoder())
	v.Conn().Destroy(v)
	return err
}

// GetViewport: extend surface interface for crop and scale
//
// Instantiate an interface extension for the given wl_surface to
// crop and scale its content. If the given wl_surface already has
// a wp_viewport object associated, the viewport_exists
// protocol error is raised.
//
// Parameters:
//   - surface: the surface
func (v *Viewporter) GetViewport(surface *wlcore.Surface) (*Viewport, error) {
	id := v.Conn().NewID()
	x := newViewportFromProxyBase(wlcore.NewProxyBase(id, v.Version(), v.Conn()))
	v.Conn().Register(x)

	e := wlcore.NewEncoder().ID(id).ID(surface.ID())
	if err := v.Conn().Send(v.ID(), opReqViewporterGetViewport, e); err != nil {
		return nil, err
	}
	return x, nil
}

func (v *Viewporter) Dispatch(opcode uint16, dec *wlcore.Decoder) error {
	switch opcode {
	default:
		return fmt.Errorf("viewporter: unknown opcode %d in wp_viewporter", opcode)
	}
}

type ViewporterError uint32

const (
	ViewporterErrorViewportExists ViewporterError = 0 // the surface already has a viewport object associated
)

const (
	opReqViewporterDestroy     = 0
	opReqViewporterGetViewport = 1
)
