// Code generated by waygenerator. DO NOT EDIT.

package viewporter

import (
	"fmt"

	"github.com/romycode/ggui/wayland/wlcore"
)

// Viewport: crop and scale interface to a wl_surface
//
// An additional interface to a wl_surface object, which allows the
// client to specify the cropping and scaling of the surface
// contents.
//
// This interface works with two concepts: the source rectangle (src_x,
// src_y, src_width, src_height), and the destination size (dst_width,
// dst_height). The contents of the source rectangle are scaled to the
// destination size, and content outside the source rectangle is ignored.
// This state is double-buffered, see wl_surface.commit.
//
// The two parts of crop and scale state are independent: the source
// rectangle, and the destination size. Initially both are unset, that
// is, no scaling is applied. The whole of the current wl_buffer is
// used as the source, and the surface size is as defined in
// wl_surface.attach.
//
// If the destination size is set, it causes the surface size to become
// dst_width, dst_height. The source (rectangle) is scaled to exactly
// this size. This overrides whatever the attached wl_buffer size is,
// unless the wl_buffer is NULL. If the wl_buffer is NULL, the surface
// has no content and therefore no size. Otherwise, the size is always
// at least 1x1 in surface local coordinates.
//
// If the source rectangle is set, it defines what area of the wl_buffer is
// taken as the source. If the source rectangle is set and the destination
// size is not set, then src_width and src_height must be integers, and the
// surface size becomes the source rectangle size. This results in cropping
// without scaling. If src_width or src_height are not integers and
// destination size is not set, the bad_size protocol error is raised when
// the surface state is applied.
//
// The coordinate transformations from buffer pixel coordinates up to
// the surface-local coordinates happen in the following order:
// 1. buffer_transform (wl_surface.set_buffer_transform)
// 2. buffer_scale (wl_surface.set_buffer_scale)
// 3. crop and scale (wp_viewport.set*)
// This means, that the source rectangle coordinates of crop and scale
// are given in the coordinates after the buffer transform and scale,
// i.e. in the coordinates that would be the surface-local coordinates
// if the crop and scale was not applied.
//
// If src_x or src_y are negative, the bad_value protocol error is raised.
// Otherwise, if the source rectangle is partially or completely outside of
// the non-NULL wl_buffer, then the out_of_buffer protocol error is raised
// when the surface state is applied. A NULL wl_buffer does not raise the
// out_of_buffer error.
//
// If the wl_surface associated with the wp_viewport is destroyed,
// all wp_viewport requests except 'destroy' raise the protocol error
// no_surface.
//
// If the wp_viewport object is destroyed, the crop and scale
// state is removed from the wl_surface. The change will be applied
// on the next wl_surface.commit.
type Viewport struct {
	wlcore.ProxyBase
	listener ViewportListener
}

var _ wlcore.Proxy = (*Viewport)(nil)

func newViewport(id, version uint32, conn *wlcore.Conn) *Viewport {
	return newViewportFromProxyBase(wlcore.NewProxyBase(id, version, conn))
}

func newViewportFromProxyBase(base wlcore.ProxyBase) *Viewport {
	v := &Viewport{ProxyBase: base}
	return v
}

func (v *Viewport) SetListener(l ViewportListener) { v.listener = l }

type ViewportListener struct {
}

var ViewportInterface = wlcore.Interface[*Viewport]{
	Name:       "wp_viewport",
	MaxVersion: 1,
	New:        newViewportFromProxyBase,
}

// Destroy: remove scaling and cropping from the surface
//
// The associated wl_surface's crop and scale state is removed.
// The change is applied on the next wl_surface.commit.
func (v *Viewport) Destroy() error {
	err := v.Conn().Send(v.ID(), opReqViewportDestroy, wlcore.NewEncoder())
	v.Conn().Destroy(v)
	return err
}

// SetSource: set the source rectangle for cropping
//
// Set the source rectangle of the associated wl_surface. See
// wp_viewport for the description, and relation to the wl_buffer
// size.
//
// If all of x, y, width and height are -1.0, the source rectangle is
// unset instead. Any other set of values where width or height are zero
// or negative, or x or y are negative, raise the bad_value protocol
// error.
//
// The crop and scale state is double-buffered, see wl_surface.commit.
//
// Parameters:
//   - x: source rectangle x
//   - y: source rectangle y
//   - width: source rectangle width
//   - height: source rectangle height
func (v *Viewport) SetSource(x wlcore.Fixed, y wlcore.Fixed, width wlcore.Fixed, height wlcore.Fixed) error {
	e := wlcore.NewEncoder().Fixed(x).Fixed(y).Fixed(width).Fixed(height)
	return v.Conn().Send(v.ID(), opReqViewportSetSource, e)
}

// SetDestination: set the surface size for scaling
//
// Set the destination size of the associated wl_surface. See
// wp_viewport for the description, and relation to the wl_buffer
// size.
//
// If width is -1 and height is -1, the destination size is unset
// instead. Any other pair of values for width and height that
// contains zero or negative values raises the bad_value protocol
// error.
//
// The crop and scale state is double-buffered, see wl_surface.commit.
//
// Parameters:
//   - width: surface width
//   - height: surface height
func (v *Viewport) SetDestination(width int32, height int32) error {
	e := wlcore.NewEncoder().Int32(width).Int32(height)
	return v.Conn().Send(v.ID(), opReqViewportSetDestination, e)
}

func (v *Viewport) Dispatch(opcode uint16, dec *wlcore.Decoder) error {
	switch opcode {
	default:
		return fmt.Errorf("viewporter: unknown opcode %d in wp_viewport", opcode)
	}
}

type ViewportError uint32

const (
	ViewportErrorBadValue    ViewportError = 0 // negative or zero values in width or height
	ViewportErrorBadSize     ViewportError = 1 // destination size is not integer
	ViewportErrorOutOfBuffer ViewportError = 2 // source rectangle extends outside of the content area
	ViewportErrorNoSurface   ViewportError = 3 // the wl_surface was destroyed
)

const (
	opReqViewportDestroy        = 0
	opReqViewportSetSource      = 1
	opReqViewportSetDestination = 2
)
