package keysymdata

import (
	"bytes"
	"fmt"
	"go/format"
	"io"
	"sort"
	"strconv"
)

// Render produces formatted Go source defining keyboard keysym lookup tables.
func Render(t Tables) ([]byte, error) {
	nameKeys := make([]string, 0, len(t.Names))
	for name := range t.Names {
		nameKeys = append(nameKeys, name)
	}
	sort.Strings(nameKeys)

	canonicalKeys := sortedKeys(t.CanonicalNames)
	runeKeys := sortedKeys(t.Runes)

	var buffer bytes.Buffer
	buffer.WriteString("// Code generated by keysymgen. DO NOT EDIT.\n\n")
	buffer.WriteString("package keyboard\n\n")
	buffer.WriteString("var keysymNames = map[string]Keysym{\n")
	for _, name := range nameKeys {
		fmt.Fprintf(&buffer, "\t%s: %s,\n", strconv.Quote(name), hex(t.Names[name]))
	}
	buffer.WriteString("}\n\n")

	buffer.WriteString("var keysymCanonicalNames = map[Keysym]string{\n")
	for _, keysym := range canonicalKeys {
		fmt.Fprintf(&buffer, "\t%s: %s,\n", hex(keysym), strconv.Quote(t.CanonicalNames[keysym]))
	}
	buffer.WriteString("}\n\n")

	buffer.WriteString("var legacyRunes = map[Keysym]rune{\n")
	for _, keysym := range runeKeys {
		fmt.Fprintf(&buffer, "\t%s: %s,\n", hex(keysym), hex(uint32(t.Runes[keysym])))
	}
	buffer.WriteString("}\n")

	formatted, err := format.Source(buffer.Bytes())
	if err != nil {
		return nil, fmt.Errorf("keysymgen: format generated Go: %w", err)
	}
	return formatted, nil
}

// Generate parses a libxkbcommon keysym header and renders Go source from it.
func Generate(r io.Reader) ([]byte, error) {
	tables, err := Parse(r)
	if err != nil {
		return nil, err
	}
	return Render(tables)
}

func sortedKeys[V any](values map[uint32]V) []uint32 {
	keys := make([]uint32, 0, len(values))
	for keysym := range values {
		keys = append(keys, keysym)
	}
	sort.Slice(keys, func(i, j int) bool {
		return keys[i] < keys[j]
	})
	return keys
}

func hex(value uint32) string {
	return fmt.Sprintf("0x%04x", value)
}
