package codegen

import (
	"bytes"
	"fmt"

	"github.com/romycode/ggui/cmd/waygenerator/internal/resolve"
)

// RenderInterface produce el código fuente (sin formatear todavía --
// format.Source llega en Emit, Task 10) de un fichero .gen.go para una
// interfaz. Task 8 y 9 lo extienden para requests y events; este task solo
// cubre el esqueleto (struct, constructor, SetListener, descriptor,
// Dispatch vacío) y enums.
func RenderInterface(iface resolve.ResolvedInterface) ([]byte, error) {
	var b bytes.Buffer

	fmt.Fprintf(&b, "// Code generated by waygenerator. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", iface.GoPackage)
	fmt.Fprintf(&b, "import \"fmt\"\n\n")

	renderStructAndConstructor(&b, iface)
	renderListener(&b, iface)
	renderDescriptor(&b, iface)
	if err := renderDispatch(&b, iface); err != nil {
		return nil, err
	}
	renderEnums(&b, iface)

	out := bytes.TrimRight(b.Bytes(), "\n")
	out = append(out, '\n')
	return out, nil
}

func renderStructAndConstructor(b *bytes.Buffer, iface resolve.ResolvedInterface) {
	fmt.Fprintf(b, "type %s struct {\n\tProxyBase\n\tlistener %sListener\n}\n\n", iface.GoType, iface.GoType)
	fmt.Fprintf(b, "var _ Proxy = (*%s)(nil)\n\n", iface.GoType)
	fmt.Fprintf(b, "func new%s(id, version uint32, c *Conn) *%s {\n", iface.GoType, iface.GoType)
	fmt.Fprintf(b, "\t%s := &%s{ProxyBase: NewProxyBase(id, version, c)}\n", iface.Recv, iface.GoType)
	if iface.HasEvents {
		fmt.Fprintf(b, "\t%s.OnClear = func() { %s.listener = %sListener{} }\n", iface.Recv, iface.Recv, iface.GoType)
	}
	fmt.Fprintf(b, "\treturn %s\n}\n\n", iface.Recv)
	if iface.PublicListener {
		fmt.Fprintf(b, "func (%s *%s) SetListener(l %sListener) { %s.listener = l }\n\n", iface.Recv, iface.GoType, iface.GoType, iface.Recv)
	}
}

func renderListener(b *bytes.Buffer, iface resolve.ResolvedInterface) {
	fmt.Fprintf(b, "type %sListener struct {\n", iface.GoType)
	// Task 9 añade un campo por evento aquí.
	fmt.Fprintf(b, "}\n\n")
}

func renderDescriptor(b *bytes.Buffer, iface resolve.ResolvedInterface) {
	fmt.Fprintf(b, "var %sInterface = Interface[*%s]{\n", iface.GoType, iface.GoType)
	fmt.Fprintf(b, "\tName:       %q,\n", iface.XMLName)
	fmt.Fprintf(b, "\tMaxVersion: %d,\n", iface.MaxVersion)
	fmt.Fprintf(b, "\tNew:        func(b ProxyBase) *%s { return &%s{ProxyBase: b} },\n", iface.GoType, iface.GoType)
	fmt.Fprintf(b, "}\n\n")
}

func renderDispatch(b *bytes.Buffer, iface resolve.ResolvedInterface) error {
	fmt.Fprintf(b, "func (%s *%s) Dispatch(opcode uint16, d *Decoder) error {\n", iface.Recv, iface.GoType)
	fmt.Fprintf(b, "\tswitch opcode {\n")
	// Task 9 añade un case por evento aquí.
	fmt.Fprintf(b, "\tdefault:\n\t\treturn fmt.Errorf(\"wlcore: opcode %%d desconocido en %s\", opcode)\n", iface.XMLName)
	fmt.Fprintf(b, "\t}\n}\n\n")
	return nil
}

func renderEnums(b *bytes.Buffer, iface resolve.ResolvedInterface) {
	for _, en := range iface.Enums {
		fmt.Fprintf(b, "type %s uint32\n\n", en.GoName)
		fmt.Fprintf(b, "const (\n")
		for _, e := range en.Entries {
			fmt.Fprintf(b, "\t%s %s = %s\n", e.GoName, en.GoName, e.Value)
		}
		fmt.Fprintf(b, ")\n\n")
		if en.Bitfield {
			fmt.Fprintf(b, "func (v %s) Has(flag %s) bool { return v&flag != 0 }\n\n", en.GoName, en.GoName)
		}
	}
}
