package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/romycode/ggui/cmd/waygenerator/internal/resolve"
)

// RenderInterface produce el código fuente (sin formatear todavía --
// format.Source llega en Emit, Task 10) de un fichero .gen.go para una
// interfaz. Task 8 y 9 lo extienden para requests y events; este task solo
// cubre el esqueleto (struct, constructor, SetListener, descriptor,
// Dispatch vacío) y enums.
func RenderInterface(iface resolve.ResolvedInterface) ([]byte, error) {
	var b bytes.Buffer

	fmt.Fprintf(&b, "// Code generated by waygenerator. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", iface.GoPackage)
	fmt.Fprintf(&b, "import \"fmt\"\n\n")

	renderStructAndConstructor(&b, iface)
	renderListener(&b, iface)
	renderDescriptor(&b, iface)
	renderRequests(&b, iface)
	if err := renderDispatch(&b, iface); err != nil {
		return nil, err
	}
	renderEnums(&b, iface)
	renderOpcodeConsts(&b, iface)

	out := bytes.TrimRight(b.Bytes(), "\n")
	out = append(out, '\n')
	return out, nil
}

func renderRequests(b *bytes.Buffer, iface resolve.ResolvedInterface) {
	for _, r := range iface.Requests {
		switch {
		case r.BindLike:
			// bindRaw no es exportado -- no lleva comentario de doc, "go
			// doc" no lo muestra y r.Summary/r.Doc (si el XML los trae)
			// documentarían un símbolo que no existe en la superficie
			// pública.
			fmt.Fprintf(b, "func (%s *%s) bindRaw(name uint32, iface string, version, newID uint32) error {\n", iface.Recv, iface.GoType)
			fmt.Fprintf(b, "\te := NewEncoder().Uint32(name).String(iface).Uint32(version).ID(newID)\n")
			fmt.Fprintf(b, "\treturn %s.Conn().Send(%s.ID(), opReq%s%s, e)\n}\n\n", iface.Recv, iface.Recv, iface.GoType, r.GoName)
		case r.Destructor:
			renderDocComment(b, "", r.GoName, r.Summary, r.Doc, docParamsFor(r.Args))
			fmt.Fprintf(b, "func (%s *%s) %s() error {\n", iface.Recv, iface.GoType, r.GoName)
			renderVersionGuard(b, iface, r, false)
			fmt.Fprintf(b, "\terr := %s.Conn().Send(%s.ID(), opReq%s%s, NewEncoder())\n", iface.Recv, iface.Recv, iface.GoType, r.GoName)
			fmt.Fprintf(b, "\t%s.Conn().destroy(%s)\n\treturn err\n}\n\n", iface.Recv, iface.Recv)
		case r.Returns != nil:
			renderDocComment(b, "", r.GoName, r.Summary, r.Doc, docParamsFor(r.Args))
			fmt.Fprintf(b, "func (%s *%s) %s(%s) (%s, error) {\n", iface.Recv, iface.GoType, r.GoName, paramList(r.Args), r.Returns.TypeString)
			renderVersionGuard(b, iface, r, true)
			fmt.Fprintf(b, "\tid := %s.Conn().NewID()\n", iface.Recv)
			fmt.Fprintf(b, "\tx := new%sFromProxyBase(NewProxyBase(id, %s.Version(), %s.Conn()))\n", r.Returns.ObjGoType, iface.Recv, iface.Recv)
			fmt.Fprintf(b, "\t%s.Conn().Register(x)\n\n", iface.Recv)
			renderNullableObjectIDs(b, r.Args)
			fmt.Fprintf(b, "\te := %s\n", encoderChain(append([]resolve.ResolvedArg{{GoName: "id", Type: resolve.GoType{Kind: resolve.KindObject}}}, r.Args...), true))
			fmt.Fprintf(b, "\tif err := %s.Conn().Send(%s.ID(), opReq%s%s, e%s); err != nil {\n\t\treturn nil, err\n\t}\n", iface.Recv, iface.Recv, iface.GoType, r.GoName, fdVariadic(r.Args))
			fmt.Fprintf(b, "\treturn x, nil\n}\n\n")
		default:
			renderDocComment(b, "", r.GoName, r.Summary, r.Doc, docParamsFor(r.Args))
			fmt.Fprintf(b, "func (%s *%s) %s(%s) error {\n", iface.Recv, iface.GoType, r.GoName, paramList(r.Args))
			renderVersionGuard(b, iface, r, false)
			renderNullableObjectIDs(b, r.Args)
			fmt.Fprintf(b, "\te := %s\n", encoderChain(r.Args, false))
			fmt.Fprintf(b, "\treturn %s.Conn().Send(%s.ID(), opReq%s%s, e%s)\n}\n\n", iface.Recv, iface.Recv, iface.GoType, r.GoName, fdVariadic(r.Args))
		}
	}
}

// docParam es un (nombre, summary) de un <arg> para la lista de
// "Parameters:" que renderDocComment añade bajo el comentario principal.
type docParam struct {
	name    string
	summary string
}

func docParamsFor(args []resolve.ResolvedArg) []docParam {
	params := make([]docParam, len(args))
	for i, a := range args {
		params[i] = docParam{name: a.GoName, summary: a.Summary}
	}
	return params
}

// renderDocComment emite el comentario de doc de un símbolo generado a
// partir de un <description>: la primera línea empieza por el propio
// nombre del símbolo Go, tal como manda docs/waygenerator.md ("Pasada 3 --
// emitir", "<description> -> comentarios de doc, empezando por el nombre
// del símbolo Go para que go doc los muestre bien"). No emite nada si no
// hay summary -- no todo <description> lo trae, y un comentario vacío
// ("// Foo:" sin más) sería peor que ninguno. indent es el prefijo de
// tabs de la posición donde se emite (vacío a nivel de fichero, "\t"
// dentro de un struct).
func renderDocComment(b *bytes.Buffer, indent, symbol, summary, body string, params []docParam) {
	if summary == "" {
		return
	}
	fmt.Fprintf(b, "%s// %s: %s\n", indent, symbol, summary)
	if lines := docBodyLines(body); len(lines) > 0 {
		fmt.Fprintf(b, "%s//\n", indent)
		for _, l := range lines {
			if l == "" {
				fmt.Fprintf(b, "%s//\n", indent)
			} else {
				fmt.Fprintf(b, "%s// %s\n", indent, l)
			}
		}
	}
	var withSummary []docParam
	for _, p := range params {
		if p.summary != "" {
			withSummary = append(withSummary, p)
		}
	}
	if len(withSummary) > 0 {
		fmt.Fprintf(b, "%s//\n", indent)
		fmt.Fprintf(b, "%s// Parameters:\n", indent)
		for _, p := range withSummary {
			fmt.Fprintf(b, "%s//   - %s: %s\n", indent, p.name, p.summary)
		}
	}
}

// docBodyLines limpia la indentación cruda del cuerpo de un <description>:
// cada línea llega tal cual estaba en el XML (indentada), y la primera y
// la última suelen quedar en blanco (el body arranca justo tras el '>' de
// apertura). Recorta cada línea y quita las blancas de los extremos,
// conservando las intermedias como separador de párrafo.
func docBodyLines(body string) []string {
	raw := strings.Split(body, "\n")
	lines := make([]string, 0, len(raw))
	for _, l := range raw {
		lines = append(lines, strings.TrimSpace(l))
	}
	for len(lines) > 0 && lines[0] == "" {
		lines = lines[1:]
	}
	for len(lines) > 0 && lines[len(lines)-1] == "" {
		lines = lines[:len(lines)-1]
	}
	return lines
}

func renderNullableObjectIDs(b *bytes.Buffer, args []resolve.ResolvedArg) {
	for _, a := range args {
		if a.Type.Kind != resolve.KindObject || !a.Type.AllowNull {
			continue
		}
		fmt.Fprintf(b, "\tvar %sID uint32\n", a.GoName)
		fmt.Fprintf(b, "\tif %s != nil {\n", a.GoName)
		fmt.Fprintf(b, "\t\t%sID = %s.ID()\n", a.GoName, a.GoName)
		fmt.Fprintf(b, "\t}\n")
	}
}

func renderVersionGuard(b *bytes.Buffer, iface resolve.ResolvedInterface, r resolve.ResolvedRequest, returnsObj bool) {
	if r.Since <= 1 {
		return
	}
	fmt.Fprintf(b, "\tif %s.Version() < %d {\n", iface.Recv, r.Since)
	if returnsObj {
		fmt.Fprintf(b, "\t\treturn nil, fmt.Errorf(\"wlcore: %s requiere versión >= %d, hay %%d\", %s.Version())\n", r.XMLName, r.Since, iface.Recv)
	} else {
		fmt.Fprintf(b, "\t\treturn fmt.Errorf(\"wlcore: %s requiere versión >= %d, hay %%d\", %s.Version())\n", r.XMLName, r.Since, iface.Recv)
	}
	fmt.Fprintf(b, "\t}\n")
}

// paramList arma la lista de parámetros de un método de request, en el
// orden del XML, saltándose el new_id (nunca llega aquí como Arg, ver
// resolve.resolveRequest) pero incluyendo los fd en su posición natural.
func paramList(args []resolve.ResolvedArg) string {
	var parts []string
	for _, a := range args {
		parts = append(parts, a.GoName+" "+a.Type.TypeString)
	}
	return joinComma(parts)
}

// encoderChain arma la cadena NewEncoder()....... saltándose los args fd
// (van a Send como variádico, no al Encoder). withLeadingID antepone
// ".ID(id)" para el caso new_id-estático, donde el primer elemento de args
// ya es ese id sintético (ver la llamada en renderRequests que le pasa un
// arg extra con GoName "id").
func encoderChain(args []resolve.ResolvedArg, withLeadingID bool) string {
	chain := "NewEncoder()"
	for i, a := range args {
		if withLeadingID && i == 0 {
			chain += ".ID(id)"
			continue
		}
		if a.IsFD {
			continue
		}
		switch a.Type.TypeString {
		case "int32":
			chain += ".Int32(" + a.GoName + ")"
		case "uint32":
			chain += ".Uint32(" + a.GoName + ")"
		case "Fixed":
			chain += ".Fixed(" + a.GoName + ")"
		case "string":
			chain += ".String(" + a.GoName + ")"
		case "*string":
			chain += ".StringOpt(" + a.GoName + ")"
		case "[]byte":
			chain += ".Array(" + a.GoName + ")"
		default:
			switch a.Type.Kind {
			case resolve.KindEnum:
				chain += ".Uint32(uint32(" + a.GoName + "))"
			case resolve.KindObject:
				if a.Type.AllowNull {
					chain += ".ID(" + a.GoName + "ID)"
				} else {
					chain += ".ID(" + a.GoName + ".ID())"
				}
			case resolve.KindObjectDyn:
				chain += ".Uint32(" + a.GoName + ")"
			}
		}
	}
	return chain
}

// fdVariadic arma ", fd1, fd2" para los args fd de un request, en su orden
// del XML -- van todos al final como variádico de Send.
func fdVariadic(args []resolve.ResolvedArg) string {
	var s string
	for _, a := range args {
		if a.IsFD {
			s += ", " + a.GoName
		}
	}
	return s
}

func joinComma(parts []string) string {
	s := ""
	for i, p := range parts {
		if i > 0 {
			s += ", "
		}
		s += p
	}
	return s
}

func renderOpcodeConsts(b *bytes.Buffer, iface resolve.ResolvedInterface) {
	if len(iface.Requests) == 0 && len(iface.Events) == 0 {
		return
	}
	fmt.Fprintf(b, "const (\n")
	for _, r := range iface.Requests {
		fmt.Fprintf(b, "\topReq%s%s = %d\n", iface.GoType, r.GoName, reqOpcode(iface, r.XMLName))
	}
	for _, ev := range iface.Events {
		fmt.Fprintf(b, "\topEvt%s%s = %d\n", iface.GoType, ev.GoName, evtOpcode(iface, ev.XMLName))
	}
	fmt.Fprintf(b, ")\n\n")
}

func reqOpcode(iface resolve.ResolvedInterface, xmlName string) int {
	for i, r := range iface.Requests {
		if r.XMLName == xmlName {
			return i
		}
	}
	return -1
}

func evtOpcode(iface resolve.ResolvedInterface, xmlName string) int {
	for i, ev := range iface.Events {
		if ev.XMLName == xmlName {
			return i
		}
	}
	return -1
}

func renderStructAndConstructor(b *bytes.Buffer, iface resolve.ResolvedInterface) {
	renderDocComment(b, "", iface.GoType, iface.Summary, iface.Doc, nil)
	fmt.Fprintf(b, "type %s struct {\n\tProxyBase\n\tlistener %sListener\n}\n\n", iface.GoType, iface.GoType)
	fmt.Fprintf(b, "var _ Proxy = (*%s)(nil)\n\n", iface.GoType)
	// El parámetro se llama "conn", no "c": si iface.Recv también fuera "c"
	// (Callback, Compositor -- cualquier interfaz cuyo GoType empiece por
	// 'C'), "c := &Foo{...}" con un parámetro "c *Conn" sería una
	// redeclaración inválida ("no new variables on left side of :="). Un
	// nombre de parámetro que nunca puede coincidir con un receptor de una
	// sola letra evita la colisión para cualquier interfaz, no solo las de
	// hoy.
	fmt.Fprintf(b, "func new%s(id, version uint32, conn *Conn) *%s {\n", iface.GoType, iface.GoType)
	fmt.Fprintf(b, "\treturn new%sFromProxyBase(NewProxyBase(id, version, conn))\n}\n\n", iface.GoType)
	fmt.Fprintf(b, "func new%sFromProxyBase(base ProxyBase) *%s {\n", iface.GoType, iface.GoType)
	fmt.Fprintf(b, "\t%s := &%s{ProxyBase: base}\n", iface.Recv, iface.GoType)
	if iface.HasEvents {
		fmt.Fprintf(b, "\t%s.OnClear = func() { %s.listener = %sListener{} }\n", iface.Recv, iface.Recv, iface.GoType)
	}
	fmt.Fprintf(b, "\treturn %s\n}\n\n", iface.Recv)
	if iface.PublicListener {
		fmt.Fprintf(b, "func (%s *%s) SetListener(l %sListener) { %s.listener = l }\n\n", iface.Recv, iface.GoType, iface.GoType, iface.Recv)
	}
}

func renderListener(b *bytes.Buffer, iface resolve.ResolvedInterface) {
	fmt.Fprintf(b, "type %sListener struct {\n", iface.GoType)
	for _, ev := range iface.Events {
		renderDocComment(b, "\t", ev.GoName, ev.Summary, ev.Doc, docParamsFor(ev.Args))
		fmt.Fprintf(b, "\t%s func(%s)\n", ev.GoName, paramList(ev.Args))
	}
	fmt.Fprintf(b, "}\n\n")
}

func renderDescriptor(b *bytes.Buffer, iface resolve.ResolvedInterface) {
	fmt.Fprintf(b, "var %sInterface = Interface[*%s]{\n", iface.GoType, iface.GoType)
	fmt.Fprintf(b, "\tName:       %q,\n", iface.XMLName)
	fmt.Fprintf(b, "\tMaxVersion: %d,\n", iface.MaxVersion)
	fmt.Fprintf(b, "\tNew:        new%sFromProxyBase,\n", iface.GoType)
	fmt.Fprintf(b, "}\n\n")
}

func renderDispatch(b *bytes.Buffer, iface resolve.ResolvedInterface) error {
	// El parámetro se llama "dec", no "d": si iface.Recv también fuera "d"
	// (Display, DataDevice, DataDeviceManager, DataOffer, DataSource --
	// cualquier interfaz cuyo GoType empiece por 'D'), "d *Decoder" chocaría
	// con el receptor ("d redeclared in this block").
	fmt.Fprintf(b, "func (%s *%s) Dispatch(opcode uint16, dec *Decoder) error {\n", iface.Recv, iface.GoType)
	fmt.Fprintf(b, "\tswitch opcode {\n")
	for _, ev := range iface.Events {
		renderEventCase(b, iface, ev)
	}
	fmt.Fprintf(b, "\tdefault:\n\t\treturn fmt.Errorf(\"wlcore: opcode %%d desconocido en %s\", opcode)\n", iface.XMLName)
	fmt.Fprintf(b, "\t}\n")
	if len(iface.Events) > 0 {
		// Con al menos un evento, los case (que no hacen return -- ver
		// renderEventCase) caen al final del switch, así que hace falta un
		// return explícito. Con cero eventos el switch solo tiene el
		// default, que sí termina en return: Go ya lo considera un
		// "terminating statement" (spec, "Terminating statements"), así
		// que un "return nil" después sería código muerto -- "go vet" lo
		// marca como unreachable en las 8 interfaces de wayland.xml sin
		// eventos (wl_compositor, wl_region, ...).
		fmt.Fprintf(b, "\treturn nil\n")
	}
	fmt.Fprintf(b, "}\n\n")
	return nil
}

func renderEventCase(b *bytes.Buffer, iface resolve.ResolvedInterface, ev resolve.ResolvedEvent) {
	fmt.Fprintf(b, "\tcase opEvt%s%s:\n", iface.GoType, ev.GoName)
	for _, a := range ev.Args {
		renderEventArgDecode(b, iface, a)
	}
	if ev.FDOwning {
		// ev.Destructor no se trata aquí aunque en principio podría (ningún
		// evento real de wayland.xml combina type="destructor" con un arg
		// fd): el fd viaja atado a un objeto que el propio evento acaba de
		// destruir, una combinación que el protocolo Wayland no usa y que
		// añadir sin una fixture real que la ejercite sería código muerto.
		fmt.Fprintf(b, "\t\tif err := dec.Err(); err != nil {\n")
		for _, a := range ev.Args {
			if a.IsFD {
				fmt.Fprintf(b, "\t\t\tDropFD(%s)\n", a.GoName)
			}
		}
		fmt.Fprintf(b, "\t\t\treturn err\n\t\t}\n")
		fmt.Fprintf(b, "\t\tif %s.listener.%s == nil {\n", iface.Recv, ev.GoName)
		for _, a := range ev.Args {
			if a.IsFD {
				fmt.Fprintf(b, "\t\t\tDropFD(%s)\n", a.GoName)
			}
		}
		fmt.Fprintf(b, "\t\t\tbreak\n\t\t}\n")
		fmt.Fprintf(b, "\t\t%s.listener.%s(%s)\n", iface.Recv, ev.GoName, argNameList(ev.Args))
		return
	}
	fmt.Fprintf(b, "\t\tif err := dec.Err(); err != nil {\n\t\t\treturn err\n\t\t}\n")
	for _, a := range ev.Args {
		if a.Type.Kind == resolve.KindNewIDStatic {
			fmt.Fprintf(b, "\t\t%s := new%sFromProxyBase(NewProxyBase(%sID, %s.Version(), %s.Conn()))\n", a.GoName, a.Type.ObjGoType, a.GoName, iface.Recv, iface.Recv)
			fmt.Fprintf(b, "\t\t%s.Conn().Register(%s)\n", iface.Recv, a.GoName)
		} else if a.Type.Kind == resolve.KindObject {
			fmt.Fprintf(b, "\t\t%s, _ := %s.Conn().Lookup(%sID).(%s)\n", a.GoName, iface.Recv, a.GoName, a.Type.TypeString)
		}
	}
	fmt.Fprintf(b, "\t\tif %s.listener.%s != nil {\n", iface.Recv, ev.GoName)
	fmt.Fprintf(b, "\t\t\t%s.listener.%s(%s)\n\t\t}\n", iface.Recv, ev.GoName, argNameList(ev.Args))
	if ev.Destructor {
		// Un evento destructor (wl_callback.done es el único caso hoy)
		// destruye el proxy tanto si había listener como si no -- por eso
		// esta llamada vive fuera del if de arriba, igual que el request
		// destructor (case r.Destructor) ya hace con c.Conn().destroy(c).
		fmt.Fprintf(b, "\t\t%s.Conn().destroy(%s)\n", iface.Recv, iface.Recv)
	}
}

func renderEventArgDecode(b *bytes.Buffer, iface resolve.ResolvedInterface, a resolve.ResolvedArg) {
	switch {
	case a.IsFD:
		fmt.Fprintf(b, "\t\t%s := dec.FD()\n", a.GoName)
	case a.Type.Kind == resolve.KindNewIDStatic || a.Type.Kind == resolve.KindObject:
		fmt.Fprintf(b, "\t\t%sID := dec.ID()\n", a.GoName)
	default:
		fmt.Fprintf(b, "\t\t%s := %s\n", a.GoName, decodeExpr(a))
	}
}

func decodeExpr(a resolve.ResolvedArg) string {
	switch a.Type.Kind {
	case resolve.KindFixed:
		return "dec.Fixed()"
	case resolve.KindEnum:
		return a.Type.TypeString + "(dec.Uint32())"
	case resolve.KindObject:
		return "dec.ID()" // el Dispatch todavía tiene que resolverlo con Lookup -- ver nota abajo
	case resolve.KindObjectDyn:
		return "dec.Uint32()"
	}
	switch a.Type.TypeString {
	case "int32":
		return "dec.Int32()"
	case "uint32":
		return "dec.Uint32()"
	case "string":
		return "dec.String()"
	case "*string":
		return "dec.StringOpt()"
	case "[]byte":
		return "dec.Array()"
	}
	return "dec.Uint32()"
}

func argNameList(args []resolve.ResolvedArg) string {
	var parts []string
	for _, a := range args {
		parts = append(parts, a.GoName)
	}
	return joinComma(parts)
}

func renderEnums(b *bytes.Buffer, iface resolve.ResolvedInterface) {
	for _, en := range iface.Enums {
		renderDocComment(b, "", en.GoName, en.Summary, en.Doc, nil)
		fmt.Fprintf(b, "type %s uint32\n\n", en.GoName)
		fmt.Fprintf(b, "const (\n")
		for _, e := range en.Entries {
			if e.Summary != "" {
				fmt.Fprintf(b, "\t%s %s = %s // %s\n", e.GoName, en.GoName, e.Value, e.Summary)
			} else {
				fmt.Fprintf(b, "\t%s %s = %s\n", e.GoName, en.GoName, e.Value)
			}
		}
		fmt.Fprintf(b, ")\n\n")
		if en.Bitfield {
			fmt.Fprintf(b, "func (v %s) Has(flag %s) bool { return v&flag != 0 }\n\n", en.GoName, en.GoName)
		}
	}
}

// Emit renderiza y escribe un .gen.go por interfaz en outDir. No escribe
// nada si cualquier interfaz falla al renderizar o formatear -- todo o
// nada, para no dejar una regeneración a medias mezclada con ficheros de
// una corrida anterior que sí generaron bien.
func Emit(m resolve.Model, outDir string) error {
	ifaces := append([]resolve.ResolvedInterface(nil), m.Interfaces...)
	sort.Slice(ifaces, func(i, j int) bool { return ifaces[i].XMLName < ifaces[j].XMLName })

	type file struct {
		name string
		data []byte
	}
	var files []file
	for _, iface := range ifaces {
		src, err := RenderInterface(iface)
		if err != nil {
			return fmt.Errorf("codegen: renderizando %s: %w", iface.XMLName, err)
		}
		formatted, err := format.Source(src)
		if err != nil {
			return fmt.Errorf("codegen: %s produjo Go inválido: %w", iface.XMLName, err)
		}
		files = append(files, file{name: fileName(iface), data: formatted})
	}

	for _, f := range files {
		path := filepath.Join(outDir, f.name)
		if err := os.WriteFile(path, f.data, 0o644); err != nil {
			return fmt.Errorf("codegen: escribiendo %s: %w", path, err)
		}
	}
	return nil
}

// fileName deriva el nombre del fichero del GoType, no del XMLName --
// snake_case del tipo Go, no el nombre XML con su prefijo de protocolo.
// wl_shm_pool -> ShmPool -> shm_pool.gen.go.
func fileName(iface resolve.ResolvedInterface) string {
	return pascalToSnake(iface.GoType) + ".gen.go"
}

func pascalToSnake(s string) string {
	var b strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			b.WriteByte('_')
		}
		b.WriteRune(r)
	}
	return strings.ToLower(b.String())
}
