package codegen

import (
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/romycode/ggui/cmd/waygenerator/internal/resolve"
)

func TestEmitWritesOneFormattedFilePerInterface(t *testing.T) {
	dir := t.TempDir()
	m := resolve.Model{Interfaces: []resolve.ResolvedInterface{
		skeletonEnumFixture(), // wl_fake_thing -> FakeThing -> fake_thing.gen.go
		versioningFixture(),   // wl_gadget -> Gadget -> gadget.gen.go
	}}
	if err := Emit(m, dir); err != nil {
		t.Fatalf("Emit: %v", err)
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	var names []string
	for _, e := range entries {
		names = append(names, e.Name())
	}
	sort.Strings(names)
	want := []string{"fake_thing.gen.go", "gadget.gen.go"}
	if len(names) != len(want) {
		t.Fatalf("files = %v, want %v", names, want)
	}
	for i := range want {
		if names[i] != want[i] {
			t.Errorf("files = %v, want %v", names, want)
		}
	}
	data, err := os.ReadFile(filepath.Join(dir, "fake_thing.gen.go"))
	if err != nil {
		t.Fatal(err)
	}
	// go/format.Source normalizes the column spacing of an aligned const
	// block -- if the file went through format.Source, that alignment
	// disappears from a short list like this one (a single const line
	// doesn't align with anything). The real check is simpler: the file
	// has to parse as valid Go, which already rules out any serious
	// template bug. Checking the generated header is enough for this
	// driver integration test.
	if !contains(data, "// Code generated by waygenerator. DO NOT EDIT.") {
		t.Error("missing the generated-code header")
	}
}

func contains(data []byte, s string) bool {
	return len(data) >= len(s) && string(data[:len(s)]) == s
}

func TestEmitRoutesEachPackageToItsOwnDirectory(t *testing.T) {
	// Regression: xdg_surface (xdgshell) and wl_surface (wlcore) share the
	// GoType "Surface" once the prefix is stripped -- same file name
	// (surface.gen.go). Without per-package routing, Emit wrote both to
	// the same outDir and the second silently clobbered the first.
	wlcoreDir := t.TempDir()
	m := resolve.Model{Interfaces: []resolve.ResolvedInterface{
		{XMLName: "wl_surface", GoPackage: "wlcore", GoType: "Surface", Recv: "s", PublicListener: true},
		{XMLName: "xdg_surface", GoPackage: "xdgshell", GoType: "Surface", Recv: "s", PublicListener: true},
	}}
	if err := Emit(m, wlcoreDir); err != nil {
		t.Fatalf("Emit: %v", err)
	}

	wlcoreData, err := os.ReadFile(filepath.Join(wlcoreDir, "surface.gen.go"))
	if err != nil {
		t.Fatalf("wlcore/surface.gen.go: %v", err)
	}
	if !strings.Contains(string(wlcoreData), "package wlcore\n") {
		t.Errorf("wlcore/surface.gen.go no dice \"package wlcore\": %s", wlcoreData)
	}

	xdgshellDir := filepath.Join(filepath.Dir(wlcoreDir), "xdgshell")
	xdgshellData, err := os.ReadFile(filepath.Join(xdgshellDir, "surface.gen.go"))
	if err != nil {
		t.Fatalf("xdgshell/surface.gen.go (wlcore sibling directory): %v", err)
	}
	if !strings.Contains(string(xdgshellData), "package xdgshell\n") {
		t.Errorf("xdgshell/surface.gen.go no dice \"package xdgshell\": %s", xdgshellData)
	}
}

func TestEmitFailsOnInvalidGoWithoutWritingPartialOutput(t *testing.T) {
	dir := t.TempDir()
	// A ResolvedInterface with an empty GoType produces invalid Go (an
	// unnamed type) -- Emit must fail and not leave partially written files.
	m := resolve.Model{Interfaces: []resolve.ResolvedInterface{
		{XMLName: "wl_broken", GoPackage: "wlcore", GoType: "", Recv: "x", PublicListener: true},
	}}
	if err := Emit(m, dir); err == nil {
		t.Fatal("Emit should fail with an empty GoType (invalid Go)")
	}
	entries, _ := os.ReadDir(dir)
	if len(entries) != 0 {
		t.Errorf("Emit left %d files written after failing, want 0", len(entries))
	}
}
