package codegen

import (
	"os"
	"path/filepath"
	"sort"
	"testing"

	"github.com/romycode/ggui/cmd/waygenerator/internal/resolve"
)

func TestEmitWritesOneFormattedFilePerInterface(t *testing.T) {
	dir := t.TempDir()
	m := resolve.Model{Interfaces: []resolve.ResolvedInterface{
		skeletonEnumFixture(), // wl_fake_thing -> FakeThing -> fake_thing.gen.go
		versioningFixture(),   // wl_gadget -> Gadget -> gadget.gen.go
	}}
	if err := Emit(m, dir); err != nil {
		t.Fatalf("Emit: %v", err)
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	var names []string
	for _, e := range entries {
		names = append(names, e.Name())
	}
	sort.Strings(names)
	want := []string{"fake_thing.gen.go", "gadget.gen.go"}
	if len(names) != len(want) {
		t.Fatalf("ficheros = %v, want %v", names, want)
	}
	for i := range want {
		if names[i] != want[i] {
			t.Errorf("ficheros = %v, want %v", names, want)
		}
	}
	data, err := os.ReadFile(filepath.Join(dir, "fake_thing.gen.go"))
	if err != nil {
		t.Fatal(err)
	}
	// go/format.Source normaliza espaciado en columnas de un const block
	// alineado -- si el fichero pasó por format.Source, esa alineación
	// desaparece de una lista corta como esta (una sola línea de const no
	// se alinea con nada). La comprobación real es más simple: el fichero
	// tiene que parsear como Go válido, lo que ya deja fuera cualquier
	// bug de plantilla grave. Comprobar la cabecera generada basta para
	// esta prueba de integración del driver.
	if !contains(data, "// Code generated by waygenerator. DO NOT EDIT.") {
		t.Error("falta la cabecera de código generado")
	}
}

func contains(data []byte, s string) bool {
	return len(data) >= len(s) && string(data[:len(s)]) == s
}

func TestEmitFailsOnInvalidGoWithoutWritingPartialOutput(t *testing.T) {
	dir := t.TempDir()
	// Un ResolvedInterface con un GoType vacío produce Go inválido (tipo
	// sin nombre) -- Emit debe fallar y no dejar ficheros a medio escribir.
	m := resolve.Model{Interfaces: []resolve.ResolvedInterface{
		{XMLName: "wl_broken", GoPackage: "wlcore", GoType: "", Recv: "x", PublicListener: true},
	}}
	if err := Emit(m, dir); err == nil {
		t.Fatal("Emit debería fallar con un GoType vacío (Go inválido)")
	}
	entries, _ := os.ReadDir(dir)
	if len(entries) != 0 {
		t.Errorf("Emit dejó %d ficheros escritos tras fallar, want 0", len(entries))
	}
}
