// Code generated by waygenerator. DO NOT EDIT.

package cursorshape

import (
	"fmt"

	"github.com/romycode/ggui/wayland/tablet"
	"github.com/romycode/ggui/wayland/wlcore"
)

// CursorShapeManager: cursor shape manager
//
// This global offers an alternative, optional way to set cursor images. This
// new way uses enumerated cursors instead of a wl_surface like
// wl_pointer.set_cursor does.
//
// Warning! The protocol described in this file is currently in the testing
// phase. Backward compatible changes may be added together with the
// corresponding interface version bump. Backward incompatible changes can
// only be done by creating a new major version of the extension.
type CursorShapeManager struct {
	wlcore.ProxyBase
	listener CursorShapeManagerListener
}

var _ wlcore.Proxy = (*CursorShapeManager)(nil)

func newCursorShapeManager(id, version uint32, conn *wlcore.Conn) *CursorShapeManager {
	return newCursorShapeManagerFromProxyBase(wlcore.NewProxyBase(id, version, conn))
}

func newCursorShapeManagerFromProxyBase(base wlcore.ProxyBase) *CursorShapeManager {
	c := &CursorShapeManager{ProxyBase: base}
	return c
}

func (c *CursorShapeManager) SetListener(l CursorShapeManagerListener) { c.listener = l }

type CursorShapeManagerListener struct {
}

var CursorShapeManagerInterface = wlcore.Interface[*CursorShapeManager]{
	Name:       "wp_cursor_shape_manager_v1",
	MaxVersion: 2,
	New:        newCursorShapeManagerFromProxyBase,
}

// Destroy: destroy the manager
//
// Destroy the cursor shape manager.
func (c *CursorShapeManager) Destroy() error {
	err := c.Conn().Send(c.ID(), opReqCursorShapeManagerDestroy, wlcore.NewEncoder())
	c.Conn().Destroy(c)
	return err
}

// GetPointer: manage the cursor shape of a pointer device
//
// Obtain a wp_cursor_shape_device_v1 for a wl_pointer object.
//
// When the pointer capability is removed from the wl_seat, the
// wp_cursor_shape_device_v1 object becomes inert.
func (c *CursorShapeManager) GetPointer(pointer *wlcore.Pointer) (*CursorShapeDevice, error) {
	id := c.Conn().NewID()
	x := newCursorShapeDeviceFromProxyBase(wlcore.NewProxyBase(id, c.Version(), c.Conn()))
	c.Conn().Register(x)

	e := wlcore.NewEncoder().ID(id).ID(pointer.ID())
	if err := c.Conn().Send(c.ID(), opReqCursorShapeManagerGetPointer, e); err != nil {
		return nil, err
	}
	return x, nil
}

// GetTabletToolV2: manage the cursor shape of a tablet tool device
//
// Obtain a wp_cursor_shape_device_v1 for a zwp_tablet_tool_v2 object.
//
// When the zwp_tablet_tool_v2 is removed, the wp_cursor_shape_device_v1
// object becomes inert.
func (c *CursorShapeManager) GetTabletToolV2(tabletTool *tablet.TabletTool) (*CursorShapeDevice, error) {
	id := c.Conn().NewID()
	x := newCursorShapeDeviceFromProxyBase(wlcore.NewProxyBase(id, c.Version(), c.Conn()))
	c.Conn().Register(x)

	e := wlcore.NewEncoder().ID(id).ID(tabletTool.ID())
	if err := c.Conn().Send(c.ID(), opReqCursorShapeManagerGetTabletToolV2, e); err != nil {
		return nil, err
	}
	return x, nil
}

func (c *CursorShapeManager) Dispatch(opcode uint16, dec *wlcore.Decoder) error {
	switch opcode {
	default:
		return fmt.Errorf("cursorshape: unknown opcode %d in wp_cursor_shape_manager_v1", opcode)
	}
}

const (
	opReqCursorShapeManagerDestroy         = 0
	opReqCursorShapeManagerGetPointer      = 1
	opReqCursorShapeManagerGetTabletToolV2 = 2
)
