// Code generated by waygenerator. DO NOT EDIT.

package cursorshape

import (
	"fmt"

	"github.com/romycode/ggui/wayland/wlcore"
)

// CursorShapeDevice: cursor shape for a device
//
// This interface allows clients to set the cursor shape.
type CursorShapeDevice struct {
	wlcore.ProxyBase
	listener CursorShapeDeviceListener
}

var _ wlcore.Proxy = (*CursorShapeDevice)(nil)

func newCursorShapeDevice(id, version uint32, conn *wlcore.Conn) *CursorShapeDevice {
	return newCursorShapeDeviceFromProxyBase(wlcore.NewProxyBase(id, version, conn))
}

func newCursorShapeDeviceFromProxyBase(base wlcore.ProxyBase) *CursorShapeDevice {
	c := &CursorShapeDevice{ProxyBase: base}
	return c
}

// SetListener installs the handlers for wp_cursor_shape_device_v1's events,
// replacing any already installed. A nil field ignores that event; a file
// descriptor arriving in an ignored event is closed, not leaked.
func (c *CursorShapeDevice) SetListener(l CursorShapeDeviceListener) { c.listener = l }

// CursorShapeDeviceListener holds the handlers for
// wp_cursor_shape_device_v1's events. Its zero value ignores every event.
// See [CursorShapeDevice.SetListener].
type CursorShapeDeviceListener struct {
}

// CursorShapeDeviceInterface describes wp_cursor_shape_device_v1 for
// [wlcore.Registry.Bind]: the name it carries on the wire and version 2,
// the highest this binding implements. Bind negotiates that against the
// version the compositor advertises, so a call site never repeats either
// value.
var CursorShapeDeviceInterface = wlcore.Interface[*CursorShapeDevice]{
	Name:       "wp_cursor_shape_device_v1",
	MaxVersion: 2,
	New:        newCursorShapeDeviceFromProxyBase,
}

// Destroy: destroy the cursor shape device
//
// Destroy the cursor shape device.
//
// The device cursor shape remains unchanged.
func (c *CursorShapeDevice) Destroy() error {
	err := c.Conn().Send(c.ID(), opReqCursorShapeDeviceDestroy, wlcore.NewEncoder())
	c.Conn().Destroy(c)
	return err
}

// SetShape: set device cursor to the shape
//
// Sets the device cursor to the specified shape. The compositor will
// change the cursor image based on the specified shape.
//
// The cursor actually changes only if the input device focus is one of
// the requesting client's surfaces. If any, the previous cursor image
// (surface or shape) is replaced.
//
// The "shape" argument must be a valid enum entry, otherwise the
// invalid_shape protocol error is raised.
//
// This is similar to the wl_pointer.set_cursor and
// zwp_tablet_tool_v2.set_cursor requests, but this request accepts a
// shape instead of contents in the form of a surface. Clients can mix
// set_cursor and set_shape requests.
//
// The serial parameter must match the latest wl_pointer.enter or
// zwp_tablet_tool_v2.proximity_in serial number sent to the client.
// Otherwise the request will be ignored.
//
// Parameters:
//   - serial: serial number of the enter event
func (c *CursorShapeDevice) SetShape(serial uint32, shape CursorShapeDeviceShape) error {
	e := wlcore.NewEncoder().Uint32(serial).Uint32(uint32(shape))
	return c.Conn().Send(c.ID(), opReqCursorShapeDeviceSetShape, e)
}

// Dispatch decodes one wp_cursor_shape_device_v1 event and calls the
// matching field of the listener. The connection calls it while pumping
// messages; it is exported only because the runtime's Proxy interface
// requires it.
func (c *CursorShapeDevice) Dispatch(opcode uint16, dec *wlcore.Decoder) error {
	switch opcode {
	default:
		return fmt.Errorf("cursorshape: unknown opcode %d in wp_cursor_shape_device_v1", opcode)
	}
}

// CursorShapeDeviceShape: cursor shapes
//
// This enum describes cursor shapes.
//
// The names are taken from the CSS W3C specification:
// https://w3c.github.io/csswg-drafts/css-ui/#cursor
// with a few additions.
//
// Note that there are some groups of cursor shapes that are related:
// The first group is drag-and-drop cursors which are used to indicate
// the selected action during dnd operations. The second group is resize
// cursors which are used to indicate resizing and moving possibilities
// on window borders. It is recommended that the shapes in these groups
// should use visually compatible images and metaphors.
type CursorShapeDeviceShape uint32

const (
	CursorShapeDeviceShapeDefault      CursorShapeDeviceShape = 1  // default cursor
	CursorShapeDeviceShapeContextMenu  CursorShapeDeviceShape = 2  // a context menu is available for the object under the cursor
	CursorShapeDeviceShapeHelp         CursorShapeDeviceShape = 3  // help is available for the object under the cursor
	CursorShapeDeviceShapePointer      CursorShapeDeviceShape = 4  // pointer that indicates a link or another interactive element
	CursorShapeDeviceShapeProgress     CursorShapeDeviceShape = 5  // progress indicator
	CursorShapeDeviceShapeWait         CursorShapeDeviceShape = 6  // program is busy, user should wait
	CursorShapeDeviceShapeCell         CursorShapeDeviceShape = 7  // a cell or set of cells may be selected
	CursorShapeDeviceShapeCrosshair    CursorShapeDeviceShape = 8  // simple crosshair
	CursorShapeDeviceShapeText         CursorShapeDeviceShape = 9  // text may be selected
	CursorShapeDeviceShapeVerticalText CursorShapeDeviceShape = 10 // vertical text may be selected
	CursorShapeDeviceShapeAlias        CursorShapeDeviceShape = 11 // drag-and-drop: alias of/shortcut to something is to be created
	CursorShapeDeviceShapeCopy         CursorShapeDeviceShape = 12 // drag-and-drop: something is to be copied
	CursorShapeDeviceShapeMove         CursorShapeDeviceShape = 13 // drag-and-drop: something is to be moved
	CursorShapeDeviceShapeNoDrop       CursorShapeDeviceShape = 14 // drag-and-drop: the dragged item cannot be dropped at the current cursor location
	CursorShapeDeviceShapeNotAllowed   CursorShapeDeviceShape = 15 // drag-and-drop: the requested action will not be carried out
	CursorShapeDeviceShapeGrab         CursorShapeDeviceShape = 16 // drag-and-drop: something can be grabbed
	CursorShapeDeviceShapeGrabbing     CursorShapeDeviceShape = 17 // drag-and-drop: something is being grabbed
	CursorShapeDeviceShapeEResize      CursorShapeDeviceShape = 18 // resizing: the east border is to be moved
	CursorShapeDeviceShapeNResize      CursorShapeDeviceShape = 19 // resizing: the north border is to be moved
	CursorShapeDeviceShapeNeResize     CursorShapeDeviceShape = 20 // resizing: the north-east corner is to be moved
	CursorShapeDeviceShapeNwResize     CursorShapeDeviceShape = 21 // resizing: the north-west corner is to be moved
	CursorShapeDeviceShapeSResize      CursorShapeDeviceShape = 22 // resizing: the south border is to be moved
	CursorShapeDeviceShapeSeResize     CursorShapeDeviceShape = 23 // resizing: the south-east corner is to be moved
	CursorShapeDeviceShapeSwResize     CursorShapeDeviceShape = 24 // resizing: the south-west corner is to be moved
	CursorShapeDeviceShapeWResize      CursorShapeDeviceShape = 25 // resizing: the west border is to be moved
	CursorShapeDeviceShapeEwResize     CursorShapeDeviceShape = 26 // resizing: the east and west borders are to be moved
	CursorShapeDeviceShapeNsResize     CursorShapeDeviceShape = 27 // resizing: the north and south borders are to be moved
	CursorShapeDeviceShapeNeswResize   CursorShapeDeviceShape = 28 // resizing: the north-east and south-west corners are to be moved
	CursorShapeDeviceShapeNwseResize   CursorShapeDeviceShape = 29 // resizing: the north-west and south-east corners are to be moved
	CursorShapeDeviceShapeColResize    CursorShapeDeviceShape = 30 // resizing: that the item/column can be resized horizontally
	CursorShapeDeviceShapeRowResize    CursorShapeDeviceShape = 31 // resizing: that the item/row can be resized vertically
	CursorShapeDeviceShapeAllScroll    CursorShapeDeviceShape = 32 // something can be scrolled in any direction
	CursorShapeDeviceShapeZoomIn       CursorShapeDeviceShape = 33 // something can be zoomed in
	CursorShapeDeviceShapeZoomOut      CursorShapeDeviceShape = 34 // something can be zoomed out
	CursorShapeDeviceShapeDndAsk       CursorShapeDeviceShape = 35 // drag-and-drop: the user will select which action will be carried out (non-css value)
	CursorShapeDeviceShapeAllResize    CursorShapeDeviceShape = 36 // resizing: something can be moved or resized in any direction (non-css value)
)

// CursorShapeDeviceError enumerates the protocol errors
// wp_cursor_shape_device_v1 can raise. The compositor reports one through
// wl_display.error.
type CursorShapeDeviceError uint32

const (
	CursorShapeDeviceErrorInvalidShape CursorShapeDeviceError = 1 // the specified shape value is invalid
)

const (
	opReqCursorShapeDeviceDestroy  = 0
	opReqCursorShapeDeviceSetShape = 1
)
