// Package cursorshape contains the bindings for cursor-shape-v1, which
// sets the pointer cursor by name instead of by pixels.
//
// Bind [CursorShapeManagerInterface] from the registry and get a
// [CursorShapeDevice] for a wl_pointer with
// [CursorShapeManager.GetPointer]. Setting a shape then takes one request
// naming it -- default, text, grab, a resize edge -- with the serial from
// the pointer enter event.
//
// This replaces the older dance of loading a cursor theme, uploading the
// image into a shm buffer and attaching it to a dedicated surface. The
// compositor owns the theme, so the cursor matches the rest of the desktop
// and follows its scale.
//
// Staging protocol -- it can still change upstream.
//
// Generated by waygenerator from protocols/cursor-shape-v1.xml. Do not
// edit the .gen.go files.
package cursorshape
