// Package tablet contains the bindings for tablet-v2: graphics tablets,
// their styli, and the pads of buttons, rings, strips and dials on them.
//
// Bind [TabletManagerInterface] from the registry and call
// [TabletManager.GetTabletSeat] with a wl_seat. The seat then advertises
// each [Tablet], [TabletTool] and [TabletPad] plugged into it, as events
// rather than as registry globals.
//
// A tool reports far more than a pointer does: pressure, distance, tilt,
// rotation, and whether it is the nib or the eraser end. Tools that
// support it also carry a hardware serial, so a client can tell two styli
// apart and keep per-tool state across proximity events.
//
// Generated by waygenerator from protocols/tablet-v2.xml. Do not edit the
// .gen.go files.
package tablet
