// Code generated by waygenerator. DO NOT EDIT.

package tablet

import (
	"fmt"

	"github.com/romycode/ggui/wayland/wlcore"
)

// TabletPad: a set of buttons, rings, strips and dials
//
// A pad device is a set of buttons, rings, strips and dials
// usually physically present on the tablet device itself. Some
// exceptions exist where the pad device is physically detached, e.g. the
// Wacom ExpressKey Remote.
//
// Pad devices have no axes that control the cursor and are generally
// auxiliary devices to the tool devices used on the tablet surface.
//
// A pad device has a number of static characteristics, e.g. the number
// of rings. These capabilities are sent in an event sequence after the
// wp_tablet_seat.pad_added event before any actual events from this pad.
// This initial event sequence is terminated by a wp_tablet_pad.done
// event.
//
// All pad features (buttons, rings, strips and dials) are logically divided into
// groups and all pads have at least one group. The available groups are
// notified through the wp_tablet_pad.group event; the compositor will
// emit one event per group before emitting wp_tablet_pad.done.
//
// Groups may have multiple modes. Modes allow clients to map multiple
// actions to a single pad feature. Only one mode can be active per group,
// although different groups may have different active modes.
type TabletPad struct {
	wlcore.ProxyBase
	listener TabletPadListener
}

var _ wlcore.Proxy = (*TabletPad)(nil)

func newTabletPad(id, version uint32, conn *wlcore.Conn) *TabletPad {
	return newTabletPadFromProxyBase(wlcore.NewProxyBase(id, version, conn))
}

func newTabletPadFromProxyBase(base wlcore.ProxyBase) *TabletPad {
	t := &TabletPad{ProxyBase: base}
	t.OnClear = func() { t.listener = TabletPadListener{} }
	return t
}

// SetListener installs the handlers for zwp_tablet_pad_v2's events,
// replacing any already installed. A nil field ignores that event; a file
// descriptor arriving in an ignored event is closed, not leaked.
func (t *TabletPad) SetListener(l TabletPadListener) { t.listener = l }

// TabletPadListener holds the handlers for zwp_tablet_pad_v2's events. Its
// zero value ignores every event. See [TabletPad.SetListener].
type TabletPadListener struct {
	// Group: group announced
	//
	// Sent on wp_tablet_pad initialization to announce available groups.
	// One event is sent for each pad group available.
	//
	// This event is sent in the initial burst of events before the
	// wp_tablet_pad.done event. At least one group will be announced.
	Group func(padGroup *TabletPadGroup)
	// Path: path to the device
	//
	// A system-specific device path that indicates which device is behind
	// this wp_tablet_pad. This information may be used to gather additional
	// information about the device, e.g. through libwacom.
	//
	// The format of the path is unspecified, it may be a device node, a
	// sysfs path, or some other identifier. It is up to the client to
	// identify the string provided.
	//
	// This event is sent in the initial burst of events before the
	// wp_tablet_pad.done event.
	//
	// Parameters:
	//   - path: path to local device
	Path func(path string)
	// Buttons: buttons announced
	//
	// Sent on wp_tablet_pad initialization to announce the available
	// buttons.
	//
	// This event is sent in the initial burst of events before the
	// wp_tablet_pad.done event. This event is only sent when at least one
	// button is available.
	//
	// Parameters:
	//   - buttons: the number of buttons
	Buttons func(buttons uint32)
	// Done: pad description event sequence complete
	//
	// This event signals the end of the initial burst of descriptive
	// events. A client may consider the static description of the pad to
	// be complete and finalize initialization of the pad.
	Done func()
	// Button: physical button state
	//
	// Sent whenever the physical state of a button changes.
	//
	// Parameters:
	//   - time: the time of the event with millisecond granularity
	//   - button: the index of the button that changed state
	Button func(time uint32, button uint32, state TabletPadButtonState)
	// Enter: enter event
	//
	// Notification that this pad is focused on the specified surface.
	//
	// Parameters:
	//   - serial: serial number of the enter event
	//   - tablet: the tablet the pad is attached to
	//   - surface: surface the pad is focused on
	Enter func(serial uint32, tablet *Tablet, surface *wlcore.Surface)
	// Leave: leave event
	//
	// Notification that this pad is no longer focused on the specified
	// surface.
	//
	// Parameters:
	//   - serial: serial number of the leave event
	//   - surface: surface the pad is no longer focused on
	Leave func(serial uint32, surface *wlcore.Surface)
	// Removed: pad removed event
	//
	// Sent when the pad has been removed from the system. When a tablet
	// is removed its pad(s) will be removed too.
	//
	// When this event is received, the client must destroy all rings, strips
	// and groups that were offered by this pad, and issue wp_tablet_pad.destroy
	// the pad itself.
	Removed func()
}

// TabletPadInterface describes zwp_tablet_pad_v2 for
// [wlcore.Registry.Bind]: the name it carries on the wire and version 2,
// the highest this binding implements. Bind negotiates that against the
// version the compositor advertises, so a call site never repeats either
// value.
var TabletPadInterface = wlcore.Interface[*TabletPad]{
	Name:       "zwp_tablet_pad_v2",
	MaxVersion: 2,
	New:        newTabletPadFromProxyBase,
}

// SetFeedback: set compositor feedback
//
// Requests the compositor to use the provided feedback string
// associated with this button. This request should be issued immediately
// after a wp_tablet_pad_group.mode_switch event from the corresponding
// group is received, or whenever a button is mapped to a different
// action. See wp_tablet_pad_group.mode_switch for more details.
//
// Clients are encouraged to provide context-aware descriptions for
// the actions associated with each button, and compositors may use
// this information to offer visual feedback on the button layout
// (e.g. on-screen displays).
//
// Button indices start at 0. Setting the feedback string on a button
// that is reserved by the compositor (i.e. not belonging to any
// wp_tablet_pad_group) does not generate an error but the compositor
// is free to ignore the request.
//
// The provided string 'description' is a UTF-8 encoded string to be
// associated with this ring, and is considered user-visible; general
// internationalization rules apply.
//
// The serial argument will be that of the last
// wp_tablet_pad_group.mode_switch event received for the group of this
// button. Requests providing other serials than the most recent one will
// be ignored.
//
// Parameters:
//   - button: button index
//   - description: button description
//   - serial: serial of the mode switch event
func (t *TabletPad) SetFeedback(button uint32, description string, serial uint32) error {
	e := wlcore.NewEncoder().Uint32(button).String(description).Uint32(serial)
	return t.Conn().Send(t.ID(), opReqTabletPadSetFeedback, e)
}

// Destroy: destroy the pad object
//
// Destroy the wp_tablet_pad object. Objects created from this object
// are unaffected and should be destroyed separately.
func (t *TabletPad) Destroy() error {
	err := t.Conn().Send(t.ID(), opReqTabletPadDestroy, wlcore.NewEncoder())
	t.Conn().Destroy(t)
	return err
}

// Dispatch decodes one zwp_tablet_pad_v2 event and calls the matching field
// of the listener. The connection calls it while pumping messages; it is
// exported only because the runtime's Proxy interface requires it.
func (t *TabletPad) Dispatch(opcode uint16, dec *wlcore.Decoder) error {
	switch opcode {
	case opEvtTabletPadGroup:
		padGroupID := dec.ID()
		if err := dec.Err(); err != nil {
			return err
		}
		padGroup := newTabletPadGroupFromProxyBase(wlcore.NewProxyBase(padGroupID, t.Version(), t.Conn()))
		t.Conn().Register(padGroup)
		if t.listener.Group != nil {
			t.listener.Group(padGroup)
		}
	case opEvtTabletPadPath:
		path := dec.String()
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Path != nil {
			t.listener.Path(path)
		}
	case opEvtTabletPadButtons:
		buttons := dec.Uint32()
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Buttons != nil {
			t.listener.Buttons(buttons)
		}
	case opEvtTabletPadDone:
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Done != nil {
			t.listener.Done()
		}
	case opEvtTabletPadButton:
		time := dec.Uint32()
		button := dec.Uint32()
		state := TabletPadButtonState(dec.Uint32())
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Button != nil {
			t.listener.Button(time, button, state)
		}
	case opEvtTabletPadEnter:
		serial := dec.Uint32()
		tabletID := dec.ID()
		surfaceID := dec.ID()
		if err := dec.Err(); err != nil {
			return err
		}
		tablet, _ := t.Conn().Lookup(tabletID).(*Tablet)
		surface, _ := t.Conn().Lookup(surfaceID).(*wlcore.Surface)
		if t.listener.Enter != nil {
			t.listener.Enter(serial, tablet, surface)
		}
	case opEvtTabletPadLeave:
		serial := dec.Uint32()
		surfaceID := dec.ID()
		if err := dec.Err(); err != nil {
			return err
		}
		surface, _ := t.Conn().Lookup(surfaceID).(*wlcore.Surface)
		if t.listener.Leave != nil {
			t.listener.Leave(serial, surface)
		}
	case opEvtTabletPadRemoved:
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Removed != nil {
			t.listener.Removed()
		}
	default:
		return fmt.Errorf("tablet: unknown opcode %d in zwp_tablet_pad_v2", opcode)
	}
	return nil
}

// TabletPadButtonState: physical button state
//
// Describes the physical state of a button that caused the button
// event.
type TabletPadButtonState uint32

const (
	TabletPadButtonStateReleased TabletPadButtonState = 0 // the button is not pressed
	TabletPadButtonStatePressed  TabletPadButtonState = 1 // the button is pressed
)

const (
	opReqTabletPadSetFeedback = 0
	opReqTabletPadDestroy     = 1
	opEvtTabletPadGroup       = 0
	opEvtTabletPadPath        = 1
	opEvtTabletPadButtons     = 2
	opEvtTabletPadDone        = 3
	opEvtTabletPadButton      = 4
	opEvtTabletPadEnter       = 5
	opEvtTabletPadLeave       = 6
	opEvtTabletPadRemoved     = 7
)
