// Code generated by waygenerator. DO NOT EDIT.

package tablet

import (
	"fmt"

	"github.com/romycode/ggui/wayland/wlcore"
)

// TabletPadStrip: pad strip
//
// A linear interaction area, such as the strips found in Wacom Cintiq
// models.
//
// Events on a strip are logically grouped by the wl_tablet_pad_strip.frame
// event.
type TabletPadStrip struct {
	wlcore.ProxyBase
	listener TabletPadStripListener
}

var _ wlcore.Proxy = (*TabletPadStrip)(nil)

func newTabletPadStrip(id, version uint32, conn *wlcore.Conn) *TabletPadStrip {
	return newTabletPadStripFromProxyBase(wlcore.NewProxyBase(id, version, conn))
}

func newTabletPadStripFromProxyBase(base wlcore.ProxyBase) *TabletPadStrip {
	t := &TabletPadStrip{ProxyBase: base}
	t.OnClear = func() { t.listener = TabletPadStripListener{} }
	return t
}

// SetListener installs the handlers for zwp_tablet_pad_strip_v2's events,
// replacing any already installed. A nil field ignores that event; a file
// descriptor arriving in an ignored event is closed, not leaked.
func (t *TabletPadStrip) SetListener(l TabletPadStripListener) { t.listener = l }

// TabletPadStripListener holds the handlers for zwp_tablet_pad_strip_v2's
// events. Its zero value ignores every event. See
// [TabletPadStrip.SetListener].
type TabletPadStripListener struct {
	// Source: strip event source
	//
	// Source information for strip events.
	//
	// This event does not occur on its own. It is sent before a
	// wp_tablet_pad_strip.frame event and carries the source information
	// for all events within that frame.
	//
	// The source specifies how this event was generated. If the source is
	// wp_tablet_pad_strip.source.finger, a wp_tablet_pad_strip.stop event
	// will be sent when the user lifts their finger off the device.
	//
	// This event is optional. If the source is unknown for an interaction,
	// no event is sent.
	//
	// Parameters:
	//   - source: the event source
	Source func(source TabletPadStripSource)
	// Position: position changed
	//
	// Sent whenever the position on a strip changes.
	//
	// The position is normalized to a range of [0, 65535], the 0-value
	// represents the top-most and/or left-most position of the strip in
	// the pad's current rotation.
	//
	// Parameters:
	//   - position: the current position
	Position func(position uint32)
	// Stop: interaction stopped
	//
	// Stop notification for strip events.
	//
	// For some wp_tablet_pad_strip.source types, a wp_tablet_pad_strip.stop
	// event is sent to notify a client that the interaction with the strip
	// has terminated. This enables the client to implement kinetic
	// scrolling. See the wp_tablet_pad_strip.source documentation for
	// information on when this event may be generated.
	//
	// Any wp_tablet_pad_strip.position events with the same source after this
	// event should be considered as the start of a new interaction.
	Stop func()
	// Frame: end of a strip event sequence
	//
	// Indicates the end of a set of events that represent one logical
	// hardware strip event. A client is expected to accumulate the data
	// in all events within the frame before proceeding.
	//
	// All wp_tablet_pad_strip events before a wp_tablet_pad_strip.frame event belong
	// logically together. For example, on termination of a finger interaction
	// on a strip the compositor will send a wp_tablet_pad_strip.source event,
	// a wp_tablet_pad_strip.stop event and a wp_tablet_pad_strip.frame
	// event.
	//
	// A wp_tablet_pad_strip.frame event is sent for every logical event
	// group, even if the group only contains a single wp_tablet_pad_strip
	// event. Specifically, a client may get a sequence: position, frame,
	// position, frame, etc.
	//
	// Parameters:
	//   - time: timestamp with millisecond granularity
	Frame func(time uint32)
}

// TabletPadStripInterface describes zwp_tablet_pad_strip_v2 for
// [wlcore.Registry.Bind]: the name it carries on the wire and version 2,
// the highest this binding implements. Bind negotiates that against the
// version the compositor advertises, so a call site never repeats either
// value.
var TabletPadStripInterface = wlcore.Interface[*TabletPadStrip]{
	Name:       "zwp_tablet_pad_strip_v2",
	MaxVersion: 2,
	New:        newTabletPadStripFromProxyBase,
}

// SetFeedback: set compositor feedback
//
// Requests the compositor to use the provided feedback string
// associated with this strip. This request should be issued immediately
// after a wp_tablet_pad_group.mode_switch event from the corresponding
// group is received, or whenever the strip is mapped to a different
// action. See wp_tablet_pad_group.mode_switch for more details.
//
// Clients are encouraged to provide context-aware descriptions for
// the actions associated with the strip, and compositors may use this
// information to offer visual feedback about the button layout
// (eg. on-screen displays).
//
// The provided string 'description' is a UTF-8 encoded string to be
// associated with this ring, and is considered user-visible; general
// internationalization rules apply.
//
// The serial argument will be that of the last
// wp_tablet_pad_group.mode_switch event received for the group of this
// strip. Requests providing other serials than the most recent one will be
// ignored.
//
// Parameters:
//   - description: strip description
//   - serial: serial of the mode switch event
func (t *TabletPadStrip) SetFeedback(description string, serial uint32) error {
	e := wlcore.NewEncoder().String(description).Uint32(serial)
	return t.Conn().Send(t.ID(), opReqTabletPadStripSetFeedback, e)
}

// Destroy: destroy the strip object
//
// This destroys the client's resource for this strip object.
func (t *TabletPadStrip) Destroy() error {
	err := t.Conn().Send(t.ID(), opReqTabletPadStripDestroy, wlcore.NewEncoder())
	t.Conn().Destroy(t)
	return err
}

// Dispatch decodes one zwp_tablet_pad_strip_v2 event and calls the matching
// field of the listener. The connection calls it while pumping messages; it
// is exported only because the runtime's Proxy interface requires it.
func (t *TabletPadStrip) Dispatch(opcode uint16, dec *wlcore.Decoder) error {
	switch opcode {
	case opEvtTabletPadStripSource:
		source := TabletPadStripSource(dec.Uint32())
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Source != nil {
			t.listener.Source(source)
		}
	case opEvtTabletPadStripPosition:
		position := dec.Uint32()
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Position != nil {
			t.listener.Position(position)
		}
	case opEvtTabletPadStripStop:
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Stop != nil {
			t.listener.Stop()
		}
	case opEvtTabletPadStripFrame:
		time := dec.Uint32()
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Frame != nil {
			t.listener.Frame(time)
		}
	default:
		return fmt.Errorf("tablet: unknown opcode %d in zwp_tablet_pad_strip_v2", opcode)
	}
	return nil
}

// TabletPadStripSource: strip axis source
//
// Describes the source types for strip events. This indicates to the
// client how a strip event was physically generated; a client may
// adjust the user interface accordingly. For example, events
// from a "finger" source may trigger kinetic scrolling.
type TabletPadStripSource uint32

const (
	TabletPadStripSourceFinger TabletPadStripSource = 1 // finger
)

const (
	opReqTabletPadStripSetFeedback = 0
	opReqTabletPadStripDestroy     = 1
	opEvtTabletPadStripSource      = 0
	opEvtTabletPadStripPosition    = 1
	opEvtTabletPadStripStop        = 2
	opEvtTabletPadStripFrame       = 3
)
