// Code generated by waygenerator. DO NOT EDIT.

package tablet

import (
	"fmt"

	"github.com/romycode/ggui/wayland/wlcore"
)

// TabletManager: controller object for graphic tablet devices
//
// An object that provides access to the graphics tablets available on this
// system. All tablets are associated with a seat, to get access to the
// actual tablets, use wp_tablet_manager.get_tablet_seat.
type TabletManager struct {
	wlcore.ProxyBase
	listener TabletManagerListener
}

var _ wlcore.Proxy = (*TabletManager)(nil)

func newTabletManager(id, version uint32, conn *wlcore.Conn) *TabletManager {
	return newTabletManagerFromProxyBase(wlcore.NewProxyBase(id, version, conn))
}

func newTabletManagerFromProxyBase(base wlcore.ProxyBase) *TabletManager {
	t := &TabletManager{ProxyBase: base}
	return t
}

// SetListener installs the handlers for zwp_tablet_manager_v2's events,
// replacing any already installed. A nil field ignores that event; a file
// descriptor arriving in an ignored event is closed, not leaked.
func (t *TabletManager) SetListener(l TabletManagerListener) { t.listener = l }

// TabletManagerListener holds the handlers for zwp_tablet_manager_v2's
// events. Its zero value ignores every event. See
// [TabletManager.SetListener].
type TabletManagerListener struct {
}

// TabletManagerInterface describes zwp_tablet_manager_v2 for
// [wlcore.Registry.Bind]: the name it carries on the wire and version 2,
// the highest this binding implements. Bind negotiates that against the
// version the compositor advertises, so a call site never repeats either
// value.
var TabletManagerInterface = wlcore.Interface[*TabletManager]{
	Name:       "zwp_tablet_manager_v2",
	MaxVersion: 2,
	New:        newTabletManagerFromProxyBase,
}

// GetTabletSeat: get the tablet seat
//
// Get the wp_tablet_seat object for the given seat. This object
// provides access to all graphics tablets in this seat.
//
// Parameters:
//   - seat: The wl_seat object to retrieve the tablets for
func (t *TabletManager) GetTabletSeat(seat *wlcore.Seat) (*TabletSeat, error) {
	id := t.Conn().NewID()
	x := newTabletSeatFromProxyBase(wlcore.NewProxyBase(id, t.Version(), t.Conn()))
	t.Conn().Register(x)

	e := wlcore.NewEncoder().ID(id).ID(seat.ID())
	if err := t.Conn().Send(t.ID(), opReqTabletManagerGetTabletSeat, e); err != nil {
		return nil, err
	}
	return x, nil
}

// Destroy: release the memory for the tablet manager object
//
// Destroy the wp_tablet_manager object. Objects created from this
// object are unaffected and should be destroyed separately.
func (t *TabletManager) Destroy() error {
	err := t.Conn().Send(t.ID(), opReqTabletManagerDestroy, wlcore.NewEncoder())
	t.Conn().Destroy(t)
	return err
}

// Dispatch decodes one zwp_tablet_manager_v2 event and calls the matching
// field of the listener. The connection calls it while pumping messages; it
// is exported only because the runtime's Proxy interface requires it.
func (t *TabletManager) Dispatch(opcode uint16, dec *wlcore.Decoder) error {
	switch opcode {
	default:
		return fmt.Errorf("tablet: unknown opcode %d in zwp_tablet_manager_v2", opcode)
	}
}

const (
	opReqTabletManagerGetTabletSeat = 0
	opReqTabletManagerDestroy       = 1
)
