// Code generated by waygenerator. DO NOT EDIT.

package tablet

import (
	"fmt"

	"github.com/romycode/ggui/wayland/wlcore"
)

// TabletPadGroup: a set of buttons, rings and strips
//
// A pad group describes a distinct (sub)set of buttons, rings and strips
// present in the tablet. The criteria of this grouping is usually positional,
// eg. if a tablet has buttons on the left and right side, 2 groups will be
// presented. The physical arrangement of groups is undisclosed and may
// change on the fly.
//
// Pad groups will announce their features during pad initialization. Between
// the corresponding wp_tablet_pad.group event and wp_tablet_pad_group.done, the
// pad group will announce the buttons, rings and strips contained in it,
// plus the number of supported modes.
//
// Modes are a mechanism to allow multiple groups of actions for every element
// in the pad group. The number of groups and available modes in each is
// persistent across device plugs. The current mode is user-switchable, it
// will be announced through the wp_tablet_pad_group.mode_switch event both
// whenever it is switched, and after wp_tablet_pad.enter.
//
// The current mode logically applies to all elements in the pad group,
// although it is at clients' discretion whether to actually perform different
// actions, and/or issue the respective .set_feedback requests to notify the
// compositor. See the wp_tablet_pad_group.mode_switch event for more details.
type TabletPadGroup struct {
	wlcore.ProxyBase
	listener TabletPadGroupListener
}

var _ wlcore.Proxy = (*TabletPadGroup)(nil)

func newTabletPadGroup(id, version uint32, conn *wlcore.Conn) *TabletPadGroup {
	return newTabletPadGroupFromProxyBase(wlcore.NewProxyBase(id, version, conn))
}

func newTabletPadGroupFromProxyBase(base wlcore.ProxyBase) *TabletPadGroup {
	t := &TabletPadGroup{ProxyBase: base}
	t.OnClear = func() { t.listener = TabletPadGroupListener{} }
	return t
}

func (t *TabletPadGroup) SetListener(l TabletPadGroupListener) { t.listener = l }

type TabletPadGroupListener struct {
	// Buttons: buttons announced
	//
	// Sent on wp_tablet_pad_group initialization to announce the available
	// buttons in the group. Button indices start at 0, a button may only be
	// in one group at a time.
	//
	// This event is first sent in the initial burst of events before the
	// wp_tablet_pad_group.done event.
	//
	// Some buttons are reserved by the compositor. These buttons may not be
	// assigned to any wp_tablet_pad_group. Compositors may broadcast this
	// event in the case of changes to the mapping of these reserved buttons.
	// If the compositor happens to reserve all buttons in a group, this event
	// will be sent with an empty array.
	//
	// Parameters:
	//   - buttons: buttons in this group
	Buttons func(buttons []byte)
	// Ring: ring announced
	//
	// Sent on wp_tablet_pad_group initialization to announce available rings.
	// One event is sent for each ring available on this pad group.
	//
	// This event is sent in the initial burst of events before the
	// wp_tablet_pad_group.done event.
	Ring func(ring *TabletPadRing)
	// Strip: strip announced
	//
	// Sent on wp_tablet_pad initialization to announce available strips.
	// One event is sent for each strip available on this pad group.
	//
	// This event is sent in the initial burst of events before the
	// wp_tablet_pad_group.done event.
	Strip func(strip *TabletPadStrip)
	// Modes: mode-switch ability announced
	//
	// Sent on wp_tablet_pad_group initialization to announce that the pad
	// group may switch between modes. A client may use a mode to store a
	// specific configuration for buttons, rings and strips and use the
	// wl_tablet_pad_group.mode_switch event to toggle between these
	// configurations. Mode indices start at 0.
	//
	// Switching modes is compositor-dependent. See the
	// wp_tablet_pad_group.mode_switch event for more details.
	//
	// This event is sent in the initial burst of events before the
	// wp_tablet_pad_group.done event. This event is only sent when more than
	// more than one mode is available.
	//
	// Parameters:
	//   - modes: the number of modes
	Modes func(modes uint32)
	// Done: tablet group description events sequence complete
	//
	// This event is sent immediately to signal the end of the initial
	// burst of descriptive events. A client may consider the static
	// description of the tablet to be complete and finalize initialization
	// of the tablet group.
	Done func()
	// ModeSwitch: mode switch event
	//
	// Notification that the mode was switched.
	//
	// A mode applies to all buttons, rings, strips and dials in a group
	// simultaneously, but a client is not required to assign different actions
	// for each mode. For example, a client may have mode-specific button
	// mappings but map the ring to vertical scrolling in all modes. Mode
	// indices start at 0.
	//
	// Switching modes is compositor-dependent. The compositor may provide
	// visual cues to the user about the mode, e.g. by toggling LEDs on
	// the tablet device. Mode-switching may be software-controlled or
	// controlled by one or more physical buttons. For example, on a Wacom
	// Intuos Pro, the button inside the ring may be assigned to switch
	// between modes.
	//
	// The compositor will also send this event after wp_tablet_pad.enter on
	// each group in order to notify of the current mode. Groups that only
	// feature one mode will use mode=0 when emitting this event.
	//
	// If a button action in the new mode differs from the action in the
	// previous mode, the client should immediately issue a
	// wp_tablet_pad.set_feedback request for each changed button.
	//
	// If a ring, strip or dial action in the new mode differs from the action
	// in the previous mode, the client should immediately issue a
	// wp_tablet_ring.set_feedback, wp_tablet_strip.set_feedback or
	// wp_tablet_dial.set_feedback request for each changed ring, strip or dial.
	//
	// Parameters:
	//   - time: the time of the event with millisecond granularity
	//   - mode: the new mode of the pad
	ModeSwitch func(time uint32, serial uint32, mode uint32)
	// Dial: dial announced
	//
	// Sent on wp_tablet_pad initialization to announce available dials.
	// One event is sent for each dial available on this pad group.
	//
	// This event is sent in the initial burst of events before the
	// wp_tablet_pad_group.done event.
	Dial func(dial *TabletPadDial)
}

var TabletPadGroupInterface = wlcore.Interface[*TabletPadGroup]{
	Name:       "zwp_tablet_pad_group_v2",
	MaxVersion: 2,
	New:        newTabletPadGroupFromProxyBase,
}

// Destroy: destroy the pad object
//
// Destroy the wp_tablet_pad_group object. Objects created from this object
// are unaffected and should be destroyed separately.
func (t *TabletPadGroup) Destroy() error {
	err := t.Conn().Send(t.ID(), opReqTabletPadGroupDestroy, wlcore.NewEncoder())
	t.Conn().Destroy(t)
	return err
}

func (t *TabletPadGroup) Dispatch(opcode uint16, dec *wlcore.Decoder) error {
	switch opcode {
	case opEvtTabletPadGroupButtons:
		buttons := dec.Array()
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Buttons != nil {
			t.listener.Buttons(buttons)
		}
	case opEvtTabletPadGroupRing:
		ringID := dec.ID()
		if err := dec.Err(); err != nil {
			return err
		}
		ring := newTabletPadRingFromProxyBase(wlcore.NewProxyBase(ringID, t.Version(), t.Conn()))
		t.Conn().Register(ring)
		if t.listener.Ring != nil {
			t.listener.Ring(ring)
		}
	case opEvtTabletPadGroupStrip:
		stripID := dec.ID()
		if err := dec.Err(); err != nil {
			return err
		}
		strip := newTabletPadStripFromProxyBase(wlcore.NewProxyBase(stripID, t.Version(), t.Conn()))
		t.Conn().Register(strip)
		if t.listener.Strip != nil {
			t.listener.Strip(strip)
		}
	case opEvtTabletPadGroupModes:
		modes := dec.Uint32()
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Modes != nil {
			t.listener.Modes(modes)
		}
	case opEvtTabletPadGroupDone:
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Done != nil {
			t.listener.Done()
		}
	case opEvtTabletPadGroupModeSwitch:
		time := dec.Uint32()
		serial := dec.Uint32()
		mode := dec.Uint32()
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.ModeSwitch != nil {
			t.listener.ModeSwitch(time, serial, mode)
		}
	case opEvtTabletPadGroupDial:
		dialID := dec.ID()
		if err := dec.Err(); err != nil {
			return err
		}
		dial := newTabletPadDialFromProxyBase(wlcore.NewProxyBase(dialID, t.Version(), t.Conn()))
		t.Conn().Register(dial)
		if t.listener.Dial != nil {
			t.listener.Dial(dial)
		}
	default:
		return fmt.Errorf("tablet: unknown opcode %d in zwp_tablet_pad_group_v2", opcode)
	}
	return nil
}

const (
	opReqTabletPadGroupDestroy    = 0
	opEvtTabletPadGroupButtons    = 0
	opEvtTabletPadGroupRing       = 1
	opEvtTabletPadGroupStrip      = 2
	opEvtTabletPadGroupModes      = 3
	opEvtTabletPadGroupDone       = 4
	opEvtTabletPadGroupModeSwitch = 5
	opEvtTabletPadGroupDial       = 6
)
