// Code generated by waygenerator. DO NOT EDIT.

package tablet

import (
	"fmt"

	"github.com/romycode/ggui/wayland/wlcore"
)

// TabletPadDial: pad dial
//
// A rotary control, e.g. a dial or a wheel.
//
// Events on a dial are logically grouped by the wl_tablet_pad_dial.frame
// event.
type TabletPadDial struct {
	wlcore.ProxyBase
	listener TabletPadDialListener
}

var _ wlcore.Proxy = (*TabletPadDial)(nil)

func newTabletPadDial(id, version uint32, conn *wlcore.Conn) *TabletPadDial {
	return newTabletPadDialFromProxyBase(wlcore.NewProxyBase(id, version, conn))
}

func newTabletPadDialFromProxyBase(base wlcore.ProxyBase) *TabletPadDial {
	t := &TabletPadDial{ProxyBase: base}
	t.OnClear = func() { t.listener = TabletPadDialListener{} }
	return t
}

func (t *TabletPadDial) SetListener(l TabletPadDialListener) { t.listener = l }

type TabletPadDialListener struct {
	// Delta: delta movement
	//
	// Sent whenever the position on a dial changes.
	//
	// This event carries the wheel delta as multiples or fractions
	// of 120 with each multiple of 120 representing one logical wheel detent.
	// For example, an axis_value120 of 30 is one quarter of
	// a logical wheel step in the positive direction, a value120 of
	// -240 are two logical wheel steps in the negative direction within the
	// same hardware event. See the wl_pointer.axis_value120 for more details.
	//
	// The value120 must not be zero.
	//
	// Parameters:
	//   - value120: rotation distance as fraction of 120
	Delta func(value120 int32)
	// Frame: end of a dial event sequence
	//
	// Indicates the end of a set of events that represent one logical
	// hardware dial event. A client is expected to accumulate the data
	// in all events within the frame before proceeding.
	//
	// All wp_tablet_pad_dial events before a wp_tablet_pad_dial.frame event belong
	// logically together.
	//
	// A wp_tablet_pad_dial.frame event is sent for every logical event
	// group, even if the group only contains a single wp_tablet_pad_dial
	// event. Specifically, a client may get a sequence: delta, frame,
	// delta, frame, etc.
	//
	// Parameters:
	//   - time: timestamp with millisecond granularity
	Frame func(time uint32)
}

var TabletPadDialInterface = wlcore.Interface[*TabletPadDial]{
	Name:       "zwp_tablet_pad_dial_v2",
	MaxVersion: 2,
	New:        newTabletPadDialFromProxyBase,
}

// SetFeedback: set compositor feedback
//
// Requests the compositor to use the provided feedback string
// associated with this dial. This request should be issued immediately
// after a wp_tablet_pad_group.mode_switch event from the corresponding
// group is received, or whenever the dial is mapped to a different
// action. See wp_tablet_pad_group.mode_switch for more details.
//
// Clients are encouraged to provide context-aware descriptions for
// the actions associated with the dial, and compositors may use this
// information to offer visual feedback about the button layout
// (eg. on-screen displays).
//
// The provided string 'description' is a UTF-8 encoded string to be
// associated with this ring, and is considered user-visible; general
// internationalization rules apply.
//
// The serial argument will be that of the last
// wp_tablet_pad_group.mode_switch event received for the group of this
// dial. Requests providing other serials than the most recent one will be
// ignored.
//
// Parameters:
//   - description: dial description
//   - serial: serial of the mode switch event
func (t *TabletPadDial) SetFeedback(description string, serial uint32) error {
	e := wlcore.NewEncoder().String(description).Uint32(serial)
	return t.Conn().Send(t.ID(), opReqTabletPadDialSetFeedback, e)
}

// Destroy: destroy the dial object
//
// This destroys the client's resource for this dial object.
func (t *TabletPadDial) Destroy() error {
	err := t.Conn().Send(t.ID(), opReqTabletPadDialDestroy, wlcore.NewEncoder())
	t.Conn().Destroy(t)
	return err
}

func (t *TabletPadDial) Dispatch(opcode uint16, dec *wlcore.Decoder) error {
	switch opcode {
	case opEvtTabletPadDialDelta:
		value120 := dec.Int32()
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Delta != nil {
			t.listener.Delta(value120)
		}
	case opEvtTabletPadDialFrame:
		time := dec.Uint32()
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Frame != nil {
			t.listener.Frame(time)
		}
	default:
		return fmt.Errorf("tablet: unknown opcode %d in zwp_tablet_pad_dial_v2", opcode)
	}
	return nil
}

const (
	opReqTabletPadDialSetFeedback = 0
	opReqTabletPadDialDestroy     = 1
	opEvtTabletPadDialDelta       = 0
	opEvtTabletPadDialFrame       = 1
)
