// Code generated by waygenerator. DO NOT EDIT.

package tablet

import (
	"fmt"

	"github.com/romycode/ggui/wayland/wlcore"
)

// TabletPadRing: pad ring
//
// A circular interaction area, such as the touch ring on the Wacom Intuos
// Pro series tablets.
//
// Events on a ring are logically grouped by the wl_tablet_pad_ring.frame
// event.
type TabletPadRing struct {
	wlcore.ProxyBase
	listener TabletPadRingListener
}

var _ wlcore.Proxy = (*TabletPadRing)(nil)

func newTabletPadRing(id, version uint32, conn *wlcore.Conn) *TabletPadRing {
	return newTabletPadRingFromProxyBase(wlcore.NewProxyBase(id, version, conn))
}

func newTabletPadRingFromProxyBase(base wlcore.ProxyBase) *TabletPadRing {
	t := &TabletPadRing{ProxyBase: base}
	t.OnClear = func() { t.listener = TabletPadRingListener{} }
	return t
}

// SetListener installs the handlers for zwp_tablet_pad_ring_v2's events,
// replacing any already installed. A nil field ignores that event; a file
// descriptor arriving in an ignored event is closed, not leaked.
func (t *TabletPadRing) SetListener(l TabletPadRingListener) { t.listener = l }

// TabletPadRingListener holds the handlers for zwp_tablet_pad_ring_v2's
// events. Its zero value ignores every event. See
// [TabletPadRing.SetListener].
type TabletPadRingListener struct {
	// Source: ring event source
	//
	// Source information for ring events.
	//
	// This event does not occur on its own. It is sent before a
	// wp_tablet_pad_ring.frame event and carries the source information
	// for all events within that frame.
	//
	// The source specifies how this event was generated. If the source is
	// wp_tablet_pad_ring.source.finger, a wp_tablet_pad_ring.stop event
	// will be sent when the user lifts the finger off the device.
	//
	// This event is optional. If the source is unknown for an interaction,
	// no event is sent.
	//
	// Parameters:
	//   - source: the event source
	Source func(source TabletPadRingSource)
	// Angle: angle changed
	//
	// Sent whenever the angle on a ring changes.
	//
	// The angle is provided in degrees clockwise from the logical
	// north of the ring in the pad's current rotation.
	//
	// Parameters:
	//   - degrees: the current angle in degrees
	Angle func(degrees wlcore.Fixed)
	// Stop: interaction stopped
	//
	// Stop notification for ring events.
	//
	// For some wp_tablet_pad_ring.source types, a wp_tablet_pad_ring.stop
	// event is sent to notify a client that the interaction with the ring
	// has terminated. This enables the client to implement kinetic scrolling.
	// See the wp_tablet_pad_ring.source documentation for information on
	// when this event may be generated.
	//
	// Any wp_tablet_pad_ring.angle events with the same source after this
	// event should be considered as the start of a new interaction.
	Stop func()
	// Frame: end of a ring event sequence
	//
	// Indicates the end of a set of ring events that logically belong
	// together. A client is expected to accumulate the data in all events
	// within the frame before proceeding.
	//
	// All wp_tablet_pad_ring events before a wp_tablet_pad_ring.frame event belong
	// logically together. For example, on termination of a finger interaction
	// on a ring the compositor will send a wp_tablet_pad_ring.source event,
	// a wp_tablet_pad_ring.stop event and a wp_tablet_pad_ring.frame event.
	//
	// A wp_tablet_pad_ring.frame event is sent for every logical event
	// group, even if the group only contains a single wp_tablet_pad_ring
	// event. Specifically, a client may get a sequence: angle, frame,
	// angle, frame, etc.
	//
	// Parameters:
	//   - time: timestamp with millisecond granularity
	Frame func(time uint32)
}

// TabletPadRingInterface describes zwp_tablet_pad_ring_v2 for
// [wlcore.Registry.Bind]: the name it carries on the wire and version 2,
// the highest this binding implements. Bind negotiates that against the
// version the compositor advertises, so a call site never repeats either
// value.
var TabletPadRingInterface = wlcore.Interface[*TabletPadRing]{
	Name:       "zwp_tablet_pad_ring_v2",
	MaxVersion: 2,
	New:        newTabletPadRingFromProxyBase,
}

// SetFeedback: set compositor feedback
//
// Request that the compositor use the provided feedback string
// associated with this ring. This request should be issued immediately
// after a wp_tablet_pad_group.mode_switch event from the corresponding
// group is received, or whenever the ring is mapped to a different
// action. See wp_tablet_pad_group.mode_switch for more details.
//
// Clients are encouraged to provide context-aware descriptions for
// the actions associated with the ring; compositors may use this
// information to offer visual feedback about the button layout
// (eg. on-screen displays).
//
// The provided string 'description' is a UTF-8 encoded string to be
// associated with this ring, and is considered user-visible; general
// internationalization rules apply.
//
// The serial argument will be that of the last
// wp_tablet_pad_group.mode_switch event received for the group of this
// ring. Requests providing other serials than the most recent one will be
// ignored.
//
// Parameters:
//   - description: ring description
//   - serial: serial of the mode switch event
func (t *TabletPadRing) SetFeedback(description string, serial uint32) error {
	e := wlcore.NewEncoder().String(description).Uint32(serial)
	return t.Conn().Send(t.ID(), opReqTabletPadRingSetFeedback, e)
}

// Destroy: destroy the ring object
//
// This destroys the client's resource for this ring object.
func (t *TabletPadRing) Destroy() error {
	err := t.Conn().Send(t.ID(), opReqTabletPadRingDestroy, wlcore.NewEncoder())
	t.Conn().Destroy(t)
	return err
}

// Dispatch decodes one zwp_tablet_pad_ring_v2 event and calls the matching
// field of the listener. The connection calls it while pumping messages; it
// is exported only because the runtime's Proxy interface requires it.
func (t *TabletPadRing) Dispatch(opcode uint16, dec *wlcore.Decoder) error {
	switch opcode {
	case opEvtTabletPadRingSource:
		source := TabletPadRingSource(dec.Uint32())
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Source != nil {
			t.listener.Source(source)
		}
	case opEvtTabletPadRingAngle:
		degrees := dec.Fixed()
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Angle != nil {
			t.listener.Angle(degrees)
		}
	case opEvtTabletPadRingStop:
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Stop != nil {
			t.listener.Stop()
		}
	case opEvtTabletPadRingFrame:
		time := dec.Uint32()
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Frame != nil {
			t.listener.Frame(time)
		}
	default:
		return fmt.Errorf("tablet: unknown opcode %d in zwp_tablet_pad_ring_v2", opcode)
	}
	return nil
}

// TabletPadRingSource: ring axis source
//
// Describes the source types for ring events. This indicates to the
// client how a ring event was physically generated; a client may
// adjust the user interface accordingly. For example, events
// from a "finger" source may trigger kinetic scrolling.
type TabletPadRingSource uint32

const (
	TabletPadRingSourceFinger TabletPadRingSource = 1 // finger
)

const (
	opReqTabletPadRingSetFeedback = 0
	opReqTabletPadRingDestroy     = 1
	opEvtTabletPadRingSource      = 0
	opEvtTabletPadRingAngle       = 1
	opEvtTabletPadRingStop        = 2
	opEvtTabletPadRingFrame       = 3
)
