// Code generated by waygenerator. DO NOT EDIT.

package tablet

import (
	"fmt"

	"github.com/romycode/ggui/wayland/wlcore"
)

// TabletSeat: controller object for graphic tablet devices of a seat
//
// An object that provides access to the graphics tablets available on this
// seat. After binding to this interface, the compositor sends a set of
// wp_tablet_seat.tablet_added and wp_tablet_seat.tool_added events.
type TabletSeat struct {
	wlcore.ProxyBase
	listener TabletSeatListener
}

var _ wlcore.Proxy = (*TabletSeat)(nil)

func newTabletSeat(id, version uint32, conn *wlcore.Conn) *TabletSeat {
	return newTabletSeatFromProxyBase(wlcore.NewProxyBase(id, version, conn))
}

func newTabletSeatFromProxyBase(base wlcore.ProxyBase) *TabletSeat {
	t := &TabletSeat{ProxyBase: base}
	t.OnClear = func() { t.listener = TabletSeatListener{} }
	return t
}

func (t *TabletSeat) SetListener(l TabletSeatListener) { t.listener = l }

type TabletSeatListener struct {
	// TabletAdded: new device notification
	//
	// This event is sent whenever a new tablet becomes available on this
	// seat. This event only provides the object id of the tablet, any
	// static information about the tablet (device name, vid/pid, etc.) is
	// sent through the wp_tablet interface.
	//
	// Parameters:
	//   - id: the newly added graphics tablet
	TabletAdded func(id *Tablet)
	// ToolAdded: a new tool has been used with a tablet
	//
	// This event is sent whenever a tool that has not previously been used
	// with a tablet comes into use. This event only provides the object id
	// of the tool; any static information about the tool (capabilities,
	// type, etc.) is sent through the wp_tablet_tool interface.
	//
	// Parameters:
	//   - id: the newly added tablet tool
	ToolAdded func(id *TabletTool)
	// PadAdded: new pad notification
	//
	// This event is sent whenever a new pad is known to the system. Typically,
	// pads are physically attached to tablets and a pad_added event is
	// sent immediately after the wp_tablet_seat.tablet_added.
	// However, some standalone pad devices logically attach to tablets at
	// runtime, and the client must wait for wp_tablet_pad.enter to know
	// the tablet a pad is attached to.
	//
	// This event only provides the object id of the pad. All further
	// features (buttons, strips, rings) are sent through the wp_tablet_pad
	// interface.
	//
	// Parameters:
	//   - id: the newly added pad
	PadAdded func(id *TabletPad)
}

var TabletSeatInterface = wlcore.Interface[*TabletSeat]{
	Name:       "zwp_tablet_seat_v2",
	MaxVersion: 2,
	New:        newTabletSeatFromProxyBase,
}

// Destroy: release the memory for the tablet seat object
//
// Destroy the wp_tablet_seat object. Objects created from this
// object are unaffected and should be destroyed separately.
func (t *TabletSeat) Destroy() error {
	err := t.Conn().Send(t.ID(), opReqTabletSeatDestroy, wlcore.NewEncoder())
	t.Conn().Destroy(t)
	return err
}

func (t *TabletSeat) Dispatch(opcode uint16, dec *wlcore.Decoder) error {
	switch opcode {
	case opEvtTabletSeatTabletAdded:
		idID := dec.ID()
		if err := dec.Err(); err != nil {
			return err
		}
		id := newTabletFromProxyBase(wlcore.NewProxyBase(idID, t.Version(), t.Conn()))
		t.Conn().Register(id)
		if t.listener.TabletAdded != nil {
			t.listener.TabletAdded(id)
		}
	case opEvtTabletSeatToolAdded:
		idID := dec.ID()
		if err := dec.Err(); err != nil {
			return err
		}
		id := newTabletToolFromProxyBase(wlcore.NewProxyBase(idID, t.Version(), t.Conn()))
		t.Conn().Register(id)
		if t.listener.ToolAdded != nil {
			t.listener.ToolAdded(id)
		}
	case opEvtTabletSeatPadAdded:
		idID := dec.ID()
		if err := dec.Err(); err != nil {
			return err
		}
		id := newTabletPadFromProxyBase(wlcore.NewProxyBase(idID, t.Version(), t.Conn()))
		t.Conn().Register(id)
		if t.listener.PadAdded != nil {
			t.listener.PadAdded(id)
		}
	default:
		return fmt.Errorf("tablet: unknown opcode %d in zwp_tablet_seat_v2", opcode)
	}
	return nil
}

const (
	opReqTabletSeatDestroy     = 0
	opEvtTabletSeatTabletAdded = 0
	opEvtTabletSeatToolAdded   = 1
	opEvtTabletSeatPadAdded    = 2
)
