// Code generated by waygenerator. DO NOT EDIT.

package tablet

import (
	"fmt"

	"github.com/romycode/ggui/wayland/wlcore"
)

// TabletTool: a physical tablet tool
//
// An object that represents a physical tool that has been, or is
// currently in use with a tablet in this seat. Each wp_tablet_tool
// object stays valid until the client destroys it; the compositor
// reuses the wp_tablet_tool object to indicate that the object's
// respective physical tool has come into proximity of a tablet again.
//
// A wp_tablet_tool object's relation to a physical tool depends on the
// tablet's ability to report serial numbers. If the tablet supports
// this capability, then the object represents a specific physical tool
// and can be identified even when used on multiple tablets.
//
// A tablet tool has a number of static characteristics, e.g. tool type,
// hardware_serial and capabilities. These capabilities are sent in an
// event sequence after the wp_tablet_seat.tool_added event before any
// actual events from this tool. This initial event sequence is
// terminated by a wp_tablet_tool.done event.
//
// Tablet tool events are grouped by wp_tablet_tool.frame events.
// Any events received before a wp_tablet_tool.frame event should be
// considered part of the same hardware state change.
type TabletTool struct {
	wlcore.ProxyBase
	listener TabletToolListener
}

var _ wlcore.Proxy = (*TabletTool)(nil)

func newTabletTool(id, version uint32, conn *wlcore.Conn) *TabletTool {
	return newTabletToolFromProxyBase(wlcore.NewProxyBase(id, version, conn))
}

func newTabletToolFromProxyBase(base wlcore.ProxyBase) *TabletTool {
	t := &TabletTool{ProxyBase: base}
	t.OnClear = func() { t.listener = TabletToolListener{} }
	return t
}

// SetListener installs the handlers for zwp_tablet_tool_v2's events,
// replacing any already installed. A nil field ignores that event; a file
// descriptor arriving in an ignored event is closed, not leaked.
func (t *TabletTool) SetListener(l TabletToolListener) { t.listener = l }

// TabletToolListener holds the handlers for zwp_tablet_tool_v2's events.
// Its zero value ignores every event. See [TabletTool.SetListener].
type TabletToolListener struct {
	// Type: tool type
	//
	// The tool type is the high-level type of the tool and usually decides
	// the interaction expected from this tool.
	//
	// This event is sent in the initial burst of events before the
	// wp_tablet_tool.done event.
	//
	// Parameters:
	//   - toolType: the physical tool type
	Type func(toolType TabletToolType)
	// HardwareSerial: unique hardware serial number of the tool
	//
	// If the physical tool can be identified by a unique 64-bit serial
	// number, this event notifies the client of this serial number.
	//
	// If multiple tablets are available in the same seat and the tool is
	// uniquely identifiable by the serial number, that tool may move
	// between tablets.
	//
	// Otherwise, if the tool has no serial number and this event is
	// missing, the tool is tied to the tablet it first comes into
	// proximity with. Even if the physical tool is used on multiple
	// tablets, separate wp_tablet_tool objects will be created, one per
	// tablet.
	//
	// This event is sent in the initial burst of events before the
	// wp_tablet_tool.done event.
	//
	// Parameters:
	//   - hardwareSerialHi: the unique serial number of the tool, most significant bits
	//   - hardwareSerialLo: the unique serial number of the tool, least significant bits
	HardwareSerial func(hardwareSerialHi uint32, hardwareSerialLo uint32)
	// HardwareIDWacom: hardware id notification in Wacom's format
	//
	// This event notifies the client of a hardware id available on this tool.
	//
	// The hardware id is a device-specific 64-bit id that provides extra
	// information about the tool in use, beyond the wl_tool.type
	// enumeration. The format of the id is specific to tablets made by
	// Wacom Inc. For example, the hardware id of a Wacom Grip
	// Pen (a stylus) is 0x802.
	//
	// This event is sent in the initial burst of events before the
	// wp_tablet_tool.done event.
	//
	// Parameters:
	//   - hardwareIDHi: the hardware id, most significant bits
	//   - hardwareIDLo: the hardware id, least significant bits
	HardwareIDWacom func(hardwareIDHi uint32, hardwareIDLo uint32)
	// Capability: tool capability notification
	//
	// This event notifies the client of any capabilities of this tool,
	// beyond the main set of x/y axes and tip up/down detection.
	//
	// One event is sent for each extra capability available on this tool.
	//
	// This event is sent in the initial burst of events before the
	// wp_tablet_tool.done event.
	//
	// Parameters:
	//   - capability: the capability
	Capability func(capability TabletToolCapability)
	// Done: tool description events sequence complete
	//
	// This event signals the end of the initial burst of descriptive
	// events. A client may consider the static description of the tool to
	// be complete and finalize initialization of the tool.
	Done func()
	// Removed: tool removed
	//
	// This event is sent when the tool is removed from the system and will
	// send no further events. Should the physical tool come back into
	// proximity later, a new wp_tablet_tool object will be created.
	//
	// It is compositor-dependent when a tool is removed. A compositor may
	// remove a tool on proximity out, tablet removal or any other reason.
	// A compositor may also keep a tool alive until shutdown.
	//
	// If the tool is currently in proximity, a proximity_out event will be
	// sent before the removed event. See wp_tablet_tool.proximity_out for
	// the handling of any buttons logically down.
	//
	// When this event is received, the client must wp_tablet_tool.destroy
	// the object.
	Removed func()
	// ProximityIn: proximity in event
	//
	// Notification that this tool is focused on a certain surface.
	//
	// This event can be received when the tool has moved from one surface to
	// another, or when the tool has come back into proximity above the
	// surface.
	//
	// If any button is logically down when the tool comes into proximity,
	// the respective button event is sent after the proximity_in event but
	// within the same frame as the proximity_in event.
	//
	// Parameters:
	//   - tablet: The tablet the tool is in proximity of
	//   - surface: The current surface the tablet tool is over
	ProximityIn func(serial uint32, tablet *Tablet, surface *wlcore.Surface)
	// ProximityOut: proximity out event
	//
	// Notification that this tool has either left proximity, or is no
	// longer focused on a certain surface.
	//
	// When the tablet tool leaves proximity of the tablet, button release
	// events are sent for each button that was held down at the time of
	// leaving proximity. These events are sent before the proximity_out
	// event but within the same wp_tablet.frame.
	//
	// If the tool stays within proximity of the tablet, but the focus
	// changes from one surface to another, a button release event may not
	// be sent until the button is actually released or the tool leaves the
	// proximity of the tablet.
	ProximityOut func()
	// Down: tablet tool is making contact
	//
	// Sent whenever the tablet tool comes in contact with the surface of the
	// tablet.
	//
	// If the tool is already in contact with the tablet when entering the
	// input region, the client owning said region will receive a
	// wp_tablet.proximity_in event, followed by a wp_tablet.down
	// event and a wp_tablet.frame event.
	//
	// Note that this event describes logical contact, not physical
	// contact. On some devices, a compositor may not consider a tool in
	// logical contact until a minimum physical pressure threshold is
	// exceeded.
	Down func(serial uint32)
	// Up: tablet tool is no longer making contact
	//
	// Sent whenever the tablet tool stops making contact with the surface of
	// the tablet, or when the tablet tool moves out of the input region
	// and the compositor grab (if any) is dismissed.
	//
	// If the tablet tool moves out of the input region while in contact
	// with the surface of the tablet and the compositor does not have an
	// ongoing grab on the surface, the client owning said region will
	// receive a wp_tablet.up event, followed by a wp_tablet.proximity_out
	// event and a wp_tablet.frame event. If the compositor has an ongoing
	// grab on this device, this event sequence is sent whenever the grab
	// is dismissed in the future.
	//
	// Note that this event describes logical contact, not physical
	// contact. On some devices, a compositor may not consider a tool out
	// of logical contact until physical pressure falls below a specific
	// threshold.
	Up func()
	// Motion: motion event
	//
	// Sent whenever a tablet tool moves.
	//
	// Parameters:
	//   - x: surface-local x coordinate
	//   - y: surface-local y coordinate
	Motion func(x wlcore.Fixed, y wlcore.Fixed)
	// Pressure: pressure change event
	//
	// Sent whenever the pressure axis on a tool changes. The value of this
	// event is normalized to a value between 0 and 65535.
	//
	// Note that pressure may be nonzero even when a tool is not in logical
	// contact. See the down and up events for more details.
	//
	// Parameters:
	//   - pressure: The current pressure value
	Pressure func(pressure uint32)
	// Distance: distance change event
	//
	// Sent whenever the distance axis on a tool changes. The value of this
	// event is normalized to a value between 0 and 65535.
	//
	// Note that distance may be nonzero even when a tool is not in logical
	// contact. See the down and up events for more details.
	//
	// Parameters:
	//   - distance: The current distance value
	Distance func(distance uint32)
	// Tilt: tilt change event
	//
	// Sent whenever one or both of the tilt axes on a tool change. Each tilt
	// value is in degrees, relative to the z-axis of the tablet.
	// The angle is positive when the top of a tool tilts along the
	// positive x or y axis.
	//
	// Parameters:
	//   - tiltX: The current value of the X tilt axis
	//   - tiltY: The current value of the Y tilt axis
	Tilt func(tiltX wlcore.Fixed, tiltY wlcore.Fixed)
	// Rotation: z-rotation change event
	//
	// Sent whenever the z-rotation axis on the tool changes. The
	// rotation value is in degrees clockwise from the tool's
	// logical neutral position.
	//
	// Parameters:
	//   - degrees: The current rotation of the Z axis
	Rotation func(degrees wlcore.Fixed)
	// Slider: Slider position change event
	//
	// Sent whenever the slider position on the tool changes. The
	// value is normalized between -65535 and 65535, with 0 as the logical
	// neutral position of the slider.
	//
	// The slider is available on e.g. the Wacom Airbrush tool.
	//
	// Parameters:
	//   - position: The current position of slider
	Slider func(position int32)
	// Wheel: Wheel delta event
	//
	// Sent whenever the wheel on the tool emits an event. This event
	// contains two values for the same axis change. The degrees value is
	// in the same orientation as the wl_pointer.vertical_scroll axis. The
	// clicks value is in discrete logical clicks of the mouse wheel. This
	// value may be zero if the movement of the wheel was less
	// than one logical click.
	//
	// Clients should choose either value and avoid mixing degrees and
	// clicks. The compositor may accumulate values smaller than a logical
	// click and emulate click events when a certain threshold is met.
	// Thus, wl_tablet_tool.wheel events with non-zero clicks values may
	// have different degrees values.
	//
	// Parameters:
	//   - degrees: The wheel delta in degrees
	//   - clicks: The wheel delta in discrete clicks
	Wheel func(degrees wlcore.Fixed, clicks int32)
	// Button: button event
	//
	// Sent whenever a button on the tool is pressed or released.
	//
	// If a button is held down when the tool moves in or out of proximity,
	// button events are generated by the compositor. See
	// wp_tablet_tool.proximity_in and wp_tablet_tool.proximity_out for
	// details.
	//
	// Parameters:
	//   - button: The button whose state has changed
	//   - state: Whether the button was pressed or released
	Button func(serial uint32, button uint32, state TabletToolButtonState)
	// Frame: frame event
	//
	// Marks the end of a series of axis and/or button updates from the
	// tablet. The Wayland protocol requires axis updates to be sent
	// sequentially, however all events within a frame should be considered
	// one hardware event.
	//
	// Parameters:
	//   - time: The time of the event with millisecond granularity
	Frame func(time uint32)
}

// TabletToolInterface describes zwp_tablet_tool_v2 for
// [wlcore.Registry.Bind]: the name it carries on the wire and version 2,
// the highest this binding implements. Bind negotiates that against the
// version the compositor advertises, so a call site never repeats either
// value.
var TabletToolInterface = wlcore.Interface[*TabletTool]{
	Name:       "zwp_tablet_tool_v2",
	MaxVersion: 2,
	New:        newTabletToolFromProxyBase,
}

// SetCursor: set the tablet tool's surface
//
// Sets the surface of the cursor used for this tool on the given
// tablet. This request only takes effect if the tool is in proximity
// of one of the requesting client's surfaces or the surface parameter
// is the current pointer surface. If there was a previous surface set
// with this request it is replaced. If surface is NULL, the cursor
// image is hidden.
//
// The parameters hotspot_x and hotspot_y define the position of the
// pointer surface relative to the pointer location. Its top-left corner
// is always at (x, y) - (hotspot_x, hotspot_y), where (x, y) are the
// coordinates of the pointer location, in surface-local coordinates.
//
// On surface.attach requests to the pointer surface, hotspot_x and
// hotspot_y are decremented by the x and y parameters passed to the
// request. Attach must be confirmed by wl_surface.commit as usual.
//
// The hotspot can also be updated by passing the currently set pointer
// surface to this request with new values for hotspot_x and hotspot_y.
//
// The current and pending input regions of the wl_surface are cleared,
// and wl_surface.set_input_region is ignored until the wl_surface is no
// longer used as the cursor. When the use as a cursor ends, the current
// and pending input regions become undefined, and the wl_surface is
// unmapped.
//
// This request gives the surface the role of a wp_tablet_tool cursor. A
// surface may only ever be used as the cursor surface for one
// wp_tablet_tool. If the surface already has another role or has
// previously been used as cursor surface for a different tool, a
// protocol error is raised.
//
// Parameters:
//   - serial: serial of the proximity_in event
//   - hotspotX: surface-local x coordinate
//   - hotspotY: surface-local y coordinate
func (t *TabletTool) SetCursor(serial uint32, surface *wlcore.Surface, hotspotX int32, hotspotY int32) error {
	var surfaceID uint32
	if surface != nil {
		surfaceID = surface.ID()
	}
	e := wlcore.NewEncoder().Uint32(serial).ID(surfaceID).Int32(hotspotX).Int32(hotspotY)
	return t.Conn().Send(t.ID(), opReqTabletToolSetCursor, e)
}

// Destroy: destroy the tool object
//
// This destroys the client's resource for this tool object.
func (t *TabletTool) Destroy() error {
	err := t.Conn().Send(t.ID(), opReqTabletToolDestroy, wlcore.NewEncoder())
	t.Conn().Destroy(t)
	return err
}

// Dispatch decodes one zwp_tablet_tool_v2 event and calls the matching
// field of the listener. The connection calls it while pumping messages; it
// is exported only because the runtime's Proxy interface requires it.
func (t *TabletTool) Dispatch(opcode uint16, dec *wlcore.Decoder) error {
	switch opcode {
	case opEvtTabletToolType:
		toolType := TabletToolType(dec.Uint32())
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Type != nil {
			t.listener.Type(toolType)
		}
	case opEvtTabletToolHardwareSerial:
		hardwareSerialHi := dec.Uint32()
		hardwareSerialLo := dec.Uint32()
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.HardwareSerial != nil {
			t.listener.HardwareSerial(hardwareSerialHi, hardwareSerialLo)
		}
	case opEvtTabletToolHardwareIDWacom:
		hardwareIDHi := dec.Uint32()
		hardwareIDLo := dec.Uint32()
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.HardwareIDWacom != nil {
			t.listener.HardwareIDWacom(hardwareIDHi, hardwareIDLo)
		}
	case opEvtTabletToolCapability:
		capability := TabletToolCapability(dec.Uint32())
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Capability != nil {
			t.listener.Capability(capability)
		}
	case opEvtTabletToolDone:
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Done != nil {
			t.listener.Done()
		}
	case opEvtTabletToolRemoved:
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Removed != nil {
			t.listener.Removed()
		}
	case opEvtTabletToolProximityIn:
		serial := dec.Uint32()
		tabletID := dec.ID()
		surfaceID := dec.ID()
		if err := dec.Err(); err != nil {
			return err
		}
		tablet, _ := t.Conn().Lookup(tabletID).(*Tablet)
		surface, _ := t.Conn().Lookup(surfaceID).(*wlcore.Surface)
		if t.listener.ProximityIn != nil {
			t.listener.ProximityIn(serial, tablet, surface)
		}
	case opEvtTabletToolProximityOut:
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.ProximityOut != nil {
			t.listener.ProximityOut()
		}
	case opEvtTabletToolDown:
		serial := dec.Uint32()
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Down != nil {
			t.listener.Down(serial)
		}
	case opEvtTabletToolUp:
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Up != nil {
			t.listener.Up()
		}
	case opEvtTabletToolMotion:
		x := dec.Fixed()
		y := dec.Fixed()
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Motion != nil {
			t.listener.Motion(x, y)
		}
	case opEvtTabletToolPressure:
		pressure := dec.Uint32()
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Pressure != nil {
			t.listener.Pressure(pressure)
		}
	case opEvtTabletToolDistance:
		distance := dec.Uint32()
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Distance != nil {
			t.listener.Distance(distance)
		}
	case opEvtTabletToolTilt:
		tiltX := dec.Fixed()
		tiltY := dec.Fixed()
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Tilt != nil {
			t.listener.Tilt(tiltX, tiltY)
		}
	case opEvtTabletToolRotation:
		degrees := dec.Fixed()
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Rotation != nil {
			t.listener.Rotation(degrees)
		}
	case opEvtTabletToolSlider:
		position := dec.Int32()
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Slider != nil {
			t.listener.Slider(position)
		}
	case opEvtTabletToolWheel:
		degrees := dec.Fixed()
		clicks := dec.Int32()
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Wheel != nil {
			t.listener.Wheel(degrees, clicks)
		}
	case opEvtTabletToolButton:
		serial := dec.Uint32()
		button := dec.Uint32()
		state := TabletToolButtonState(dec.Uint32())
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Button != nil {
			t.listener.Button(serial, button, state)
		}
	case opEvtTabletToolFrame:
		time := dec.Uint32()
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Frame != nil {
			t.listener.Frame(time)
		}
	default:
		return fmt.Errorf("tablet: unknown opcode %d in zwp_tablet_tool_v2", opcode)
	}
	return nil
}

// TabletToolType: a physical tool type
//
// Describes the physical type of a tool. The physical type of a tool
// generally defines its base usage.
//
// The mouse tool represents a mouse-shaped tool that is not a relative
// device but bound to the tablet's surface, providing absolute
// coordinates.
//
// The lens tool is a mouse-shaped tool with an attached lens to
// provide precision focus.
type TabletToolType uint32

const (
	TabletToolTypePen      TabletToolType = 0x140 // Pen
	TabletToolTypeEraser   TabletToolType = 0x141 // Eraser
	TabletToolTypeBrush    TabletToolType = 0x142 // Brush
	TabletToolTypePencil   TabletToolType = 0x143 // Pencil
	TabletToolTypeAirbrush TabletToolType = 0x144 // Airbrush
	TabletToolTypeFinger   TabletToolType = 0x145 // Finger
	TabletToolTypeMouse    TabletToolType = 0x146 // Mouse
	TabletToolTypeLens     TabletToolType = 0x147 // Lens
)

// TabletToolCapability: capability flags for a tool
//
// Describes extra capabilities on a tablet.
//
// Any tool must provide x and y values, extra axes are
// device-specific.
type TabletToolCapability uint32

const (
	TabletToolCapabilityTilt     TabletToolCapability = 1 // Tilt axes
	TabletToolCapabilityPressure TabletToolCapability = 2 // Pressure axis
	TabletToolCapabilityDistance TabletToolCapability = 3 // Distance axis
	TabletToolCapabilityRotation TabletToolCapability = 4 // Z-rotation axis
	TabletToolCapabilitySlider   TabletToolCapability = 5 // Slider axis
	TabletToolCapabilityWheel    TabletToolCapability = 6 // Wheel axis
)

// TabletToolButtonState: physical button state
//
// Describes the physical state of a button that produced the button event.
type TabletToolButtonState uint32

const (
	TabletToolButtonStateReleased TabletToolButtonState = 0 // button is not pressed
	TabletToolButtonStatePressed  TabletToolButtonState = 1 // button is pressed
)

// TabletToolError enumerates the protocol errors zwp_tablet_tool_v2 can
// raise. The compositor reports one through wl_display.error.
type TabletToolError uint32

const (
	TabletToolErrorRole TabletToolError = 0 // given wl_surface has another role
)

const (
	opReqTabletToolSetCursor       = 0
	opReqTabletToolDestroy         = 1
	opEvtTabletToolType            = 0
	opEvtTabletToolHardwareSerial  = 1
	opEvtTabletToolHardwareIDWacom = 2
	opEvtTabletToolCapability      = 3
	opEvtTabletToolDone            = 4
	opEvtTabletToolRemoved         = 5
	opEvtTabletToolProximityIn     = 6
	opEvtTabletToolProximityOut    = 7
	opEvtTabletToolDown            = 8
	opEvtTabletToolUp              = 9
	opEvtTabletToolMotion          = 10
	opEvtTabletToolPressure        = 11
	opEvtTabletToolDistance        = 12
	opEvtTabletToolTilt            = 13
	opEvtTabletToolRotation        = 14
	opEvtTabletToolSlider          = 15
	opEvtTabletToolWheel           = 16
	opEvtTabletToolButton          = 17
	opEvtTabletToolFrame           = 18
)
