// Package xdgshell contains the bindings for the xdg-shell protocol: the
// desktop windows a Wayland client actually shows.
//
// Bind [WmBaseInterface] from the registry, wrap a wl_surface with
// [WmBase.GetXdgSurface], then give it a role with [Surface.GetToplevel]
// for a window or [Surface.GetPopup] for a menu or tooltip.
//
// The handshake is the part that catches people out: after the first
// commit the compositor answers with a configure event, and the surface
// stays invisible until the client acks it and only then attaches a buffer
// and commits again. A [Toplevel] configure also carries the size the
// compositor wants, which may be 0x0 meaning "pick your own".
//
// [WmBase] pings to check the client is alive. A pong must be sent back or
// the compositor is entitled to treat the window as hung.
//
// Generated by waygenerator from protocols/xdg-shell.xml. Do not edit the
// .gen.go files.
package xdgshell
