// Code generated by waygenerator. DO NOT EDIT.

package xdgshell

import (
	"fmt"

	"github.com/romycode/ggui/wayland/wlcore"
)

// Popup: short-lived, popup surfaces for menus
//
// A popup surface is a short-lived, temporary surface. It can be used to
// implement for example menus, popovers, tooltips and other similar user
// interface concepts.
//
// A popup can be made to take an explicit grab. See xdg_popup.grab for
// details.
//
// When the popup is dismissed, a popup_done event will be sent out, and at
// the same time the surface will be unmapped. See the xdg_popup.popup_done
// event for details.
//
// Explicitly destroying the xdg_popup object will also dismiss the popup and
// unmap the surface. Clients that want to dismiss the popup when another
// surface of their own is clicked should dismiss the popup using the destroy
// request.
//
// A newly created xdg_popup will be stacked on top of all previously created
// xdg_popup surfaces associated with the same xdg_toplevel.
//
// The parent of an xdg_popup must be mapped (see the xdg_surface
// description) before the xdg_popup itself.
//
// The client must call wl_surface.commit on the corresponding wl_surface
// for the xdg_popup state to take effect.
type Popup struct {
	wlcore.ProxyBase
	listener PopupListener
}

var _ wlcore.Proxy = (*Popup)(nil)

func newPopup(id, version uint32, conn *wlcore.Conn) *Popup {
	return newPopupFromProxyBase(wlcore.NewProxyBase(id, version, conn))
}

func newPopupFromProxyBase(base wlcore.ProxyBase) *Popup {
	p := &Popup{ProxyBase: base}
	p.OnClear = func() { p.listener = PopupListener{} }
	return p
}

func (p *Popup) SetListener(l PopupListener) { p.listener = l }

type PopupListener struct {
	// Configure: configure the popup surface
	//
	// This event asks the popup surface to configure itself given the
	// configuration. The configured state should not be applied immediately.
	// See xdg_surface.configure for details.
	//
	// The x and y arguments represent the position the popup was placed at
	// given the xdg_positioner rule, relative to the upper left corner of the
	// window geometry of the parent surface.
	//
	// For version 2 or older, the configure event for an xdg_popup is only
	// ever sent once for the initial configuration. Starting with version 3,
	// it may be sent again if the popup is setup with an xdg_positioner with
	// set_reactive requested, or in response to xdg_popup.reposition requests.
	//
	// Parameters:
	//   - x: x position relative to parent surface window geometry
	//   - y: y position relative to parent surface window geometry
	//   - width: window geometry width
	//   - height: window geometry height
	Configure func(x int32, y int32, width int32, height int32)
	// PopupDone: popup interaction is done
	//
	// The popup_done event is sent out when a popup is dismissed by the
	// compositor. The client should destroy the xdg_popup object at this
	// point.
	PopupDone func()
	// Repositioned: signal the completion of a repositioned request
	//
	// The repositioned event is sent as part of a popup configuration
	// sequence, together with xdg_popup.configure and lastly
	// xdg_surface.configure to notify the completion of a reposition request.
	//
	// The repositioned event is to notify about the completion of a
	// xdg_popup.reposition request. The token argument is the token passed
	// in the xdg_popup.reposition request.
	//
	// Immediately after this event is emitted, xdg_popup.configure and
	// xdg_surface.configure will be sent with the updated size and position,
	// as well as a new configure serial.
	//
	// The client should optionally update the content of the popup, but must
	// acknowledge the new popup configuration for the new position to take
	// effect. See xdg_surface.ack_configure for details.
	//
	// Parameters:
	//   - token: reposition request token
	Repositioned func(token uint32)
}

var PopupInterface = wlcore.Interface[*Popup]{
	Name:       "xdg_popup",
	MaxVersion: 7,
	New:        newPopupFromProxyBase,
}

// Destroy: remove xdg_popup interface
//
// This destroys the popup. Explicitly destroying the xdg_popup
// object will also dismiss the popup, and unmap the surface.
//
// If this xdg_popup is not the "topmost" popup, the
// xdg_wm_base.not_the_topmost_popup protocol error will be sent.
func (p *Popup) Destroy() error {
	err := p.Conn().Send(p.ID(), opReqPopupDestroy, wlcore.NewEncoder())
	p.Conn().Destroy(p)
	return err
}

// Grab: make the popup take an explicit grab
//
// This request makes the created popup take an explicit grab. An explicit
// grab will be dismissed when the user dismisses the popup, or when the
// client destroys the xdg_popup. This can be done by the user clicking
// outside the surface, using the keyboard, or even locking the screen
// through closing the lid or a timeout.
//
// If the compositor denies the grab, the popup will be immediately
// dismissed.
//
// This request must be used in response to some sort of user action like a
// button press, key press, or touch down event. The serial number of the
// event should be passed as 'serial'.
//
// The parent of a grabbing popup must either be an xdg_toplevel surface or
// another xdg_popup with an explicit grab. If the parent is another
// xdg_popup it means that the popups are nested, with this popup now being
// the topmost popup.
//
// Nested popups must be destroyed in the reverse order they were created
// in, e.g. the only popup you are allowed to destroy at all times is the
// topmost one.
//
// When compositors choose to dismiss a popup, they may dismiss every
// nested grabbing popup as well. When a compositor dismisses popups, it
// will follow the same dismissing order as required from the client.
//
// If the topmost grabbing popup is destroyed, the grab will be returned to
// the parent of the popup, if that parent previously had an explicit grab.
//
// If the parent is a grabbing popup which has already been dismissed, this
// popup will be immediately dismissed. If the parent is a popup that did
// not take an explicit grab, an error will be raised.
//
// During a popup grab, the client owning the grab will receive pointer
// and touch events for all their surfaces as normal (similar to an
// "owner-events" grab in X11 parlance), while the top most grabbing popup
// will always have keyboard focus.
//
// Parameters:
//   - seat: the wl_seat of the user event
//   - serial: the serial of the user event
func (p *Popup) Grab(seat *wlcore.Seat, serial uint32) error {
	e := wlcore.NewEncoder().ID(seat.ID()).Uint32(serial)
	return p.Conn().Send(p.ID(), opReqPopupGrab, e)
}

// Reposition: recalculate the popup's location
//
// Reposition an already-mapped popup. The popup will be placed given the
// details in the passed xdg_positioner object, and a
// xdg_popup.repositioned followed by xdg_popup.configure and
// xdg_surface.configure will be emitted in response. Any parameters set
// by the previous positioner will be discarded.
//
// The passed token will be sent in the corresponding
// xdg_popup.repositioned event. The new popup position will not take
// effect until the corresponding configure event is acknowledged by the
// client. See xdg_popup.repositioned for details. The token itself is
// opaque, and has no other special meaning.
//
// If multiple reposition requests are sent, the compositor may skip all
// but the last one.
//
// If the popup is repositioned in response to a configure event for its
// parent, the client should send an xdg_positioner.set_parent_configure
// and possibly an xdg_positioner.set_parent_size request to allow the
// compositor to properly constrain the popup.
//
// If the popup is repositioned together with a parent that is being
// resized, but not in response to a configure event, the client should
// send an xdg_positioner.set_parent_size request.
//
// Parameters:
//   - token: reposition request token
func (p *Popup) Reposition(positioner *Positioner, token uint32) error {
	if p.Version() < 3 {
		return fmt.Errorf("xdgshell: reposition requires version >= 3, got %d", p.Version())
	}
	e := wlcore.NewEncoder().ID(positioner.ID()).Uint32(token)
	return p.Conn().Send(p.ID(), opReqPopupReposition, e)
}

func (p *Popup) Dispatch(opcode uint16, dec *wlcore.Decoder) error {
	switch opcode {
	case opEvtPopupConfigure:
		x := dec.Int32()
		y := dec.Int32()
		width := dec.Int32()
		height := dec.Int32()
		if err := dec.Err(); err != nil {
			return err
		}
		if p.listener.Configure != nil {
			p.listener.Configure(x, y, width, height)
		}
	case opEvtPopupPopupDone:
		if err := dec.Err(); err != nil {
			return err
		}
		if p.listener.PopupDone != nil {
			p.listener.PopupDone()
		}
	case opEvtPopupRepositioned:
		token := dec.Uint32()
		if err := dec.Err(); err != nil {
			return err
		}
		if p.listener.Repositioned != nil {
			p.listener.Repositioned(token)
		}
	default:
		return fmt.Errorf("xdgshell: unknown opcode %d in xdg_popup", opcode)
	}
	return nil
}

type PopupError uint32

const (
	PopupErrorInvalidGrab PopupError = 0 // tried to grab after being mapped
)

const (
	opReqPopupDestroy      = 0
	opReqPopupGrab         = 1
	opReqPopupReposition   = 2
	opEvtPopupConfigure    = 0
	opEvtPopupPopupDone    = 1
	opEvtPopupRepositioned = 2
)
