// Code generated by waygenerator. DO NOT EDIT.

package xdgshell

import (
	"fmt"

	"github.com/romycode/ggui/wayland/wlcore"
)

// Positioner: child surface positioner
//
// The xdg_positioner provides a collection of rules for the placement of a
// child surface relative to a parent surface. Rules can be defined to ensure
// the child surface remains within the visible area's borders, and to
// specify how the child surface changes its position, such as sliding along
// an axis, or flipping around a rectangle. These positioner-created rules are
// constrained by the requirement that a child surface must intersect with or
// be at least partially adjacent to its parent surface.
//
// See the various requests for details about possible rules.
//
// At the time of the request, the compositor makes a copy of the rules
// specified by the xdg_positioner. Thus, after the request is complete the
// xdg_positioner object can be destroyed or reused; further changes to the
// object will have no effect on previous usages.
//
// For an xdg_positioner object to be considered complete, it must have a
// non-zero size set by set_size, and a non-zero anchor rectangle set by
// set_anchor_rect. Passing an incomplete xdg_positioner object when
// positioning a surface raises an invalid_positioner error.
type Positioner struct {
	wlcore.ProxyBase
	listener PositionerListener
}

var _ wlcore.Proxy = (*Positioner)(nil)

func newPositioner(id, version uint32, conn *wlcore.Conn) *Positioner {
	return newPositionerFromProxyBase(wlcore.NewProxyBase(id, version, conn))
}

func newPositionerFromProxyBase(base wlcore.ProxyBase) *Positioner {
	p := &Positioner{ProxyBase: base}
	return p
}

// SetListener installs the handlers for xdg_positioner's events, replacing
// any already installed. A nil field ignores that event; a file descriptor
// arriving in an ignored event is closed, not leaked.
func (p *Positioner) SetListener(l PositionerListener) { p.listener = l }

// PositionerListener holds the handlers for xdg_positioner's events. Its
// zero value ignores every event. See [Positioner.SetListener].
type PositionerListener struct {
}

// PositionerInterface describes xdg_positioner for [wlcore.Registry.Bind]:
// the name it carries on the wire and version 7, the highest this binding
// implements. Bind negotiates that against the version the compositor
// advertises, so a call site never repeats either value.
var PositionerInterface = wlcore.Interface[*Positioner]{
	Name:       "xdg_positioner",
	MaxVersion: 7,
	New:        newPositionerFromProxyBase,
}

// Destroy: destroy the xdg_positioner object
//
// Notify the compositor that the xdg_positioner will no longer be used.
func (p *Positioner) Destroy() error {
	err := p.Conn().Send(p.ID(), opReqPositionerDestroy, wlcore.NewEncoder())
	p.Conn().Destroy(p)
	return err
}

// SetSize: set the size of the to-be positioned rectangle
//
// Set the size of the surface that is to be positioned with the positioner
// object. The size is in surface-local coordinates and corresponds to the
// window geometry. See xdg_surface.set_window_geometry.
//
// If a zero or negative size is set the invalid_input error is raised.
//
// Parameters:
//   - width: width of positioned rectangle
//   - height: height of positioned rectangle
func (p *Positioner) SetSize(width int32, height int32) error {
	e := wlcore.NewEncoder().Int32(width).Int32(height)
	return p.Conn().Send(p.ID(), opReqPositionerSetSize, e)
}

// SetAnchorRect: set the anchor rectangle within the parent surface
//
// Specify the anchor rectangle within the parent surface that the child
// surface will be placed relative to. The rectangle is relative to the
// window geometry as defined by xdg_surface.set_window_geometry of the
// parent surface.
//
// When the xdg_positioner object is used to position a child surface, the
// anchor rectangle may not extend outside the window geometry of the
// positioned child's parent surface.
//
// If a negative size is set the invalid_input error is raised.
//
// Parameters:
//   - x: x position of anchor rectangle
//   - y: y position of anchor rectangle
//   - width: width of anchor rectangle
//   - height: height of anchor rectangle
func (p *Positioner) SetAnchorRect(x int32, y int32, width int32, height int32) error {
	e := wlcore.NewEncoder().Int32(x).Int32(y).Int32(width).Int32(height)
	return p.Conn().Send(p.ID(), opReqPositionerSetAnchorRect, e)
}

// SetAnchor: set anchor rectangle anchor
//
// Defines the anchor point for the anchor rectangle. The specified anchor
// is used derive an anchor point that the child surface will be
// positioned relative to. If a corner anchor is set (e.g. 'top_left' or
// 'bottom_right'), the anchor point will be at the specified corner;
// otherwise, the derived anchor point will be centered on the specified
// edge, or in the center of the anchor rectangle if no edge is specified.
//
// Parameters:
//   - anchor: anchor
func (p *Positioner) SetAnchor(anchor PositionerAnchor) error {
	e := wlcore.NewEncoder().Uint32(uint32(anchor))
	return p.Conn().Send(p.ID(), opReqPositionerSetAnchor, e)
}

// SetGravity: set child surface gravity
//
// Defines in what direction a surface should be positioned, relative to
// the anchor point of the parent surface. If a corner gravity is
// specified (e.g. 'bottom_right' or 'top_left'), then the child surface
// will be placed towards the specified gravity; otherwise, the child
// surface will be centered over the anchor point on any axis that had no
// gravity specified. If the gravity is not in the ‘gravity’ enum, an
// invalid_input error is raised.
//
// Parameters:
//   - gravity: gravity direction
func (p *Positioner) SetGravity(gravity PositionerGravity) error {
	e := wlcore.NewEncoder().Uint32(uint32(gravity))
	return p.Conn().Send(p.ID(), opReqPositionerSetGravity, e)
}

// SetConstraintAdjustment: set the adjustment to be done when constrained
//
// Specify how the window should be positioned if the originally intended
// position caused the surface to be constrained, meaning at least
// partially outside positioning boundaries set by the compositor. The
// adjustment is set by constructing a bitmask describing the adjustment to
// be made when the surface is constrained on that axis.
//
// If no bit for one axis is set, the compositor will assume that the child
// surface should not change its position on that axis when constrained.
//
// If more than one bit for one axis is set, the order of how adjustments
// are applied is specified in the corresponding adjustment descriptions.
//
// The default adjustment is none.
//
// Parameters:
//   - constraintAdjustment: bit mask of constraint adjustments
func (p *Positioner) SetConstraintAdjustment(constraintAdjustment PositionerConstraintAdjustment) error {
	e := wlcore.NewEncoder().Uint32(uint32(constraintAdjustment))
	return p.Conn().Send(p.ID(), opReqPositionerSetConstraintAdjustment, e)
}

// SetOffset: set surface position offset
//
// Specify the surface position offset relative to the position of the
// anchor on the anchor rectangle and the anchor on the surface. For
// example if the anchor of the anchor rectangle is at (x, y), the surface
// has the gravity bottom|right, and the offset is (ox, oy), the calculated
// surface position will be (x + ox, y + oy). The offset position of the
// surface is the one used for constraint testing. See
// set_constraint_adjustment.
//
// An example use case is placing a popup menu on top of a user interface
// element, while aligning the user interface element of the parent surface
// with some user interface element placed somewhere in the popup surface.
//
// Parameters:
//   - x: surface position x offset
//   - y: surface position y offset
func (p *Positioner) SetOffset(x int32, y int32) error {
	e := wlcore.NewEncoder().Int32(x).Int32(y)
	return p.Conn().Send(p.ID(), opReqPositionerSetOffset, e)
}

// SetReactive: continuously reconstrain the surface
//
// When set reactive, the surface is reconstrained if the conditions used
// for constraining changed, e.g. the parent window moved.
//
// If the conditions changed and the popup was reconstrained, an
// xdg_popup.configure event is sent with updated geometry, followed by an
// xdg_surface.configure event.
func (p *Positioner) SetReactive() error {
	if p.Version() < 3 {
		return fmt.Errorf("xdgshell: set_reactive requires version >= 3, got %d", p.Version())
	}
	e := wlcore.NewEncoder()
	return p.Conn().Send(p.ID(), opReqPositionerSetReactive, e)
}

// SetParentSize: Set the parent window geometry the compositor should use when
// positioning the popup. The compositor may use this information to
// determine the future state the popup should be constrained using. If
// this doesn't match the dimension of the parent the popup is eventually
// positioned against, the behavior is undefined.
//
// The arguments are given in the surface-local coordinate space.
//
// Parameters:
//   - parentWidth: future window geometry width of parent
//   - parentHeight: future window geometry height of parent
func (p *Positioner) SetParentSize(parentWidth int32, parentHeight int32) error {
	if p.Version() < 3 {
		return fmt.Errorf("xdgshell: set_parent_size requires version >= 3, got %d", p.Version())
	}
	e := wlcore.NewEncoder().Int32(parentWidth).Int32(parentHeight)
	return p.Conn().Send(p.ID(), opReqPositionerSetParentSize, e)
}

// SetParentConfigure: set parent configure this is a response to
//
// Set the serial of an xdg_surface.configure event this positioner will be
// used in response to. The compositor may use this information together
// with set_parent_size to determine what future state the popup should be
// constrained using.
//
// Parameters:
//   - serial: serial of parent configure event
func (p *Positioner) SetParentConfigure(serial uint32) error {
	if p.Version() < 3 {
		return fmt.Errorf("xdgshell: set_parent_configure requires version >= 3, got %d", p.Version())
	}
	e := wlcore.NewEncoder().Uint32(serial)
	return p.Conn().Send(p.ID(), opReqPositionerSetParentConfigure, e)
}

// Dispatch decodes one xdg_positioner event and calls the matching field of
// the listener. The connection calls it while pumping messages; it is
// exported only because the runtime's Proxy interface requires it.
func (p *Positioner) Dispatch(opcode uint16, dec *wlcore.Decoder) error {
	switch opcode {
	default:
		return fmt.Errorf("xdgshell: unknown opcode %d in xdg_positioner", opcode)
	}
}

// PositionerError enumerates the protocol errors xdg_positioner can raise.
// The compositor reports one through wl_display.error.
type PositionerError uint32

const (
	PositionerErrorInvalidInput PositionerError = 0 // invalid input provided
)

// PositionerAnchor is xdg_positioner's "anchor" enum.
type PositionerAnchor uint32

const (
	PositionerAnchorNone        PositionerAnchor = 0
	PositionerAnchorTop         PositionerAnchor = 1
	PositionerAnchorBottom      PositionerAnchor = 2
	PositionerAnchorLeft        PositionerAnchor = 3
	PositionerAnchorRight       PositionerAnchor = 4
	PositionerAnchorTopLeft     PositionerAnchor = 5
	PositionerAnchorBottomLeft  PositionerAnchor = 6
	PositionerAnchorTopRight    PositionerAnchor = 7
	PositionerAnchorBottomRight PositionerAnchor = 8
)

// PositionerGravity is xdg_positioner's "gravity" enum.
type PositionerGravity uint32

const (
	PositionerGravityNone        PositionerGravity = 0
	PositionerGravityTop         PositionerGravity = 1
	PositionerGravityBottom      PositionerGravity = 2
	PositionerGravityLeft        PositionerGravity = 3
	PositionerGravityRight       PositionerGravity = 4
	PositionerGravityTopLeft     PositionerGravity = 5
	PositionerGravityBottomLeft  PositionerGravity = 6
	PositionerGravityTopRight    PositionerGravity = 7
	PositionerGravityBottomRight PositionerGravity = 8
)

// PositionerConstraintAdjustment: constraint adjustments
//
// The constraint adjustment value define ways the compositor will adjust
// the position of the surface, if the unadjusted position would result
// in the surface being partly constrained.
//
// Whether a surface is considered 'constrained' is left to the compositor
// to determine. For example, the surface may be partly outside the
// compositor's defined 'work area', thus necessitating the child surface's
// position be adjusted until it is entirely inside the work area.
//
// The adjustments can be combined, according to a defined precedence: 1)
// Flip, 2) Slide, 3) Resize.
type PositionerConstraintAdjustment uint32

const (
	PositionerConstraintAdjustmentNone    PositionerConstraintAdjustment = 0
	PositionerConstraintAdjustmentSlideX  PositionerConstraintAdjustment = 1
	PositionerConstraintAdjustmentSlideY  PositionerConstraintAdjustment = 2
	PositionerConstraintAdjustmentFlipX   PositionerConstraintAdjustment = 4
	PositionerConstraintAdjustmentFlipY   PositionerConstraintAdjustment = 8
	PositionerConstraintAdjustmentResizeX PositionerConstraintAdjustment = 16
	PositionerConstraintAdjustmentResizeY PositionerConstraintAdjustment = 32
)

// Has reports whether v has any bit of flag set. With a flag holding a
// single bit -- the usual case -- that is the membership test.
func (v PositionerConstraintAdjustment) Has(flag PositionerConstraintAdjustment) bool {
	return v&flag != 0
}

const (
	opReqPositionerDestroy                 = 0
	opReqPositionerSetSize                 = 1
	opReqPositionerSetAnchorRect           = 2
	opReqPositionerSetAnchor               = 3
	opReqPositionerSetGravity              = 4
	opReqPositionerSetConstraintAdjustment = 5
	opReqPositionerSetOffset               = 6
	opReqPositionerSetReactive             = 7
	opReqPositionerSetParentSize           = 8
	opReqPositionerSetParentConfigure      = 9
)
