// Code generated by waygenerator. DO NOT EDIT.

package xdgshell

import (
	"fmt"

	"github.com/romycode/ggui/wayland/wlcore"
)

// Surface: desktop user interface surface base interface
//
// An interface that may be implemented by a wl_surface, for
// implementations that provide a desktop-style user interface.
//
// It provides a base set of functionality required to construct user
// interface elements requiring management by the compositor, such as
// toplevel windows, menus, etc. The types of functionality are split into
// xdg_surface roles.
//
// Creating an xdg_surface does not set the role for a wl_surface. In order
// to map an xdg_surface, the client must create a role-specific object
// using, e.g., get_toplevel, get_popup. The wl_surface for any given
// xdg_surface can have at most one role, and may not be assigned any role
// not based on xdg_surface.
//
// A role must be assigned before any other requests are made to the
// xdg_surface object.
//
// The client must call wl_surface.commit on the corresponding wl_surface
// for the xdg_surface state to take effect.
//
// Creating an xdg_surface from a wl_surface which has a buffer attached or
// committed is a client error, and any attempts by a client to attach or
// manipulate a buffer prior to the first xdg_surface.configure call must
// also be treated as errors.
//
// After creating a role-specific object and setting it up (e.g. by sending
// the title, app ID, size constraints, parent, etc), the client must
// perform an initial commit without any buffer attached. The compositor
// will reply with initial wl_surface state such as
// wl_surface.preferred_buffer_scale followed by an xdg_surface.configure
// event. The client must acknowledge it and is then allowed to attach a
// buffer to map the surface.
//
// Mapping an xdg_surface-based role surface is defined as making it
// possible for the surface to be shown by the compositor. Note that
// a mapped surface is not guaranteed to be visible once it is mapped.
//
// For an xdg_surface to be mapped by the compositor, the following
// conditions must be met:
// (1) the client has assigned an xdg_surface-based role to the surface
// (2) the client has set and committed the xdg_surface state and the
// role-dependent state to the surface
// (3) the client has committed a buffer to the surface
//
// A newly-unmapped surface is considered to have met condition (1) out
// of the 3 required conditions for mapping a surface if its role surface
// has not been destroyed, i.e. the client must perform the initial commit
// again before attaching a buffer.
type Surface struct {
	wlcore.ProxyBase
	listener SurfaceListener
}

var _ wlcore.Proxy = (*Surface)(nil)

func newSurface(id, version uint32, conn *wlcore.Conn) *Surface {
	return newSurfaceFromProxyBase(wlcore.NewProxyBase(id, version, conn))
}

func newSurfaceFromProxyBase(base wlcore.ProxyBase) *Surface {
	s := &Surface{ProxyBase: base}
	s.OnClear = func() { s.listener = SurfaceListener{} }
	return s
}

// SetListener installs the handlers for xdg_surface's events, replacing any
// already installed. A nil field ignores that event; a file descriptor
// arriving in an ignored event is closed, not leaked.
func (s *Surface) SetListener(l SurfaceListener) { s.listener = l }

// SurfaceListener holds the handlers for xdg_surface's events. Its zero
// value ignores every event. See [Surface.SetListener].
type SurfaceListener struct {
	// Configure: suggest a surface change
	//
	// The configure event marks the end of a configure sequence. A configure
	// sequence is a set of one or more events configuring the state of the
	// xdg_surface, including the final xdg_surface.configure event.
	//
	// Where applicable, xdg_surface surface roles will during a configure
	// sequence extend this event as a latched state sent as events before the
	// xdg_surface.configure event. Such events should be considered to make up
	// a set of atomically applied configuration states, where the
	// xdg_surface.configure commits the accumulated state.
	//
	// Clients should arrange their surface for the new states, and then send
	// an ack_configure request with the serial sent in this configure event at
	// some point before committing the new surface.
	//
	// If the client receives multiple configure events before it can respond
	// to one, it is free to discard all but the last event it received.
	//
	// Parameters:
	//   - serial: serial of the configure event
	Configure func(serial uint32)
}

// SurfaceInterface describes xdg_surface for [wlcore.Registry.Bind]: the
// name it carries on the wire and version 7, the highest this binding
// implements. Bind negotiates that against the version the compositor
// advertises, so a call site never repeats either value.
var SurfaceInterface = wlcore.Interface[*Surface]{
	Name:       "xdg_surface",
	MaxVersion: 7,
	New:        newSurfaceFromProxyBase,
}

// Destroy: destroy the xdg_surface
//
// Destroy the xdg_surface object. An xdg_surface must only be destroyed
// after its role object has been destroyed, otherwise
// a defunct_role_object error is raised.
func (s *Surface) Destroy() error {
	err := s.Conn().Send(s.ID(), opReqSurfaceDestroy, wlcore.NewEncoder())
	s.Conn().Destroy(s)
	return err
}

// GetToplevel: assign the xdg_toplevel surface role
//
// This creates an xdg_toplevel object for the given xdg_surface and gives
// the associated wl_surface the xdg_toplevel role.
//
// See the documentation of xdg_toplevel for more details about what an
// xdg_toplevel is and how it is used.
func (s *Surface) GetToplevel() (*Toplevel, error) {
	id := s.Conn().NewID()
	x := newToplevelFromProxyBase(wlcore.NewProxyBase(id, s.Version(), s.Conn()))
	s.Conn().Register(x)

	e := wlcore.NewEncoder().ID(id)
	if err := s.Conn().Send(s.ID(), opReqSurfaceGetToplevel, e); err != nil {
		return nil, err
	}
	return x, nil
}

// GetPopup: assign the xdg_popup surface role
//
// This creates an xdg_popup object for the given xdg_surface and gives
// the associated wl_surface the xdg_popup role.
//
// If null is passed as a parent, a parent surface must be specified using
// some other protocol, before committing the initial state.
//
// See the documentation of xdg_popup for more details about what an
// xdg_popup is and how it is used.
func (s *Surface) GetPopup(parent *Surface, positioner *Positioner) (*Popup, error) {
	id := s.Conn().NewID()
	x := newPopupFromProxyBase(wlcore.NewProxyBase(id, s.Version(), s.Conn()))
	s.Conn().Register(x)

	var parentID uint32
	if parent != nil {
		parentID = parent.ID()
	}
	e := wlcore.NewEncoder().ID(id).ID(parentID).ID(positioner.ID())
	if err := s.Conn().Send(s.ID(), opReqSurfaceGetPopup, e); err != nil {
		return nil, err
	}
	return x, nil
}

// SetWindowGeometry: set the new window geometry
//
// The window geometry of a surface is its "visible bounds" from the
// user's perspective. Client-side decorations often have invisible
// portions like drop-shadows which should be ignored for the
// purposes of aligning, placing and constraining windows.
//
// The window geometry is double-buffered state, see wl_surface.commit.
//
// When maintaining a position, the compositor should treat the (x, y)
// coordinate of the window geometry as the top left corner of the window.
// A client changing the (x, y) window geometry coordinate should in
// general not alter the position of the window.
//
// Once the window geometry of the surface is set, it is not possible to
// unset it, and it will remain the same until set_window_geometry is
// called again, even if a new subsurface or buffer is attached.
//
// If never set, the value is the full bounds of the surface,
// including any subsurfaces. This updates dynamically on every
// commit. This unset is meant for extremely simple clients.
//
// The arguments are given in the surface-local coordinate space of
// the wl_surface associated with this xdg_surface, and may extend outside
// of the wl_surface itself to mark parts of the subsurface tree as part of
// the window geometry.
//
// When applied, the effective window geometry will be the set window
// geometry clamped to the bounding rectangle of the combined
// geometry of the surface of the xdg_surface and the associated
// subsurfaces.
//
// The effective geometry will not be recalculated unless a new call to
// set_window_geometry is done and the new pending surface state is
// subsequently applied.
//
// The width and height of the effective window geometry must be
// greater than zero. Setting an invalid size will raise an
// invalid_size error.
func (s *Surface) SetWindowGeometry(x int32, y int32, width int32, height int32) error {
	e := wlcore.NewEncoder().Int32(x).Int32(y).Int32(width).Int32(height)
	return s.Conn().Send(s.ID(), opReqSurfaceSetWindowGeometry, e)
}

// AckConfigure: ack a configure event
//
// When a configure event is received, if a client commits the
// surface in response to the configure event, then the client
// must make an ack_configure request sometime before the commit
// request, passing along the serial of the configure event.
//
// For instance, for toplevel surfaces the compositor might use this
// information to move a surface to the top left only when the client has
// drawn itself for the maximized or fullscreen state.
//
// If the client receives multiple configure events before it
// can respond to one, it only has to ack the last configure event.
// Acking a configure event that was never sent raises an invalid_serial
// error.
//
// A client is not required to commit immediately after sending
// an ack_configure request - it may even ack_configure several times
// before its next surface commit.
//
// A client may send multiple ack_configure requests before committing, but
// only the last request sent before a commit indicates which configure
// event the client really is responding to.
//
// Sending an ack_configure request consumes the serial number sent with
// the request, as well as serial numbers sent by all configure events
// sent on this xdg_surface prior to the configure event referenced by
// the committed serial.
//
// It is an error to issue multiple ack_configure requests referencing a
// serial from the same configure event, or to issue an ack_configure
// request referencing a serial from a configure event issued before the
// event identified by the last ack_configure request for the same
// xdg_surface. Doing so will raise an invalid_serial error.
//
// Parameters:
//   - serial: the serial from the configure event
func (s *Surface) AckConfigure(serial uint32) error {
	e := wlcore.NewEncoder().Uint32(serial)
	return s.Conn().Send(s.ID(), opReqSurfaceAckConfigure, e)
}

// Dispatch decodes one xdg_surface event and calls the matching field of
// the listener. The connection calls it while pumping messages; it is
// exported only because the runtime's Proxy interface requires it.
func (s *Surface) Dispatch(opcode uint16, dec *wlcore.Decoder) error {
	switch opcode {
	case opEvtSurfaceConfigure:
		serial := dec.Uint32()
		if err := dec.Err(); err != nil {
			return err
		}
		if s.listener.Configure != nil {
			s.listener.Configure(serial)
		}
	default:
		return fmt.Errorf("xdgshell: unknown opcode %d in xdg_surface", opcode)
	}
	return nil
}

// SurfaceError enumerates the protocol errors xdg_surface can raise. The
// compositor reports one through wl_display.error.
type SurfaceError uint32

const (
	SurfaceErrorNotConstructed     SurfaceError = 1 // Surface was not fully constructed
	SurfaceErrorAlreadyConstructed SurfaceError = 2 // Surface was already constructed
	SurfaceErrorUnconfiguredBuffer SurfaceError = 3 // Attaching a buffer to an unconfigured surface
	SurfaceErrorInvalidSerial      SurfaceError = 4 // Invalid serial number when acking a configure event
	SurfaceErrorInvalidSize        SurfaceError = 5 // Width or height was zero or negative
	SurfaceErrorDefunctRoleObject  SurfaceError = 6 // Surface was destroyed before its role object
)

const (
	opReqSurfaceDestroy           = 0
	opReqSurfaceGetToplevel       = 1
	opReqSurfaceGetPopup          = 2
	opReqSurfaceSetWindowGeometry = 3
	opReqSurfaceAckConfigure      = 4
	opEvtSurfaceConfigure         = 0
)
