// Code generated by waygenerator. DO NOT EDIT.

package wlcore

import "fmt"

// Buffer: content for a wl_surface
//
// A buffer provides the content for a wl_surface. Buffers are
// created through factory interfaces such as wl_shm, wp_linux_buffer_params
// (from the linux-dmabuf protocol extension) or similar. It has a width and
// a height and can be attached to a wl_surface, but the mechanism by which a
// client provides and updates the contents is defined by the buffer factory
// interface.
//
// Color channels are assumed to be electrical rather than optical (in other
// words, encoded with a transfer function) unless otherwise specified. If
// the buffer uses a format that has an alpha channel, the alpha channel is
// assumed to be premultiplied into the electrical color channel values
// (after transfer function encoding) unless otherwise specified.
//
// Note, because wl_buffer objects are created from multiple independent
// factory interfaces, the wl_buffer interface is frozen at version 1.
type Buffer struct {
	ProxyBase
	listener BufferListener
}

var _ Proxy = (*Buffer)(nil)

func newBuffer(id, version uint32, conn *Conn) *Buffer {
	return newBufferFromProxyBase(NewProxyBase(id, version, conn))
}

func newBufferFromProxyBase(base ProxyBase) *Buffer {
	b := &Buffer{ProxyBase: base}
	b.OnClear = func() { b.listener = BufferListener{} }
	return b
}

// SetListener installs the handlers for wl_buffer's events, replacing any
// already installed. A nil field ignores that event; a file descriptor
// arriving in an ignored event is closed, not leaked.
func (b *Buffer) SetListener(l BufferListener) { b.listener = l }

// BufferListener holds the handlers for wl_buffer's events. Its zero value
// ignores every event. See [Buffer.SetListener].
type BufferListener struct {
	// Release: compositor releases buffer
	//
	// Sent when this wl_buffer is no longer used by the compositor.
	//
	// For more information on when release events may or may not be sent,
	// and what consequences it has, please see the description of
	// wl_surface.attach.
	//
	// If a client receives a release event before the frame callback
	// requested in the same wl_surface.commit that attaches this
	// wl_buffer to a surface, then the client is immediately free to
	// reuse the buffer and its backing storage, and does not need a
	// second buffer for the next surface content update. Typically
	// this is possible, when the compositor maintains a copy of the
	// wl_surface contents, e.g. as a GL texture. This is an important
	// optimization for GL(ES) compositors with wl_shm clients.
	Release func()
}

// BufferInterface describes wl_buffer for [Registry.Bind]: the name it
// carries on the wire and version 1, the highest this binding implements.
// Bind negotiates that against the version the compositor advertises, so a
// call site never repeats either value.
var BufferInterface = Interface[*Buffer]{
	Name:       "wl_buffer",
	MaxVersion: 1,
	New:        newBufferFromProxyBase,
}

// Destroy: destroy a buffer
//
// Destroy a buffer. If and how you need to release the backing
// storage is defined by the buffer factory interface.
//
// For possible side-effects to a surface, see wl_surface.attach.
func (b *Buffer) Destroy() error {
	err := b.Conn().Send(b.ID(), opReqBufferDestroy, NewEncoder())
	b.Conn().Destroy(b)
	return err
}

// Dispatch decodes one wl_buffer event and calls the matching field of the
// listener. The connection calls it while pumping messages; it is exported
// only because the runtime's Proxy interface requires it.
func (b *Buffer) Dispatch(opcode uint16, dec *Decoder) error {
	switch opcode {
	case opEvtBufferRelease:
		if err := dec.Err(); err != nil {
			return err
		}
		if b.listener.Release != nil {
			b.listener.Release()
		}
	default:
		return fmt.Errorf("wlcore: unknown opcode %d in wl_buffer", opcode)
	}
	return nil
}

const (
	opReqBufferDestroy = 0
	opEvtBufferRelease = 0
)
