// Code generated by waygenerator. DO NOT EDIT.

package wlcore

import "fmt"

// Callback: callback object
//
// Clients can handle the 'done' event to get notified when
// the related request is done.
//
// Note, because wl_callback objects are created from multiple independent
// factory interfaces, the wl_callback interface is frozen at version 1.
type Callback struct {
	ProxyBase
	listener CallbackListener
}

var _ Proxy = (*Callback)(nil)

func newCallback(id, version uint32, conn *Conn) *Callback {
	return newCallbackFromProxyBase(NewProxyBase(id, version, conn))
}

func newCallbackFromProxyBase(base ProxyBase) *Callback {
	c := &Callback{ProxyBase: base}
	c.OnClear = func() { c.listener = CallbackListener{} }
	return c
}

func (c *Callback) SetListener(l CallbackListener) { c.listener = l }

type CallbackListener struct {
	// Done: done event
	//
	// Notify the client when the related request is done.
	//
	// Parameters:
	//   - callbackData: request-specific data for the callback
	Done func(callbackData uint32)
}

var CallbackInterface = Interface[*Callback]{
	Name:       "wl_callback",
	MaxVersion: 1,
	New:        newCallbackFromProxyBase,
}

func (c *Callback) Dispatch(opcode uint16, dec *Decoder) error {
	switch opcode {
	case opEvtCallbackDone:
		callbackData := dec.Uint32()
		if err := dec.Err(); err != nil {
			return err
		}
		if c.listener.Done != nil {
			c.listener.Done(callbackData)
		}
		c.Conn().destroy(c)
	default:
		return fmt.Errorf("wlcore: opcode %d desconocido en wl_callback", opcode)
	}
	return nil
}

const (
	opEvtCallbackDone = 0
)
