// Code generated by waygenerator. DO NOT EDIT.

package wlcore

import "fmt"

// Compositor: the compositor singleton
//
// A compositor.  This object is a singleton global.  The
// compositor is in charge of combining the contents of multiple
// surfaces into one displayable output.
type Compositor struct {
	ProxyBase
	listener CompositorListener
}

var _ Proxy = (*Compositor)(nil)

func newCompositor(id, version uint32, conn *Conn) *Compositor {
	return newCompositorFromProxyBase(NewProxyBase(id, version, conn))
}

func newCompositorFromProxyBase(base ProxyBase) *Compositor {
	c := &Compositor{ProxyBase: base}
	return c
}

func (c *Compositor) SetListener(l CompositorListener) { c.listener = l }

type CompositorListener struct {
}

var CompositorInterface = Interface[*Compositor]{
	Name:       "wl_compositor",
	MaxVersion: 7,
	New:        newCompositorFromProxyBase,
}

// CreateSurface: create new surface
//
// Ask the compositor to create a new surface.
func (c *Compositor) CreateSurface() (*Surface, error) {
	id := c.Conn().NewID()
	x := newSurfaceFromProxyBase(NewProxyBase(id, c.Version(), c.Conn()))
	c.Conn().Register(x)

	e := NewEncoder().ID(id)
	if err := c.Conn().Send(c.ID(), opReqCompositorCreateSurface, e); err != nil {
		return nil, err
	}
	return x, nil
}

// CreateRegion: create new region
//
// Ask the compositor to create a new region.
func (c *Compositor) CreateRegion() (*Region, error) {
	id := c.Conn().NewID()
	x := newRegionFromProxyBase(NewProxyBase(id, c.Version(), c.Conn()))
	c.Conn().Register(x)

	e := NewEncoder().ID(id)
	if err := c.Conn().Send(c.ID(), opReqCompositorCreateRegion, e); err != nil {
		return nil, err
	}
	return x, nil
}

// Release: destroy wl_compositor
//
// This request destroys the wl_compositor. This has no effect on any other objects.
func (c *Compositor) Release() error {
	if c.Version() < 7 {
		return fmt.Errorf("wlcore: release requiere versión >= 7, hay %d", c.Version())
	}
	err := c.Conn().Send(c.ID(), opReqCompositorRelease, NewEncoder())
	c.Conn().destroy(c)
	return err
}

func (c *Compositor) Dispatch(opcode uint16, dec *Decoder) error {
	switch opcode {
	default:
		return fmt.Errorf("wlcore: opcode %d desconocido en wl_compositor", opcode)
	}
}

const (
	opReqCompositorCreateSurface = 0
	opReqCompositorCreateRegion  = 1
	opReqCompositorRelease       = 2
)
