// Code generated by waygenerator. DO NOT EDIT.

package wlcore

import "fmt"

// DataDeviceManager: data transfer interface
//
// The wl_data_device_manager is a singleton global object that
// provides access to inter-client data transfer mechanisms such as
// copy-and-paste and drag-and-drop.  These mechanisms are tied to
// a wl_seat and this interface lets a client get a wl_data_device
// corresponding to a wl_seat.
//
// Depending on the version bound, the objects created from the bound
// wl_data_device_manager object will have different requirements for
// functioning properly. See wl_data_source.set_actions,
// wl_data_offer.accept and wl_data_offer.finish for details.
type DataDeviceManager struct {
	ProxyBase
	listener DataDeviceManagerListener
}

var _ Proxy = (*DataDeviceManager)(nil)

func newDataDeviceManager(id, version uint32, conn *Conn) *DataDeviceManager {
	return newDataDeviceManagerFromProxyBase(NewProxyBase(id, version, conn))
}

func newDataDeviceManagerFromProxyBase(base ProxyBase) *DataDeviceManager {
	d := &DataDeviceManager{ProxyBase: base}
	return d
}

// SetListener installs the handlers for wl_data_device_manager's events,
// replacing any already installed. A nil field ignores that event; a file
// descriptor arriving in an ignored event is closed, not leaked.
func (d *DataDeviceManager) SetListener(l DataDeviceManagerListener) { d.listener = l }

// DataDeviceManagerListener holds the handlers for wl_data_device_manager's
// events. Its zero value ignores every event. See
// [DataDeviceManager.SetListener].
type DataDeviceManagerListener struct {
}

// DataDeviceManagerInterface describes wl_data_device_manager for
// [Registry.Bind]: the name it carries on the wire and version 3, the
// highest this binding implements. Bind negotiates that against the version
// the compositor advertises, so a call site never repeats either value.
var DataDeviceManagerInterface = Interface[*DataDeviceManager]{
	Name:       "wl_data_device_manager",
	MaxVersion: 3,
	New:        newDataDeviceManagerFromProxyBase,
}

// CreateDataSource: create a new data source
//
// Create a new data source.
func (d *DataDeviceManager) CreateDataSource() (*DataSource, error) {
	id := d.Conn().NewID()
	x := newDataSourceFromProxyBase(NewProxyBase(id, d.Version(), d.Conn()))
	d.Conn().Register(x)

	e := NewEncoder().ID(id)
	if err := d.Conn().Send(d.ID(), opReqDataDeviceManagerCreateDataSource, e); err != nil {
		return nil, err
	}
	return x, nil
}

// GetDataDevice: create a new data device
//
// Create a new data device for a given seat.
//
// Parameters:
//   - seat: seat associated with the data device
func (d *DataDeviceManager) GetDataDevice(seat *Seat) (*DataDevice, error) {
	id := d.Conn().NewID()
	x := newDataDeviceFromProxyBase(NewProxyBase(id, d.Version(), d.Conn()))
	d.Conn().Register(x)

	e := NewEncoder().ID(id).ID(seat.ID())
	if err := d.Conn().Send(d.ID(), opReqDataDeviceManagerGetDataDevice, e); err != nil {
		return nil, err
	}
	return x, nil
}

// Dispatch decodes one wl_data_device_manager event and calls the matching
// field of the listener. The connection calls it while pumping messages; it
// is exported only because the runtime's Proxy interface requires it.
func (d *DataDeviceManager) Dispatch(opcode uint16, dec *Decoder) error {
	switch opcode {
	default:
		return fmt.Errorf("wlcore: unknown opcode %d in wl_data_device_manager", opcode)
	}
}

// DataDeviceManagerDndAction: drag and drop actions
//
// This is a bitmask of the available/preferred actions in a
// drag-and-drop operation.
//
// In the compositor, the selected action is a result of matching the
// actions offered by the source and destination sides.  "action" events
// with a "none" action will be sent to both source and destination if
// there is no match. All further checks will effectively happen on
// (source actions ∩ destination actions).
//
// In addition, compositors may also pick different actions in
// reaction to key modifiers being pressed. One common design that
// is used in major toolkits (and the behavior recommended for
// compositors) is:
//
// - If no modifiers are pressed, the first match (in bit order)
// will be used.
// - Pressing Shift selects "move", if enabled in the mask.
// - Pressing Control selects "copy", if enabled in the mask.
//
// Behavior beyond that is considered implementation-dependent.
// Compositors may for example bind other modifiers (like Alt/Meta)
// or drags initiated with other buttons than BTN_LEFT to specific
// actions (e.g. "ask").
type DataDeviceManagerDndAction uint32

const (
	DataDeviceManagerDndActionNone DataDeviceManagerDndAction = 0 // no action
	DataDeviceManagerDndActionCopy DataDeviceManagerDndAction = 1 // copy action
	DataDeviceManagerDndActionMove DataDeviceManagerDndAction = 2 // move action
	DataDeviceManagerDndActionAsk  DataDeviceManagerDndAction = 4 // ask action
)

// Has reports whether v has any bit of flag set. With a flag holding a
// single bit -- the usual case -- that is the membership test.
func (v DataDeviceManagerDndAction) Has(flag DataDeviceManagerDndAction) bool { return v&flag != 0 }

const (
	opReqDataDeviceManagerCreateDataSource = 0
	opReqDataDeviceManagerGetDataDevice    = 1
)
