// Code generated by waygenerator. DO NOT EDIT.

package wlcore

import "fmt"

type DataOffer struct {
	ProxyBase
	listener DataOfferListener
}

var _ Proxy = (*DataOffer)(nil)

func newDataOffer(id, version uint32, conn *Conn) *DataOffer {
	return newDataOfferFromProxyBase(NewProxyBase(id, version, conn))
}

func newDataOfferFromProxyBase(base ProxyBase) *DataOffer {
	d := &DataOffer{ProxyBase: base}
	d.OnClear = func() { d.listener = DataOfferListener{} }
	return d
}

func (d *DataOffer) SetListener(l DataOfferListener) { d.listener = l }

type DataOfferListener struct {
	Offer         func(mimeType string)
	SourceActions func(sourceActions DataDeviceManagerDndAction)
	Action        func(dndAction DataDeviceManagerDndAction)
}

var DataOfferInterface = Interface[*DataOffer]{
	Name:       "wl_data_offer",
	MaxVersion: 4,
	New:        newDataOfferFromProxyBase,
}

func (d *DataOffer) Accept(serial uint32, mimeType *string) error {
	e := NewEncoder().Uint32(serial).StringOpt(mimeType)
	return d.Conn().Send(d.ID(), opReqDataOfferAccept, e)
}

func (d *DataOffer) Receive(mimeType string, fd int) error {
	e := NewEncoder().String(mimeType)
	return d.Conn().Send(d.ID(), opReqDataOfferReceive, e, fd)
}

func (d *DataOffer) Destroy() error {
	err := d.Conn().Send(d.ID(), opReqDataOfferDestroy, NewEncoder())
	d.Conn().destroy(d)
	return err
}

func (d *DataOffer) Finish() error {
	if d.Version() < 3 {
		return fmt.Errorf("wlcore: finish requiere versión >= 3, hay %d", d.Version())
	}
	e := NewEncoder()
	return d.Conn().Send(d.ID(), opReqDataOfferFinish, e)
}

func (d *DataOffer) SetActions(dndActions DataDeviceManagerDndAction, preferredAction DataDeviceManagerDndAction) error {
	if d.Version() < 3 {
		return fmt.Errorf("wlcore: set_actions requiere versión >= 3, hay %d", d.Version())
	}
	e := NewEncoder().Uint32(uint32(dndActions)).Uint32(uint32(preferredAction))
	return d.Conn().Send(d.ID(), opReqDataOfferSetActions, e)
}

func (d *DataOffer) Dispatch(opcode uint16, dec *Decoder) error {
	switch opcode {
	case opEvtDataOfferOffer:
		mimeType := dec.String()
		if err := dec.Err(); err != nil {
			return err
		}
		if d.listener.Offer != nil {
			d.listener.Offer(mimeType)
		}
	case opEvtDataOfferSourceActions:
		sourceActions := DataDeviceManagerDndAction(dec.Uint32())
		if err := dec.Err(); err != nil {
			return err
		}
		if d.listener.SourceActions != nil {
			d.listener.SourceActions(sourceActions)
		}
	case opEvtDataOfferAction:
		dndAction := DataDeviceManagerDndAction(dec.Uint32())
		if err := dec.Err(); err != nil {
			return err
		}
		if d.listener.Action != nil {
			d.listener.Action(dndAction)
		}
	default:
		return fmt.Errorf("wlcore: opcode %d desconocido en wl_data_offer", opcode)
	}
	return nil
}

type DataOfferError uint32

const (
	DataOfferErrorInvalidFinish     DataOfferError = 0
	DataOfferErrorInvalidActionMask DataOfferError = 1
	DataOfferErrorInvalidAction     DataOfferError = 2
	DataOfferErrorInvalidOffer      DataOfferError = 3
)

const (
	opReqDataOfferAccept        = 0
	opReqDataOfferReceive       = 1
	opReqDataOfferDestroy       = 2
	opReqDataOfferFinish        = 3
	opReqDataOfferSetActions    = 4
	opEvtDataOfferOffer         = 0
	opEvtDataOfferSourceActions = 1
	opEvtDataOfferAction        = 2
)
