// Code generated by waygenerator. DO NOT EDIT.

package wlcore

import "fmt"

// DataDevice: data transfer device
//
// There is one wl_data_device per seat which can be obtained
// from the global wl_data_device_manager singleton.
//
// A wl_data_device provides access to inter-client data transfer
// mechanisms such as copy-and-paste and drag-and-drop.
type DataDevice struct {
	ProxyBase
	listener DataDeviceListener
}

var _ Proxy = (*DataDevice)(nil)

func newDataDevice(id, version uint32, conn *Conn) *DataDevice {
	return newDataDeviceFromProxyBase(NewProxyBase(id, version, conn))
}

func newDataDeviceFromProxyBase(base ProxyBase) *DataDevice {
	d := &DataDevice{ProxyBase: base}
	d.OnClear = func() { d.listener = DataDeviceListener{} }
	return d
}

// SetListener installs the handlers for wl_data_device's events, replacing
// any already installed. A nil field ignores that event; a file descriptor
// arriving in an ignored event is closed, not leaked.
func (d *DataDevice) SetListener(l DataDeviceListener) { d.listener = l }

// DataDeviceListener holds the handlers for wl_data_device's events. Its
// zero value ignores every event. See [DataDevice.SetListener].
type DataDeviceListener struct {
	// DataOffer: introduce a new wl_data_offer
	//
	// The data_offer event introduces a new wl_data_offer object,
	// which will subsequently be used in either the
	// data_device.enter event (for drag-and-drop) or the
	// data_device.selection event (for selections).  Immediately
	// following the data_device.data_offer event, the new data_offer
	// object will send out data_offer.offer events to describe the
	// mime types it offers.
	//
	// Parameters:
	//   - id: the new data_offer object
	DataOffer func(id *DataOffer)
	// Enter: initiate drag-and-drop session
	//
	// This event is sent when an active drag-and-drop pointer enters
	// a surface owned by the client.  The position of the pointer at
	// enter time is provided by the x and y arguments, in surface-local
	// coordinates.
	//
	// Parameters:
	//   - serial: serial number of the enter event
	//   - surface: client surface entered
	//   - x: surface-local x coordinate
	//   - y: surface-local y coordinate
	//   - id: source data_offer object
	Enter func(serial uint32, surface *Surface, x Fixed, y Fixed, id *DataOffer)
	// Leave: end drag-and-drop session
	//
	// This event is sent when the drag-and-drop pointer leaves the
	// surface and the session ends.  The client must destroy the
	// wl_data_offer introduced at enter time at this point.
	Leave func()
	// Motion: drag-and-drop session motion
	//
	// This event is sent when the drag-and-drop pointer moves within
	// the currently focused surface. The new position of the pointer
	// is provided by the x and y arguments, in surface-local
	// coordinates.
	//
	// Parameters:
	//   - time: timestamp with millisecond granularity
	//   - x: surface-local x coordinate
	//   - y: surface-local y coordinate
	Motion func(time uint32, x Fixed, y Fixed)
	// Drop: end drag-and-drop session successfully
	//
	// The event is sent when a drag-and-drop operation is ended
	// because the implicit grab is removed.
	//
	// The drag-and-drop destination is expected to honor the last action
	// received through wl_data_offer.action, if the resulting action is
	// "copy" or "move", the destination can still perform
	// wl_data_offer.receive requests, and is expected to end all
	// transfers with a wl_data_offer.finish request.
	//
	// If the resulting action is "ask", the action will not be considered
	// final. The drag-and-drop destination is expected to perform one last
	// wl_data_offer.set_actions request, or wl_data_offer.destroy in order
	// to cancel the operation.
	Drop func()
	// Selection: advertise new selection
	//
	// The selection event is sent out to notify the client of a new
	// wl_data_offer for the selection for this device.  The
	// data_device.data_offer and the data_offer.offer events are
	// sent out immediately before this event to introduce the data
	// offer object.  The selection event is sent to a client
	// immediately before receiving keyboard focus and when a new
	// selection is set while the client has keyboard focus.  The
	// data_offer is valid until a new data_offer or NULL is received
	// or until the client loses keyboard focus.  Switching surface with
	// keyboard focus within the same client doesn't mean a new selection
	// will be sent.  The client must destroy the previous selection
	// data_offer, if any, upon receiving this event.
	//
	// Parameters:
	//   - id: selection data_offer object
	Selection func(id *DataOffer)
}

// DataDeviceInterface describes wl_data_device for [Registry.Bind]: the
// name it carries on the wire and version 3, the highest this binding
// implements. Bind negotiates that against the version the compositor
// advertises, so a call site never repeats either value.
var DataDeviceInterface = Interface[*DataDevice]{
	Name:       "wl_data_device",
	MaxVersion: 3,
	New:        newDataDeviceFromProxyBase,
}

// StartDrag: start drag-and-drop operation
//
// This request asks the compositor to start a drag-and-drop
// operation on behalf of the client.
//
// The source argument is the data source that provides the data
// for the eventual data transfer. If source is NULL, enter, leave
// and motion events are sent only to the client that initiated the
// drag and the client is expected to handle the data passing
// internally. If source is destroyed, the drag-and-drop session will be
// cancelled.
//
// The origin surface is the surface where the drag originates and
// the client must have an active implicit grab that matches the
// serial.
//
// The icon surface is an optional (can be NULL) surface that
// provides an icon to be moved around with the cursor.  Initially,
// the top-left corner of the icon surface is placed at the cursor
// hotspot, but subsequent wl_surface.offset requests can move the
// relative position. Attach requests must be confirmed with
// wl_surface.commit as usual. The icon surface is given the role of
// a drag-and-drop icon. If the icon surface already has another role,
// it raises a protocol error.
//
// The input region is ignored for wl_surfaces with the role of a
// drag-and-drop icon.
//
// The given source may not be used in any further set_selection or
// start_drag requests. Attempting to reuse a previously-used source
// may send a used_source error.
//
// Parameters:
//   - source: data source for the eventual transfer
//   - origin: surface where the drag originates
//   - icon: drag-and-drop icon surface
//   - serial: serial number of the implicit grab on the origin
func (d *DataDevice) StartDrag(source *DataSource, origin *Surface, icon *Surface, serial uint32) error {
	var sourceID uint32
	if source != nil {
		sourceID = source.ID()
	}
	var iconID uint32
	if icon != nil {
		iconID = icon.ID()
	}
	e := NewEncoder().ID(sourceID).ID(origin.ID()).ID(iconID).Uint32(serial)
	return d.Conn().Send(d.ID(), opReqDataDeviceStartDrag, e)
}

// SetSelection: copy data to the selection
//
// This request asks the compositor to set the selection
// to the data from the source on behalf of the client.
//
// To unset the selection, set the source to NULL.
//
// The given source may not be used in any further set_selection or
// start_drag requests. Attempting to reuse a previously-used source
// may send a used_source error.
//
// Parameters:
//   - source: data source for the selection
//   - serial: serial number of the event that triggered this request
func (d *DataDevice) SetSelection(source *DataSource, serial uint32) error {
	var sourceID uint32
	if source != nil {
		sourceID = source.ID()
	}
	e := NewEncoder().ID(sourceID).Uint32(serial)
	return d.Conn().Send(d.ID(), opReqDataDeviceSetSelection, e)
}

// Release: destroy data device
//
// This request destroys the data device.
func (d *DataDevice) Release() error {
	if d.Version() < 2 {
		return fmt.Errorf("wlcore: release requires version >= 2, got %d", d.Version())
	}
	err := d.Conn().Send(d.ID(), opReqDataDeviceRelease, NewEncoder())
	d.Conn().Destroy(d)
	return err
}

// Dispatch decodes one wl_data_device event and calls the matching field of
// the listener. The connection calls it while pumping messages; it is
// exported only because the runtime's Proxy interface requires it.
func (d *DataDevice) Dispatch(opcode uint16, dec *Decoder) error {
	switch opcode {
	case opEvtDataDeviceDataOffer:
		idID := dec.ID()
		if err := dec.Err(); err != nil {
			return err
		}
		id := newDataOfferFromProxyBase(NewProxyBase(idID, d.Version(), d.Conn()))
		d.Conn().Register(id)
		if d.listener.DataOffer != nil {
			d.listener.DataOffer(id)
		}
	case opEvtDataDeviceEnter:
		serial := dec.Uint32()
		surfaceID := dec.ID()
		x := dec.Fixed()
		y := dec.Fixed()
		idID := dec.ID()
		if err := dec.Err(); err != nil {
			return err
		}
		surface, _ := d.Conn().Lookup(surfaceID).(*Surface)
		id, _ := d.Conn().Lookup(idID).(*DataOffer)
		if d.listener.Enter != nil {
			d.listener.Enter(serial, surface, x, y, id)
		}
	case opEvtDataDeviceLeave:
		if err := dec.Err(); err != nil {
			return err
		}
		if d.listener.Leave != nil {
			d.listener.Leave()
		}
	case opEvtDataDeviceMotion:
		time := dec.Uint32()
		x := dec.Fixed()
		y := dec.Fixed()
		if err := dec.Err(); err != nil {
			return err
		}
		if d.listener.Motion != nil {
			d.listener.Motion(time, x, y)
		}
	case opEvtDataDeviceDrop:
		if err := dec.Err(); err != nil {
			return err
		}
		if d.listener.Drop != nil {
			d.listener.Drop()
		}
	case opEvtDataDeviceSelection:
		idID := dec.ID()
		if err := dec.Err(); err != nil {
			return err
		}
		id, _ := d.Conn().Lookup(idID).(*DataOffer)
		if d.listener.Selection != nil {
			d.listener.Selection(id)
		}
	default:
		return fmt.Errorf("wlcore: unknown opcode %d in wl_data_device", opcode)
	}
	return nil
}

// DataDeviceError enumerates the protocol errors wl_data_device can raise.
// The compositor reports one through wl_display.error.
type DataDeviceError uint32

const (
	DataDeviceErrorRole       DataDeviceError = 0 // given wl_surface has another role
	DataDeviceErrorUsedSource DataDeviceError = 1 // source has already been used
)

const (
	opReqDataDeviceStartDrag    = 0
	opReqDataDeviceSetSelection = 1
	opReqDataDeviceRelease      = 2
	opEvtDataDeviceDataOffer    = 0
	opEvtDataDeviceEnter        = 1
	opEvtDataDeviceLeave        = 2
	opEvtDataDeviceMotion       = 3
	opEvtDataDeviceDrop         = 4
	opEvtDataDeviceSelection    = 5
)
