// Code generated by waygenerator. DO NOT EDIT.

package wlcore

import "fmt"

type DataSource struct {
	ProxyBase
	listener DataSourceListener
}

var _ Proxy = (*DataSource)(nil)

func newDataSource(id, version uint32, conn *Conn) *DataSource {
	return newDataSourceFromProxyBase(NewProxyBase(id, version, conn))
}

func newDataSourceFromProxyBase(base ProxyBase) *DataSource {
	d := &DataSource{ProxyBase: base}
	d.OnClear = func() { d.listener = DataSourceListener{} }
	return d
}

func (d *DataSource) SetListener(l DataSourceListener) { d.listener = l }

type DataSourceListener struct {
	Target           func(mimeType *string)
	Send             func(mimeType string, fd int)
	Cancelled        func()
	DndDropPerformed func()
	DndFinished      func()
	Action           func(dndAction DataDeviceManagerDndAction)
}

var DataSourceInterface = Interface[*DataSource]{
	Name:       "wl_data_source",
	MaxVersion: 4,
	New:        newDataSourceFromProxyBase,
}

func (d *DataSource) Offer(mimeType string) error {
	e := NewEncoder().String(mimeType)
	return d.Conn().Send(d.ID(), opReqDataSourceOffer, e)
}

func (d *DataSource) Destroy() error {
	err := d.Conn().Send(d.ID(), opReqDataSourceDestroy, NewEncoder())
	d.Conn().destroy(d)
	return err
}

func (d *DataSource) SetActions(dndActions DataDeviceManagerDndAction) error {
	if d.Version() < 3 {
		return fmt.Errorf("wlcore: set_actions requiere versión >= 3, hay %d", d.Version())
	}
	e := NewEncoder().Uint32(uint32(dndActions))
	return d.Conn().Send(d.ID(), opReqDataSourceSetActions, e)
}

func (d *DataSource) Dispatch(opcode uint16, dec *Decoder) error {
	switch opcode {
	case opEvtDataSourceTarget:
		mimeType := dec.StringOpt()
		if err := dec.Err(); err != nil {
			return err
		}
		if d.listener.Target != nil {
			d.listener.Target(mimeType)
		}
	case opEvtDataSourceSend:
		mimeType := dec.String()
		fd := dec.FD()
		if err := dec.Err(); err != nil {
			DropFD(fd)
			return err
		}
		if d.listener.Send == nil {
			DropFD(fd)
			break
		}
		d.listener.Send(mimeType, fd)
	case opEvtDataSourceCancelled:
		if err := dec.Err(); err != nil {
			return err
		}
		if d.listener.Cancelled != nil {
			d.listener.Cancelled()
		}
	case opEvtDataSourceDndDropPerformed:
		if err := dec.Err(); err != nil {
			return err
		}
		if d.listener.DndDropPerformed != nil {
			d.listener.DndDropPerformed()
		}
	case opEvtDataSourceDndFinished:
		if err := dec.Err(); err != nil {
			return err
		}
		if d.listener.DndFinished != nil {
			d.listener.DndFinished()
		}
	case opEvtDataSourceAction:
		dndAction := DataDeviceManagerDndAction(dec.Uint32())
		if err := dec.Err(); err != nil {
			return err
		}
		if d.listener.Action != nil {
			d.listener.Action(dndAction)
		}
	default:
		return fmt.Errorf("wlcore: opcode %d desconocido en wl_data_source", opcode)
	}
	return nil
}

type DataSourceError uint32

const (
	DataSourceErrorInvalidActionMask DataSourceError = 0
	DataSourceErrorInvalidSource     DataSourceError = 1
)

const (
	opReqDataSourceOffer            = 0
	opReqDataSourceDestroy          = 1
	opReqDataSourceSetActions       = 2
	opEvtDataSourceTarget           = 0
	opEvtDataSourceSend             = 1
	opEvtDataSourceCancelled        = 2
	opEvtDataSourceDndDropPerformed = 3
	opEvtDataSourceDndFinished      = 4
	opEvtDataSourceAction           = 5
)
