// Code generated by waygenerator. DO NOT EDIT.

package wlcore

import "fmt"

type DataDeviceManager struct {
	ProxyBase
	listener DataDeviceManagerListener
}

var _ Proxy = (*DataDeviceManager)(nil)

func newDataDeviceManager(id, version uint32, conn *Conn) *DataDeviceManager {
	return newDataDeviceManagerFromProxyBase(NewProxyBase(id, version, conn))
}

func newDataDeviceManagerFromProxyBase(base ProxyBase) *DataDeviceManager {
	d := &DataDeviceManager{ProxyBase: base}
	return d
}

func (d *DataDeviceManager) SetListener(l DataDeviceManagerListener) { d.listener = l }

type DataDeviceManagerListener struct {
}

var DataDeviceManagerInterface = Interface[*DataDeviceManager]{
	Name:       "wl_data_device_manager",
	MaxVersion: 4,
	New:        newDataDeviceManagerFromProxyBase,
}

func (d *DataDeviceManager) CreateDataSource() (*DataSource, error) {
	id := d.Conn().NewID()
	x := newDataSourceFromProxyBase(NewProxyBase(id, d.Version(), d.Conn()))
	d.Conn().Register(x)

	e := NewEncoder().ID(id)
	if err := d.Conn().Send(d.ID(), opReqDataDeviceManagerCreateDataSource, e); err != nil {
		return nil, err
	}
	return x, nil
}

func (d *DataDeviceManager) GetDataDevice(seat *Seat) (*DataDevice, error) {
	id := d.Conn().NewID()
	x := newDataDeviceFromProxyBase(NewProxyBase(id, d.Version(), d.Conn()))
	d.Conn().Register(x)

	e := NewEncoder().ID(id).ID(seat.ID())
	if err := d.Conn().Send(d.ID(), opReqDataDeviceManagerGetDataDevice, e); err != nil {
		return nil, err
	}
	return x, nil
}

func (d *DataDeviceManager) Release() error {
	if d.Version() < 4 {
		return fmt.Errorf("wlcore: release requiere versión >= 4, hay %d", d.Version())
	}
	err := d.Conn().Send(d.ID(), opReqDataDeviceManagerRelease, NewEncoder())
	d.Conn().destroy(d)
	return err
}

func (d *DataDeviceManager) Dispatch(opcode uint16, dec *Decoder) error {
	switch opcode {
	default:
		return fmt.Errorf("wlcore: opcode %d desconocido en wl_data_device_manager", opcode)
	}
}

type DataDeviceManagerDndAction uint32

const (
	DataDeviceManagerDndActionNone DataDeviceManagerDndAction = 0
	DataDeviceManagerDndActionCopy DataDeviceManagerDndAction = 1
	DataDeviceManagerDndActionMove DataDeviceManagerDndAction = 2
	DataDeviceManagerDndActionAsk  DataDeviceManagerDndAction = 4
)

func (v DataDeviceManagerDndAction) Has(flag DataDeviceManagerDndAction) bool { return v&flag != 0 }

const (
	opReqDataDeviceManagerCreateDataSource = 0
	opReqDataDeviceManagerGetDataDevice    = 1
	opReqDataDeviceManagerRelease          = 2
)
