// Code generated by waygenerator. DO NOT EDIT.

package wlcore

import "fmt"

// DataSource: offer to transfer data
//
// The wl_data_source object is the source side of a wl_data_offer.
// It is created by the source client in a data transfer and
// provides a way to describe the offered data and a way to respond
// to requests to transfer the data.
type DataSource struct {
	ProxyBase
	listener DataSourceListener
}

var _ Proxy = (*DataSource)(nil)

func newDataSource(id, version uint32, conn *Conn) *DataSource {
	return newDataSourceFromProxyBase(NewProxyBase(id, version, conn))
}

func newDataSourceFromProxyBase(base ProxyBase) *DataSource {
	d := &DataSource{ProxyBase: base}
	d.OnClear = func() { d.listener = DataSourceListener{} }
	return d
}

// SetListener installs the handlers for wl_data_source's events, replacing
// any already installed. A nil field ignores that event; a file descriptor
// arriving in an ignored event is closed, not leaked.
func (d *DataSource) SetListener(l DataSourceListener) { d.listener = l }

// DataSourceListener holds the handlers for wl_data_source's events. Its
// zero value ignores every event. See [DataSource.SetListener].
type DataSourceListener struct {
	// Target: a target accepts an offered mime type
	//
	// Sent when a target accepts pointer_focus or motion events.  If
	// a target does not accept any of the offered types, type is NULL.
	//
	// Used for feedback during drag-and-drop.
	//
	// Parameters:
	//   - mimeType: mime type accepted by the target
	Target func(mimeType *string)
	// Send: send the data
	//
	// Request for data from the client.  Send the data as the
	// specified mime type over the passed file descriptor, then
	// close it.
	//
	// Parameters:
	//   - mimeType: mime type for the data
	//   - fd: file descriptor for the data
	Send func(mimeType string, fd int)
	// Cancelled: selection was cancelled
	//
	// This data source is no longer valid. There are several reasons why
	// this could happen:
	//
	// - The data source has been replaced by another data source.
	// - The drag-and-drop operation was performed, but the drop destination
	// did not accept any of the mime types offered through
	// wl_data_source.target.
	// - The drag-and-drop operation was performed, but the drop destination
	// did not select any of the actions present in the mask offered through
	// wl_data_source.action.
	// - The drag-and-drop operation was performed but didn't happen over a
	// surface.
	// - The compositor cancelled the drag-and-drop operation (e.g. compositor
	// dependent timeouts to avoid stale drag-and-drop transfers).
	//
	// The client should clean up and destroy this data source.
	//
	// For objects of version 2 or older, wl_data_source.cancelled will
	// only be emitted if the data source was replaced by another data
	// source.
	Cancelled func()
	// DndDropPerformed: the drag-and-drop operation physically finished
	//
	// The user performed the drop action. This event does not indicate
	// acceptance, wl_data_source.cancelled may still be emitted afterwards
	// if the drop destination does not accept any mime type.
	//
	// However, this event might however not be received if the compositor
	// cancelled the drag-and-drop operation before this event could happen.
	//
	// Note that the data_source may still be used in the future and should
	// not be destroyed here.
	DndDropPerformed func()
	// DndFinished: the drag-and-drop operation concluded
	//
	// The drop destination finished interoperating with this data
	// source, so the client is now free to destroy this data source and
	// free all associated data.
	//
	// If the action used to perform the operation was "move", the
	// source can now delete the transferred data.
	DndFinished func()
	// Action: notify the selected action
	//
	// This event indicates the action selected by the compositor after
	// matching the source/destination side actions. Only one action (or
	// none) will be offered here.
	//
	// This event can be emitted multiple times during the drag-and-drop
	// operation, mainly in response to destination side changes through
	// wl_data_offer.set_actions, and as the data device enters/leaves
	// surfaces.
	//
	// It is only possible to receive this event after
	// wl_data_source.dnd_drop_performed if the drag-and-drop operation
	// ended in an "ask" action, in which case the final wl_data_source.action
	// event will happen immediately before wl_data_source.dnd_finished.
	//
	// Compositors may also change the selected action on the fly, mainly
	// in response to keyboard modifier changes during the drag-and-drop
	// operation.
	//
	// The most recent action received is always the valid one. The chosen
	// action may change alongside negotiation (e.g. an "ask" action can turn
	// into a "move" operation), so the effects of the final action must
	// always be applied in wl_data_offer.dnd_finished.
	//
	// Clients can trigger cursor surface changes from this point, so
	// they reflect the current action.
	//
	// Parameters:
	//   - dndAction: action selected by the compositor
	Action func(dndAction DataDeviceManagerDndAction)
}

// DataSourceInterface describes wl_data_source for [Registry.Bind]: the
// name it carries on the wire and version 3, the highest this binding
// implements. Bind negotiates that against the version the compositor
// advertises, so a call site never repeats either value.
var DataSourceInterface = Interface[*DataSource]{
	Name:       "wl_data_source",
	MaxVersion: 3,
	New:        newDataSourceFromProxyBase,
}

// Offer: add an offered mime type
//
// This request adds a mime type to the set of mime types
// advertised to targets.  Can be called several times to offer
// multiple types.
//
// Parameters:
//   - mimeType: mime type offered by the data source
func (d *DataSource) Offer(mimeType string) error {
	e := NewEncoder().String(mimeType)
	return d.Conn().Send(d.ID(), opReqDataSourceOffer, e)
}

// Destroy: destroy the data source
//
// Destroy the data source.
func (d *DataSource) Destroy() error {
	err := d.Conn().Send(d.ID(), opReqDataSourceDestroy, NewEncoder())
	d.Conn().Destroy(d)
	return err
}

// SetActions: set the available drag-and-drop actions
//
// Sets the actions that the source side client supports for this
// operation. This request may trigger wl_data_source.action and
// wl_data_offer.action events if the compositor needs to change the
// selected action.
//
// The dnd_actions argument must contain only values expressed in the
// wl_data_device_manager.dnd_actions enum, otherwise it will result
// in a protocol error.
//
// This request must be made once only, and can only be made on sources
// used in drag-and-drop, so it must be performed before
// wl_data_device.start_drag. Attempting to use the source other than
// for drag-and-drop will raise a protocol error.
//
// Parameters:
//   - dndActions: actions supported by the data source
func (d *DataSource) SetActions(dndActions DataDeviceManagerDndAction) error {
	if d.Version() < 3 {
		return fmt.Errorf("wlcore: set_actions requires version >= 3, got %d", d.Version())
	}
	e := NewEncoder().Uint32(uint32(dndActions))
	return d.Conn().Send(d.ID(), opReqDataSourceSetActions, e)
}

// Dispatch decodes one wl_data_source event and calls the matching field of
// the listener. The connection calls it while pumping messages; it is
// exported only because the runtime's Proxy interface requires it.
func (d *DataSource) Dispatch(opcode uint16, dec *Decoder) error {
	switch opcode {
	case opEvtDataSourceTarget:
		mimeType := dec.StringOpt()
		if err := dec.Err(); err != nil {
			return err
		}
		if d.listener.Target != nil {
			d.listener.Target(mimeType)
		}
	case opEvtDataSourceSend:
		mimeType := dec.String()
		fd := dec.FD()
		if err := dec.Err(); err != nil {
			DropFD(fd)
			return err
		}
		if d.listener.Send == nil {
			DropFD(fd)
			break
		}
		d.listener.Send(mimeType, fd)
	case opEvtDataSourceCancelled:
		if err := dec.Err(); err != nil {
			return err
		}
		if d.listener.Cancelled != nil {
			d.listener.Cancelled()
		}
	case opEvtDataSourceDndDropPerformed:
		if err := dec.Err(); err != nil {
			return err
		}
		if d.listener.DndDropPerformed != nil {
			d.listener.DndDropPerformed()
		}
	case opEvtDataSourceDndFinished:
		if err := dec.Err(); err != nil {
			return err
		}
		if d.listener.DndFinished != nil {
			d.listener.DndFinished()
		}
	case opEvtDataSourceAction:
		dndAction := DataDeviceManagerDndAction(dec.Uint32())
		if err := dec.Err(); err != nil {
			return err
		}
		if d.listener.Action != nil {
			d.listener.Action(dndAction)
		}
	default:
		return fmt.Errorf("wlcore: unknown opcode %d in wl_data_source", opcode)
	}
	return nil
}

// DataSourceError enumerates the protocol errors wl_data_source can raise.
// The compositor reports one through wl_display.error.
type DataSourceError uint32

const (
	DataSourceErrorInvalidActionMask DataSourceError = 0 // action mask contains invalid values
	DataSourceErrorInvalidSource     DataSourceError = 1 // source doesn't accept this request
)

const (
	opReqDataSourceOffer            = 0
	opReqDataSourceDestroy          = 1
	opReqDataSourceSetActions       = 2
	opEvtDataSourceTarget           = 0
	opEvtDataSourceSend             = 1
	opEvtDataSourceCancelled        = 2
	opEvtDataSourceDndDropPerformed = 3
	opEvtDataSourceDndFinished      = 4
	opEvtDataSourceAction           = 5
)
