// Code generated by waygenerator. DO NOT EDIT.

package wlcore

import "fmt"

type DataDevice struct {
	ProxyBase
	listener DataDeviceListener
}

var _ Proxy = (*DataDevice)(nil)

func newDataDevice(id, version uint32, conn *Conn) *DataDevice {
	d := &DataDevice{ProxyBase: NewProxyBase(id, version, conn)}
	d.OnClear = func() { d.listener = DataDeviceListener{} }
	return d
}

func (d *DataDevice) SetListener(l DataDeviceListener) { d.listener = l }

type DataDeviceListener struct {
	DataOffer func(id *DataOffer)
	Enter     func(serial uint32, surface *Surface, x Fixed, y Fixed, id *DataOffer)
	Leave     func()
	Motion    func(time uint32, x Fixed, y Fixed)
	Drop      func()
	Selection func(id *DataOffer)
}

var DataDeviceInterface = Interface[*DataDevice]{
	Name:       "wl_data_device",
	MaxVersion: 4,
	New:        func(b ProxyBase) *DataDevice { return &DataDevice{ProxyBase: b} },
}

func (d *DataDevice) StartDrag(source *DataSource, origin *Surface, icon *Surface, serial uint32) error {
	e := NewEncoder().ID(source.ID()).ID(origin.ID()).ID(icon.ID()).Uint32(serial)
	return d.Conn().Send(d.ID(), opReqDataDeviceStartDrag, e)
}

func (d *DataDevice) SetSelection(source *DataSource, serial uint32) error {
	e := NewEncoder().ID(source.ID()).Uint32(serial)
	return d.Conn().Send(d.ID(), opReqDataDeviceSetSelection, e)
}

func (d *DataDevice) Release() error {
	err := d.Conn().Send(d.ID(), opReqDataDeviceRelease, NewEncoder())
	d.Conn().destroy(d)
	return err
}

func (d *DataDevice) Dispatch(opcode uint16, dec *Decoder) error {
	switch opcode {
	case opEvtDataDeviceDataOffer:
		idID := dec.ID()
		if err := dec.Err(); err != nil {
			return err
		}
		id := DataOfferInterface.New(NewProxyBase(idID, d.Version(), d.Conn()))
		d.Conn().Register(id)
		if d.listener.DataOffer != nil {
			d.listener.DataOffer(id)
		}
	case opEvtDataDeviceEnter:
		serial := dec.Uint32()
		surfaceID := dec.ID()
		x := dec.Fixed()
		y := dec.Fixed()
		idID := dec.ID()
		if err := dec.Err(); err != nil {
			return err
		}
		surface, _ := d.Conn().Lookup(surfaceID).(*Surface)
		id, _ := d.Conn().Lookup(idID).(*DataOffer)
		if d.listener.Enter != nil {
			d.listener.Enter(serial, surface, x, y, id)
		}
	case opEvtDataDeviceLeave:
		if err := dec.Err(); err != nil {
			return err
		}
		if d.listener.Leave != nil {
			d.listener.Leave()
		}
	case opEvtDataDeviceMotion:
		time := dec.Uint32()
		x := dec.Fixed()
		y := dec.Fixed()
		if err := dec.Err(); err != nil {
			return err
		}
		if d.listener.Motion != nil {
			d.listener.Motion(time, x, y)
		}
	case opEvtDataDeviceDrop:
		if err := dec.Err(); err != nil {
			return err
		}
		if d.listener.Drop != nil {
			d.listener.Drop()
		}
	case opEvtDataDeviceSelection:
		idID := dec.ID()
		if err := dec.Err(); err != nil {
			return err
		}
		id, _ := d.Conn().Lookup(idID).(*DataOffer)
		if d.listener.Selection != nil {
			d.listener.Selection(id)
		}
	default:
		return fmt.Errorf("wlcore: opcode %d desconocido en wl_data_device", opcode)
	}
	return nil
}

type DataDeviceError uint32

const (
	DataDeviceErrorRole       DataDeviceError = 0
	DataDeviceErrorUsedSource DataDeviceError = 1
)

const (
	opReqDataDeviceStartDrag    = 0
	opReqDataDeviceSetSelection = 1
	opReqDataDeviceRelease      = 2
	opEvtDataDeviceDataOffer    = 0
	opEvtDataDeviceEnter        = 1
	opEvtDataDeviceLeave        = 2
	opEvtDataDeviceMotion       = 3
	opEvtDataDeviceDrop         = 4
	opEvtDataDeviceSelection    = 5
)
