// Code generated by waygenerator. DO NOT EDIT.

package wlcore

import "fmt"

// Display: core global object
//
// The core global object.  This is a special singleton object.  It
// is used for internal Wayland protocol features.
type Display struct {
	ProxyBase
	listener DisplayListener
}

var _ Proxy = (*Display)(nil)

func newDisplay(id, version uint32, conn *Conn) *Display {
	return newDisplayFromProxyBase(NewProxyBase(id, version, conn))
}

func newDisplayFromProxyBase(base ProxyBase) *Display {
	d := &Display{ProxyBase: base}
	d.OnClear = func() { d.listener = DisplayListener{} }
	return d
}

type DisplayListener struct {
	// Error: fatal error event
	//
	// The error event is sent out when a fatal (non-recoverable)
	// error has occurred.  The object_id argument is the object
	// where the error occurred, most often in response to a request
	// to that object.  The code identifies the error and is defined
	// by the object interface.  As such, each interface defines its
	// own set of error codes.  The message is a brief description
	// of the error, for (debugging) convenience.
	//
	// Parameters:
	//   - objectID: object where the error occurred
	//   - code: error code
	//   - message: error description
	Error func(objectID uint32, code uint32, message string)
	// DeleteID: acknowledge object ID deletion
	//
	// This event is used internally by the object ID management logic.
	//
	// When the server stops using an object created by the client, the server
	// sends this event. In particular, after sending this event, the server
	// will no longer send any events that contain the object as the receiver
	// or as an argument.
	//
	// When the client receives this event, it knows that it can reuse the
	// object ID.
	//
	// Parameters:
	//   - id: deleted object ID
	DeleteID func(id uint32)
}

var DisplayInterface = Interface[*Display]{
	Name:       "wl_display",
	MaxVersion: 1,
	New:        newDisplayFromProxyBase,
}

// Sync: asynchronous roundtrip
//
// The sync request asks the server to emit the 'done' event
// on the returned wl_callback object.  Since requests are
// handled in-order and events are delivered in-order, this can
// be used as a barrier to ensure all previous requests and the
// resulting events have been handled.
//
// The object returned by this request will be destroyed by the
// compositor after the callback is fired and as such the client must not
// attempt to use it after that point.
//
// The callback_data passed in the callback is undefined and should be ignored.
func (d *Display) Sync() (*Callback, error) {
	id := d.Conn().NewID()
	x := newCallbackFromProxyBase(NewProxyBase(id, d.Version(), d.Conn()))
	d.Conn().Register(x)

	e := NewEncoder().ID(id)
	if err := d.Conn().Send(d.ID(), opReqDisplaySync, e); err != nil {
		return nil, err
	}
	return x, nil
}

// GetRegistry: get global registry object
//
// This request creates a registry object that allows the client
// to list and bind the global objects available from the
// compositor.
//
// It should be noted that the server side resources consumed in
// response to a get_registry request can only be released when the
// client disconnects, not when the client side proxy is destroyed.
// Therefore, clients should invoke get_registry as infrequently as
// possible to avoid wasting memory.
func (d *Display) GetRegistry() (*Registry, error) {
	id := d.Conn().NewID()
	x := newRegistryFromProxyBase(NewProxyBase(id, d.Version(), d.Conn()))
	d.Conn().Register(x)

	e := NewEncoder().ID(id)
	if err := d.Conn().Send(d.ID(), opReqDisplayGetRegistry, e); err != nil {
		return nil, err
	}
	return x, nil
}

func (d *Display) Dispatch(opcode uint16, dec *Decoder) error {
	switch opcode {
	case opEvtDisplayError:
		objectID := dec.Uint32()
		code := dec.Uint32()
		message := dec.String()
		if err := dec.Err(); err != nil {
			return err
		}
		if d.listener.Error != nil {
			d.listener.Error(objectID, code, message)
		}
	case opEvtDisplayDeleteID:
		id := dec.Uint32()
		if err := dec.Err(); err != nil {
			return err
		}
		if d.listener.DeleteID != nil {
			d.listener.DeleteID(id)
		}
	default:
		return fmt.Errorf("wlcore: opcode %d desconocido en wl_display", opcode)
	}
	return nil
}

// DisplayError: global error values
//
// These errors are global and can be emitted in response to any
// server request.
type DisplayError uint32

const (
	DisplayErrorInvalidObject  DisplayError = 0 // server couldn't find object
	DisplayErrorInvalidMethod  DisplayError = 1 // method doesn't exist on the specified interface or malformed request
	DisplayErrorNoMemory       DisplayError = 2 // server is out of memory
	DisplayErrorImplementation DisplayError = 3 // implementation error in compositor
)

const (
	opReqDisplaySync        = 0
	opReqDisplayGetRegistry = 1
	opEvtDisplayError       = 0
	opEvtDisplayDeleteID    = 1
)
