// Code generated by waygenerator. DO NOT EDIT.

package wlcore

import "fmt"

// Fixes: wayland protocol fixes
//
// This global fixes problems with other core-protocol interfaces that
// cannot be fixed in these interfaces themselves.
type Fixes struct {
	ProxyBase
	listener FixesListener
}

var _ Proxy = (*Fixes)(nil)

func newFixes(id, version uint32, conn *Conn) *Fixes {
	return newFixesFromProxyBase(NewProxyBase(id, version, conn))
}

func newFixesFromProxyBase(base ProxyBase) *Fixes {
	f := &Fixes{ProxyBase: base}
	return f
}

func (f *Fixes) SetListener(l FixesListener) { f.listener = l }

type FixesListener struct {
}

var FixesInterface = Interface[*Fixes]{
	Name:       "wl_fixes",
	MaxVersion: 1,
	New:        newFixesFromProxyBase,
}

// Destroy: destroys this object
func (f *Fixes) Destroy() error {
	err := f.Conn().Send(f.ID(), opReqFixesDestroy, NewEncoder())
	f.Conn().Destroy(f)
	return err
}

// DestroyRegistry: destroy a wl_registry
//
// This request destroys a wl_registry object.
//
// The client should no longer use the wl_registry after making this
// request.
//
// The compositor will emit a wl_display.delete_id event with the object ID
// of the registry and will no longer emit any events on the registry. The
// client should re-use the object ID once it receives the
// wl_display.delete_id event.
//
// Parameters:
//   - registry: the registry to destroy
func (f *Fixes) DestroyRegistry(registry *Registry) error {
	e := NewEncoder().ID(registry.ID())
	return f.Conn().Send(f.ID(), opReqFixesDestroyRegistry, e)
}

func (f *Fixes) Dispatch(opcode uint16, dec *Decoder) error {
	switch opcode {
	default:
		return fmt.Errorf("wlcore: unknown opcode %d in wl_fixes", opcode)
	}
}

const (
	opReqFixesDestroy         = 0
	opReqFixesDestroyRegistry = 1
)
