// Code generated by waygenerator. DO NOT EDIT.

package wlcore

import "fmt"

// Fixes: wayland protocol fixes
//
// This global fixes problems with other core-protocol interfaces that
// cannot be fixed in these interfaces themselves.
type Fixes struct {
	ProxyBase
	listener FixesListener
}

var _ Proxy = (*Fixes)(nil)

func newFixes(id, version uint32, conn *Conn) *Fixes {
	return newFixesFromProxyBase(NewProxyBase(id, version, conn))
}

func newFixesFromProxyBase(base ProxyBase) *Fixes {
	f := &Fixes{ProxyBase: base}
	return f
}

// SetListener installs the handlers for wl_fixes's events, replacing any
// already installed. A nil field ignores that event; a file descriptor
// arriving in an ignored event is closed, not leaked.
func (f *Fixes) SetListener(l FixesListener) { f.listener = l }

// FixesListener holds the handlers for wl_fixes's events. Its zero value
// ignores every event. See [Fixes.SetListener].
type FixesListener struct {
}

// FixesInterface describes wl_fixes for [Registry.Bind]: the name it
// carries on the wire and version 1, the highest this binding implements.
// Bind negotiates that against the version the compositor advertises, so a
// call site never repeats either value.
var FixesInterface = Interface[*Fixes]{
	Name:       "wl_fixes",
	MaxVersion: 1,
	New:        newFixesFromProxyBase,
}

// Destroy: destroys this object
func (f *Fixes) Destroy() error {
	err := f.Conn().Send(f.ID(), opReqFixesDestroy, NewEncoder())
	f.Conn().Destroy(f)
	return err
}

// DestroyRegistry: destroy a wl_registry
//
// This request destroys a wl_registry object.
//
// The client should no longer use the wl_registry after making this
// request.
//
// The compositor will emit a wl_display.delete_id event with the object ID
// of the registry and will no longer emit any events on the registry. The
// client should re-use the object ID once it receives the
// wl_display.delete_id event.
//
// Parameters:
//   - registry: the registry to destroy
func (f *Fixes) DestroyRegistry(registry *Registry) error {
	e := NewEncoder().ID(registry.ID())
	return f.Conn().Send(f.ID(), opReqFixesDestroyRegistry, e)
}

// Dispatch decodes one wl_fixes event and calls the matching field of the
// listener. The connection calls it while pumping messages; it is exported
// only because the runtime's Proxy interface requires it.
func (f *Fixes) Dispatch(opcode uint16, dec *Decoder) error {
	switch opcode {
	default:
		return fmt.Errorf("wlcore: unknown opcode %d in wl_fixes", opcode)
	}
}

const (
	opReqFixesDestroy         = 0
	opReqFixesDestroyRegistry = 1
)
