// Code generated by waygenerator. DO NOT EDIT.

package wlcore

import "fmt"

type Keyboard struct {
	ProxyBase
	listener KeyboardListener
}

var _ Proxy = (*Keyboard)(nil)

func newKeyboard(id, version uint32, conn *Conn) *Keyboard {
	return newKeyboardFromProxyBase(NewProxyBase(id, version, conn))
}

func newKeyboardFromProxyBase(base ProxyBase) *Keyboard {
	k := &Keyboard{ProxyBase: base}
	k.OnClear = func() { k.listener = KeyboardListener{} }
	return k
}

func (k *Keyboard) SetListener(l KeyboardListener) { k.listener = l }

type KeyboardListener struct {
	Keymap     func(format KeyboardKeymapFormat, fd int, size uint32)
	Enter      func(serial uint32, surface *Surface, keys []byte)
	Leave      func(serial uint32, surface *Surface)
	Key        func(serial uint32, time uint32, key uint32, state KeyboardKeyState)
	Modifiers  func(serial uint32, modsDepressed uint32, modsLatched uint32, modsLocked uint32, group uint32)
	RepeatInfo func(rate int32, delay int32)
}

var KeyboardInterface = Interface[*Keyboard]{
	Name:       "wl_keyboard",
	MaxVersion: 11,
	New:        newKeyboardFromProxyBase,
}

func (k *Keyboard) Release() error {
	if k.Version() < 3 {
		return fmt.Errorf("wlcore: release requiere versión >= 3, hay %d", k.Version())
	}
	err := k.Conn().Send(k.ID(), opReqKeyboardRelease, NewEncoder())
	k.Conn().destroy(k)
	return err
}

func (k *Keyboard) Dispatch(opcode uint16, dec *Decoder) error {
	switch opcode {
	case opEvtKeyboardKeymap:
		format := KeyboardKeymapFormat(dec.Uint32())
		fd := dec.FD()
		size := dec.Uint32()
		if err := dec.Err(); err != nil {
			DropFD(fd)
			return err
		}
		if k.listener.Keymap == nil {
			DropFD(fd)
			break
		}
		k.listener.Keymap(format, fd, size)
	case opEvtKeyboardEnter:
		serial := dec.Uint32()
		surfaceID := dec.ID()
		keys := dec.Array()
		if err := dec.Err(); err != nil {
			return err
		}
		surface, _ := k.Conn().Lookup(surfaceID).(*Surface)
		if k.listener.Enter != nil {
			k.listener.Enter(serial, surface, keys)
		}
	case opEvtKeyboardLeave:
		serial := dec.Uint32()
		surfaceID := dec.ID()
		if err := dec.Err(); err != nil {
			return err
		}
		surface, _ := k.Conn().Lookup(surfaceID).(*Surface)
		if k.listener.Leave != nil {
			k.listener.Leave(serial, surface)
		}
	case opEvtKeyboardKey:
		serial := dec.Uint32()
		time := dec.Uint32()
		key := dec.Uint32()
		state := KeyboardKeyState(dec.Uint32())
		if err := dec.Err(); err != nil {
			return err
		}
		if k.listener.Key != nil {
			k.listener.Key(serial, time, key, state)
		}
	case opEvtKeyboardModifiers:
		serial := dec.Uint32()
		modsDepressed := dec.Uint32()
		modsLatched := dec.Uint32()
		modsLocked := dec.Uint32()
		group := dec.Uint32()
		if err := dec.Err(); err != nil {
			return err
		}
		if k.listener.Modifiers != nil {
			k.listener.Modifiers(serial, modsDepressed, modsLatched, modsLocked, group)
		}
	case opEvtKeyboardRepeatInfo:
		rate := dec.Int32()
		delay := dec.Int32()
		if err := dec.Err(); err != nil {
			return err
		}
		if k.listener.RepeatInfo != nil {
			k.listener.RepeatInfo(rate, delay)
		}
	default:
		return fmt.Errorf("wlcore: opcode %d desconocido en wl_keyboard", opcode)
	}
	return nil
}

type KeyboardKeymapFormat uint32

const (
	KeyboardKeymapFormatNoKeymap KeyboardKeymapFormat = 0
	KeyboardKeymapFormatXkbV1    KeyboardKeymapFormat = 1
)

type KeyboardKeyState uint32

const (
	KeyboardKeyStateReleased KeyboardKeyState = 0
	KeyboardKeyStatePressed  KeyboardKeyState = 1
	KeyboardKeyStateRepeated KeyboardKeyState = 2
)

const (
	opReqKeyboardRelease    = 0
	opEvtKeyboardKeymap     = 0
	opEvtKeyboardEnter      = 1
	opEvtKeyboardLeave      = 2
	opEvtKeyboardKey        = 3
	opEvtKeyboardModifiers  = 4
	opEvtKeyboardRepeatInfo = 5
)
