// Code generated by waygenerator. DO NOT EDIT.

package wlcore

import "fmt"

// Output: compositor output region
//
// An output describes part of the compositor geometry.  The
// compositor works in the 'compositor coordinate system' and an
// output corresponds to a rectangular area in that space that is
// actually visible.  This typically corresponds to a monitor that
// displays part of the compositor space.  This object is published
// as global during start up, or when a monitor is hotplugged.
type Output struct {
	ProxyBase
	listener OutputListener
}

var _ Proxy = (*Output)(nil)

func newOutput(id, version uint32, conn *Conn) *Output {
	return newOutputFromProxyBase(NewProxyBase(id, version, conn))
}

func newOutputFromProxyBase(base ProxyBase) *Output {
	o := &Output{ProxyBase: base}
	o.OnClear = func() { o.listener = OutputListener{} }
	return o
}

// SetListener installs the handlers for wl_output's events, replacing any
// already installed. A nil field ignores that event; a file descriptor
// arriving in an ignored event is closed, not leaked.
func (o *Output) SetListener(l OutputListener) { o.listener = l }

// OutputListener holds the handlers for wl_output's events. Its zero value
// ignores every event. See [Output.SetListener].
type OutputListener struct {
	// Geometry: properties of the output
	//
	// The geometry event describes geometric properties of the output.
	// The event is sent when binding to the output object and whenever
	// any of the properties change.
	//
	// The physical size can be set to zero if it doesn't make sense for this
	// output (e.g. for projectors or virtual outputs).
	//
	// The geometry event will be followed by a done event (starting from
	// version 2).
	//
	// Clients should use wl_surface.preferred_buffer_transform instead of the
	// transform advertised by this event to find the preferred buffer
	// transform to use for a surface.
	//
	// Note: wl_output only advertises partial information about the output
	// position and identification. Some compositors, for instance those not
	// implementing a desktop-style output layout or those exposing virtual
	// outputs, might fake this information. Instead of using x and y, clients
	// should use xdg_output.logical_position. Instead of using make and model,
	// clients should use name and description.
	//
	// Parameters:
	//   - x: x position within the global compositor space
	//   - y: y position within the global compositor space
	//   - physicalWidth: width in millimeters of the output
	//   - physicalHeight: height in millimeters of the output
	//   - subpixel: subpixel orientation of the output
	//   - make: textual description of the manufacturer
	//   - model: textual description of the model
	//   - transform: additional transformation applied to buffer contents during presentation
	Geometry func(x int32, y int32, physicalWidth int32, physicalHeight int32, subpixel OutputSubpixel, make string, model string, transform OutputTransform)
	// Mode: advertise available modes for the output
	//
	// The mode event describes an available mode for the output.
	//
	// The event is sent when binding to the output object and there
	// will always be one mode, the current mode.  The event is sent
	// again if an output changes mode, for the mode that is now
	// current.  In other words, the current mode is always the last
	// mode that was received with the current flag set.
	//
	// Non-current modes are deprecated. A compositor can decide to only
	// advertise the current mode and never send other modes. Clients
	// should not rely on non-current modes.
	//
	// The size of a mode is given in physical hardware units of
	// the output device. This is not necessarily the same as
	// the output size in the global compositor space. For instance,
	// the output may be scaled, as described in wl_output.scale,
	// or transformed, as described in wl_output.transform. Clients
	// willing to retrieve the output size in the global compositor
	// space should use xdg_output.logical_size instead.
	//
	// The vertical refresh rate can be set to zero if it doesn't make
	// sense for this output (e.g. for virtual outputs).
	//
	// The mode event will be followed by a done event (starting from
	// version 2).
	//
	// Clients should not use the refresh rate to schedule frames. Instead,
	// they should use the wl_surface.frame event or the presentation-time
	// protocol.
	//
	// Note: this information is not always meaningful for all outputs. Some
	// compositors, such as those exposing virtual outputs, might fake the
	// refresh rate or the size.
	//
	// Parameters:
	//   - flags: bitfield of mode flags
	//   - width: width of the mode in hardware units
	//   - height: height of the mode in hardware units
	//   - refresh: vertical refresh rate in mHz
	Mode func(flags OutputMode, width int32, height int32, refresh int32)
	// Done: sent all information about output
	//
	// This event is sent after all other properties have been
	// sent after binding to the output object and after any
	// other property changes done after that. This allows
	// changes to the output properties to be seen as
	// atomic, even if they happen via multiple events.
	Done func()
	// Scale: output scaling properties
	//
	// This event contains scaling geometry information
	// that is not in the geometry event. It may be sent after
	// binding the output object or if the output scale changes
	// later. The compositor will emit a non-zero, positive
	// value for scale. If it is not sent, the client should
	// assume a scale of 1.
	//
	// A scale larger than 1 means that the compositor will
	// automatically scale surface buffers by this amount
	// when rendering. This is used for very high resolution
	// displays where applications rendering at the native
	// resolution would be too small to be legible.
	//
	// Clients should use wl_surface.preferred_buffer_scale
	// instead of this event to find the preferred buffer
	// scale to use for a surface.
	//
	// The scale event will be followed by a done event.
	//
	// Parameters:
	//   - factor: scaling factor of output
	Scale func(factor int32)
	// Name: name of this output
	//
	// Many compositors will assign user-friendly names to their outputs, show
	// them to the user, allow the user to refer to an output, etc. The client
	// may wish to know this name as well to offer the user similar behaviors.
	//
	// The name is a UTF-8 string with no convention defined for its contents.
	// Each name is unique among all wl_output globals. The name is only
	// guaranteed to be unique for the compositor instance.
	//
	// The same output name is used for all clients for a given wl_output
	// global. Thus, the name can be shared across processes to refer to a
	// specific wl_output global.
	//
	// The name is not guaranteed to be persistent across sessions, thus cannot
	// be used to reliably identify an output in e.g. configuration files.
	//
	// Examples of names include 'HDMI-A-1', 'WL-1', 'X11-1', etc. However, do
	// not assume that the name is a reflection of an underlying DRM connector,
	// X11 connection, etc.
	//
	// The name event is sent after binding the output object. This event is
	// only sent once per output object, and the name does not change over the
	// lifetime of the wl_output global.
	//
	// Compositors may re-use the same output name if the wl_output global is
	// destroyed and re-created later. Compositors should avoid re-using the
	// same name if possible.
	//
	// The name event will be followed by a done event.
	//
	// Parameters:
	//   - name: output name
	Name func(name string)
	// Description: human-readable description of this output
	//
	// Many compositors can produce human-readable descriptions of their
	// outputs. The client may wish to know this description as well, e.g. for
	// output selection purposes.
	//
	// The description is a UTF-8 string with no convention defined for its
	// contents. The description is not guaranteed to be unique among all
	// wl_output globals. Examples might include 'Foocorp 11" Display' or
	// 'Virtual X11 output via :1'.
	//
	// The description event is sent after binding the output object and
	// whenever the description changes. The description is optional, and may
	// not be sent at all.
	//
	// The description event will be followed by a done event.
	//
	// Parameters:
	//   - description: output description
	Description func(description string)
}

// OutputInterface describes wl_output for [Registry.Bind]: the name it
// carries on the wire and version 4, the highest this binding implements.
// Bind negotiates that against the version the compositor advertises, so a
// call site never repeats either value.
var OutputInterface = Interface[*Output]{
	Name:       "wl_output",
	MaxVersion: 4,
	New:        newOutputFromProxyBase,
}

// Release: release the output object
//
// Using this request a client can tell the server that it is not going to
// use the output object anymore.
func (o *Output) Release() error {
	if o.Version() < 3 {
		return fmt.Errorf("wlcore: release requires version >= 3, got %d", o.Version())
	}
	err := o.Conn().Send(o.ID(), opReqOutputRelease, NewEncoder())
	o.Conn().Destroy(o)
	return err
}

// Dispatch decodes one wl_output event and calls the matching field of the
// listener. The connection calls it while pumping messages; it is exported
// only because the runtime's Proxy interface requires it.
func (o *Output) Dispatch(opcode uint16, dec *Decoder) error {
	switch opcode {
	case opEvtOutputGeometry:
		x := dec.Int32()
		y := dec.Int32()
		physicalWidth := dec.Int32()
		physicalHeight := dec.Int32()
		subpixel := OutputSubpixel(dec.Uint32())
		make := dec.String()
		model := dec.String()
		transform := OutputTransform(dec.Uint32())
		if err := dec.Err(); err != nil {
			return err
		}
		if o.listener.Geometry != nil {
			o.listener.Geometry(x, y, physicalWidth, physicalHeight, subpixel, make, model, transform)
		}
	case opEvtOutputMode:
		flags := OutputMode(dec.Uint32())
		width := dec.Int32()
		height := dec.Int32()
		refresh := dec.Int32()
		if err := dec.Err(); err != nil {
			return err
		}
		if o.listener.Mode != nil {
			o.listener.Mode(flags, width, height, refresh)
		}
	case opEvtOutputDone:
		if err := dec.Err(); err != nil {
			return err
		}
		if o.listener.Done != nil {
			o.listener.Done()
		}
	case opEvtOutputScale:
		factor := dec.Int32()
		if err := dec.Err(); err != nil {
			return err
		}
		if o.listener.Scale != nil {
			o.listener.Scale(factor)
		}
	case opEvtOutputName:
		name := dec.String()
		if err := dec.Err(); err != nil {
			return err
		}
		if o.listener.Name != nil {
			o.listener.Name(name)
		}
	case opEvtOutputDescription:
		description := dec.String()
		if err := dec.Err(); err != nil {
			return err
		}
		if o.listener.Description != nil {
			o.listener.Description(description)
		}
	default:
		return fmt.Errorf("wlcore: unknown opcode %d in wl_output", opcode)
	}
	return nil
}

// OutputSubpixel: subpixel geometry information
//
// This enumeration describes how the physical
// pixels on an output are laid out.
type OutputSubpixel uint32

const (
	OutputSubpixelUnknown       OutputSubpixel = 0 // unknown geometry
	OutputSubpixelNone          OutputSubpixel = 1 // no geometry
	OutputSubpixelHorizontalRgb OutputSubpixel = 2 // horizontal RGB
	OutputSubpixelHorizontalBgr OutputSubpixel = 3 // horizontal BGR
	OutputSubpixelVerticalRgb   OutputSubpixel = 4 // vertical RGB
	OutputSubpixelVerticalBgr   OutputSubpixel = 5 // vertical BGR
)

// OutputTransform: transformation applied to buffer contents
//
// This describes transformations that clients and compositors apply to
// buffer contents.
//
// The flipped values correspond to an initial flip around a
// vertical axis followed by rotation.
//
// The purpose is mainly to allow clients to render accordingly and
// tell the compositor, so that for fullscreen surfaces, the
// compositor will still be able to scan out directly from client
// surfaces.
type OutputTransform uint32

const (
	OutputTransformNormal     OutputTransform = 0 // no transform
	OutputTransform90         OutputTransform = 1 // 90 degrees counter-clockwise
	OutputTransform180        OutputTransform = 2 // 180 degrees counter-clockwise
	OutputTransform270        OutputTransform = 3 // 270 degrees counter-clockwise
	OutputTransformFlipped    OutputTransform = 4 // 180 degree flip around a vertical axis
	OutputTransformFlipped90  OutputTransform = 5 // flip and rotate 90 degrees counter-clockwise
	OutputTransformFlipped180 OutputTransform = 6 // flip and rotate 180 degrees counter-clockwise
	OutputTransformFlipped270 OutputTransform = 7 // flip and rotate 270 degrees counter-clockwise
)

// OutputMode: mode information
//
// These flags describe properties of an output mode.
// They are used in the flags bitfield of the mode event.
type OutputMode uint32

const (
	OutputModeCurrent   OutputMode = 0x1 // indicates this is the current mode
	OutputModePreferred OutputMode = 0x2 // indicates this is the preferred mode
)

// Has reports whether v has any bit of flag set. With a flag holding a
// single bit -- the usual case -- that is the membership test.
func (v OutputMode) Has(flag OutputMode) bool { return v&flag != 0 }

const (
	opReqOutputRelease     = 0
	opEvtOutputGeometry    = 0
	opEvtOutputMode        = 1
	opEvtOutputDone        = 2
	opEvtOutputScale       = 3
	opEvtOutputName        = 4
	opEvtOutputDescription = 5
)
