// Code generated by waygenerator. DO NOT EDIT.

package wlcore

import "fmt"

type Output struct {
	ProxyBase
	listener OutputListener
}

var _ Proxy = (*Output)(nil)

func newOutput(id, version uint32, conn *Conn) *Output {
	o := &Output{ProxyBase: NewProxyBase(id, version, conn)}
	o.OnClear = func() { o.listener = OutputListener{} }
	return o
}

func (o *Output) SetListener(l OutputListener) { o.listener = l }

type OutputListener struct {
	Geometry    func(x int32, y int32, physicalWidth int32, physicalHeight int32, subpixel int32, make string, model string, transform int32)
	Mode        func(flags OutputMode, width int32, height int32, refresh int32)
	Done        func()
	Scale       func(factor int32)
	Name        func(name string)
	Description func(description string)
}

var OutputInterface = Interface[*Output]{
	Name:       "wl_output",
	MaxVersion: 4,
	New:        func(b ProxyBase) *Output { return &Output{ProxyBase: b} },
}

func (o *Output) Release() error {
	err := o.Conn().Send(o.ID(), opReqOutputRelease, NewEncoder())
	o.Conn().destroy(o)
	return err
}

func (o *Output) Dispatch(opcode uint16, dec *Decoder) error {
	switch opcode {
	case opEvtOutputGeometry:
		x := dec.Int32()
		y := dec.Int32()
		physicalWidth := dec.Int32()
		physicalHeight := dec.Int32()
		subpixel := dec.Int32()
		make := dec.String()
		model := dec.String()
		transform := dec.Int32()
		if err := dec.Err(); err != nil {
			return err
		}
		if o.listener.Geometry != nil {
			o.listener.Geometry(x, y, physicalWidth, physicalHeight, subpixel, make, model, transform)
		}
	case opEvtOutputMode:
		flags := OutputMode(dec.Uint32())
		width := dec.Int32()
		height := dec.Int32()
		refresh := dec.Int32()
		if err := dec.Err(); err != nil {
			return err
		}
		if o.listener.Mode != nil {
			o.listener.Mode(flags, width, height, refresh)
		}
	case opEvtOutputDone:
		if err := dec.Err(); err != nil {
			return err
		}
		if o.listener.Done != nil {
			o.listener.Done()
		}
	case opEvtOutputScale:
		factor := dec.Int32()
		if err := dec.Err(); err != nil {
			return err
		}
		if o.listener.Scale != nil {
			o.listener.Scale(factor)
		}
	case opEvtOutputName:
		name := dec.String()
		if err := dec.Err(); err != nil {
			return err
		}
		if o.listener.Name != nil {
			o.listener.Name(name)
		}
	case opEvtOutputDescription:
		description := dec.String()
		if err := dec.Err(); err != nil {
			return err
		}
		if o.listener.Description != nil {
			o.listener.Description(description)
		}
	default:
		return fmt.Errorf("wlcore: opcode %d desconocido en wl_output", opcode)
	}
	return nil
}

type OutputSubpixel uint32

const (
	OutputSubpixelUnknown       OutputSubpixel = 0
	OutputSubpixelNone          OutputSubpixel = 1
	OutputSubpixelHorizontalRgb OutputSubpixel = 2
	OutputSubpixelHorizontalBgr OutputSubpixel = 3
	OutputSubpixelVerticalRgb   OutputSubpixel = 4
	OutputSubpixelVerticalBgr   OutputSubpixel = 5
)

type OutputTransform uint32

const (
	OutputTransformNormal     OutputTransform = 0
	OutputTransform90         OutputTransform = 1
	OutputTransform180        OutputTransform = 2
	OutputTransform270        OutputTransform = 3
	OutputTransformFlipped    OutputTransform = 4
	OutputTransformFlipped90  OutputTransform = 5
	OutputTransformFlipped180 OutputTransform = 6
	OutputTransformFlipped270 OutputTransform = 7
)

type OutputMode uint32

const (
	OutputModeCurrent   OutputMode = 0x1
	OutputModePreferred OutputMode = 0x2
)

func (v OutputMode) Has(flag OutputMode) bool { return v&flag != 0 }

const (
	opReqOutputRelease     = 0
	opEvtOutputGeometry    = 0
	opEvtOutputMode        = 1
	opEvtOutputDone        = 2
	opEvtOutputScale       = 3
	opEvtOutputName        = 4
	opEvtOutputDescription = 5
)
