// Code generated by waygenerator. DO NOT EDIT.

package wlcore

import "fmt"

type Pointer struct {
	ProxyBase
	listener PointerListener
}

var _ Proxy = (*Pointer)(nil)

func newPointer(id, version uint32, conn *Conn) *Pointer {
	return newPointerFromProxyBase(NewProxyBase(id, version, conn))
}

func newPointerFromProxyBase(base ProxyBase) *Pointer {
	p := &Pointer{ProxyBase: base}
	p.OnClear = func() { p.listener = PointerListener{} }
	return p
}

func (p *Pointer) SetListener(l PointerListener) { p.listener = l }

type PointerListener struct {
	Enter                 func(serial uint32, surface *Surface, surfaceX Fixed, surfaceY Fixed)
	Leave                 func(serial uint32, surface *Surface)
	Motion                func(time uint32, surfaceX Fixed, surfaceY Fixed)
	Button                func(serial uint32, time uint32, button uint32, state PointerButtonState)
	Axis                  func(time uint32, axis PointerAxis, value Fixed)
	Frame                 func()
	AxisSource            func(axisSource PointerAxisSource)
	AxisStop              func(time uint32, axis PointerAxis)
	AxisDiscrete          func(axis PointerAxis, discrete int32)
	AxisValue120          func(axis PointerAxis, value120 int32)
	AxisRelativeDirection func(axis PointerAxis, direction PointerAxisRelativeDirection)
	Warp                  func(surfaceX Fixed, surfaceY Fixed)
}

var PointerInterface = Interface[*Pointer]{
	Name:       "wl_pointer",
	MaxVersion: 11,
	New:        newPointerFromProxyBase,
}

func (p *Pointer) SetCursor(serial uint32, surface *Surface, hotspotX int32, hotspotY int32) error {
	e := NewEncoder().Uint32(serial).ID(surface.ID()).Int32(hotspotX).Int32(hotspotY)
	return p.Conn().Send(p.ID(), opReqPointerSetCursor, e)
}

func (p *Pointer) Release() error {
	err := p.Conn().Send(p.ID(), opReqPointerRelease, NewEncoder())
	p.Conn().destroy(p)
	return err
}

func (p *Pointer) Dispatch(opcode uint16, dec *Decoder) error {
	switch opcode {
	case opEvtPointerEnter:
		serial := dec.Uint32()
		surfaceID := dec.ID()
		surfaceX := dec.Fixed()
		surfaceY := dec.Fixed()
		if err := dec.Err(); err != nil {
			return err
		}
		surface, _ := p.Conn().Lookup(surfaceID).(*Surface)
		if p.listener.Enter != nil {
			p.listener.Enter(serial, surface, surfaceX, surfaceY)
		}
	case opEvtPointerLeave:
		serial := dec.Uint32()
		surfaceID := dec.ID()
		if err := dec.Err(); err != nil {
			return err
		}
		surface, _ := p.Conn().Lookup(surfaceID).(*Surface)
		if p.listener.Leave != nil {
			p.listener.Leave(serial, surface)
		}
	case opEvtPointerMotion:
		time := dec.Uint32()
		surfaceX := dec.Fixed()
		surfaceY := dec.Fixed()
		if err := dec.Err(); err != nil {
			return err
		}
		if p.listener.Motion != nil {
			p.listener.Motion(time, surfaceX, surfaceY)
		}
	case opEvtPointerButton:
		serial := dec.Uint32()
		time := dec.Uint32()
		button := dec.Uint32()
		state := PointerButtonState(dec.Uint32())
		if err := dec.Err(); err != nil {
			return err
		}
		if p.listener.Button != nil {
			p.listener.Button(serial, time, button, state)
		}
	case opEvtPointerAxis:
		time := dec.Uint32()
		axis := PointerAxis(dec.Uint32())
		value := dec.Fixed()
		if err := dec.Err(); err != nil {
			return err
		}
		if p.listener.Axis != nil {
			p.listener.Axis(time, axis, value)
		}
	case opEvtPointerFrame:
		if err := dec.Err(); err != nil {
			return err
		}
		if p.listener.Frame != nil {
			p.listener.Frame()
		}
	case opEvtPointerAxisSource:
		axisSource := PointerAxisSource(dec.Uint32())
		if err := dec.Err(); err != nil {
			return err
		}
		if p.listener.AxisSource != nil {
			p.listener.AxisSource(axisSource)
		}
	case opEvtPointerAxisStop:
		time := dec.Uint32()
		axis := PointerAxis(dec.Uint32())
		if err := dec.Err(); err != nil {
			return err
		}
		if p.listener.AxisStop != nil {
			p.listener.AxisStop(time, axis)
		}
	case opEvtPointerAxisDiscrete:
		axis := PointerAxis(dec.Uint32())
		discrete := dec.Int32()
		if err := dec.Err(); err != nil {
			return err
		}
		if p.listener.AxisDiscrete != nil {
			p.listener.AxisDiscrete(axis, discrete)
		}
	case opEvtPointerAxisValue120:
		axis := PointerAxis(dec.Uint32())
		value120 := dec.Int32()
		if err := dec.Err(); err != nil {
			return err
		}
		if p.listener.AxisValue120 != nil {
			p.listener.AxisValue120(axis, value120)
		}
	case opEvtPointerAxisRelativeDirection:
		axis := PointerAxis(dec.Uint32())
		direction := PointerAxisRelativeDirection(dec.Uint32())
		if err := dec.Err(); err != nil {
			return err
		}
		if p.listener.AxisRelativeDirection != nil {
			p.listener.AxisRelativeDirection(axis, direction)
		}
	case opEvtPointerWarp:
		surfaceX := dec.Fixed()
		surfaceY := dec.Fixed()
		if err := dec.Err(); err != nil {
			return err
		}
		if p.listener.Warp != nil {
			p.listener.Warp(surfaceX, surfaceY)
		}
	default:
		return fmt.Errorf("wlcore: opcode %d desconocido en wl_pointer", opcode)
	}
	return nil
}

type PointerError uint32

const (
	PointerErrorRole PointerError = 0
)

type PointerButtonState uint32

const (
	PointerButtonStateReleased PointerButtonState = 0
	PointerButtonStatePressed  PointerButtonState = 1
)

type PointerAxis uint32

const (
	PointerAxisVerticalScroll   PointerAxis = 0
	PointerAxisHorizontalScroll PointerAxis = 1
)

type PointerAxisSource uint32

const (
	PointerAxisSourceWheel      PointerAxisSource = 0
	PointerAxisSourceFinger     PointerAxisSource = 1
	PointerAxisSourceContinuous PointerAxisSource = 2
	PointerAxisSourceWheelTilt  PointerAxisSource = 3
)

type PointerAxisRelativeDirection uint32

const (
	PointerAxisRelativeDirectionIdentical PointerAxisRelativeDirection = 0
	PointerAxisRelativeDirectionInverted  PointerAxisRelativeDirection = 1
)

const (
	opReqPointerSetCursor             = 0
	opReqPointerRelease               = 1
	opEvtPointerEnter                 = 0
	opEvtPointerLeave                 = 1
	opEvtPointerMotion                = 2
	opEvtPointerButton                = 3
	opEvtPointerAxis                  = 4
	opEvtPointerFrame                 = 5
	opEvtPointerAxisSource            = 6
	opEvtPointerAxisStop              = 7
	opEvtPointerAxisDiscrete          = 8
	opEvtPointerAxisValue120          = 9
	opEvtPointerAxisRelativeDirection = 10
	opEvtPointerWarp                  = 11
)
