// Code generated by waygenerator. DO NOT EDIT.

package wlcore

import "fmt"

// Pointer: pointer input device
//
// The wl_pointer interface represents one or more input devices,
// such as mice, which control the pointer location and pointer_focus
// of a seat.
//
// The wl_pointer interface generates motion, enter and leave
// events for the surfaces that the pointer is located over,
// and button and axis events for button presses, button releases
// and scrolling.
type Pointer struct {
	ProxyBase
	listener PointerListener
}

var _ Proxy = (*Pointer)(nil)

func newPointer(id, version uint32, conn *Conn) *Pointer {
	return newPointerFromProxyBase(NewProxyBase(id, version, conn))
}

func newPointerFromProxyBase(base ProxyBase) *Pointer {
	p := &Pointer{ProxyBase: base}
	p.OnClear = func() { p.listener = PointerListener{} }
	return p
}

func (p *Pointer) SetListener(l PointerListener) { p.listener = l }

type PointerListener struct {
	// Enter: enter event
	//
	// Notification that this seat's pointer is focused on a certain
	// surface.
	//
	// When a seat's focus enters a surface, the pointer image
	// is undefined and a client should respond to this event by setting
	// an appropriate pointer image with the set_cursor request.
	//
	// Parameters:
	//   - serial: serial number of the enter event
	//   - surface: surface entered by the pointer
	//   - surfaceX: surface-local x coordinate
	//   - surfaceY: surface-local y coordinate
	Enter func(serial uint32, surface *Surface, surfaceX Fixed, surfaceY Fixed)
	// Leave: leave event
	//
	// Notification that this seat's pointer is no longer focused on
	// a certain surface.
	//
	// The leave notification is sent before the enter notification
	// for the new focus.
	//
	// Parameters:
	//   - serial: serial number of the leave event
	//   - surface: surface left by the pointer
	Leave func(serial uint32, surface *Surface)
	// Motion: pointer motion event
	//
	// Notification of pointer location change. The arguments
	// surface_x and surface_y are the location relative to the
	// focused surface.
	//
	// Parameters:
	//   - time: timestamp with millisecond granularity
	//   - surfaceX: surface-local x coordinate
	//   - surfaceY: surface-local y coordinate
	Motion func(time uint32, surfaceX Fixed, surfaceY Fixed)
	// Button: pointer button event
	//
	// Mouse button click and release notifications.
	//
	// The location of the click is given by the last motion, warp or
	// enter event.
	// The time argument is a timestamp with millisecond
	// granularity, with an undefined base.
	//
	// The button is a button code as defined in the Linux kernel's
	// linux/input-event-codes.h header file, e.g. BTN_LEFT.
	//
	// Any 16-bit button code value is reserved for future additions to the
	// kernel's event code list. All other button codes above 0xFFFF are
	// currently undefined but may be used in future versions of this
	// protocol.
	//
	// Parameters:
	//   - serial: serial number of the button event
	//   - time: timestamp with millisecond granularity
	//   - button: button that produced the event
	//   - state: physical state of the button
	Button func(serial uint32, time uint32, button uint32, state PointerButtonState)
	// Axis: axis event
	//
	// Scroll and other axis notifications.
	//
	// For scroll events (vertical and horizontal scroll axes), the
	// value parameter is the length of a vector along the specified
	// axis in a coordinate space identical to those of motion events,
	// representing a relative movement along the specified axis.
	//
	// For devices that support movements non-parallel to axes multiple
	// axis events will be emitted.
	//
	// When applicable, for example for touch pads, the server can
	// choose to emit scroll events where the motion vector is
	// equivalent to a motion event vector.
	//
	// When applicable, a client can transform its content relative to the
	// scroll distance.
	//
	// Parameters:
	//   - time: timestamp with millisecond granularity
	//   - axis: axis type
	//   - value: length of vector in surface-local coordinate space
	Axis func(time uint32, axis PointerAxis, value Fixed)
	// Frame: end of a pointer event sequence
	//
	// Indicates the end of a set of events that logically belong together.
	// A client is expected to accumulate the data in all events within the
	// frame before proceeding.
	//
	// All wl_pointer events before a wl_pointer.frame event belong
	// logically together. For example, in a diagonal scroll motion the
	// compositor will send an optional wl_pointer.axis_source event, two
	// wl_pointer.axis events (horizontal and vertical) and finally a
	// wl_pointer.frame event. The client may use this information to
	// calculate a diagonal vector for scrolling.
	//
	// When multiple wl_pointer.axis events occur within the same frame,
	// the motion vector is the combined motion of all events.
	// When a wl_pointer.axis and a wl_pointer.axis_stop event occur within
	// the same frame, this indicates that axis movement in one axis has
	// stopped but continues in the other axis.
	// When multiple wl_pointer.axis_stop events occur within the same
	// frame, this indicates that these axes stopped in the same instance.
	//
	// A wl_pointer.frame event is sent for every logical event group,
	// even if the group only contains a single wl_pointer event.
	// Specifically, a client may get a sequence: motion, frame, button,
	// frame, axis, frame, axis_stop, frame.
	//
	// The wl_pointer.enter and wl_pointer.leave events are logical events
	// generated by the compositor and not the hardware. These events are
	// also grouped by a wl_pointer.frame. When a pointer moves from one
	// surface to another, a compositor should group the
	// wl_pointer.leave event within the same wl_pointer.frame.
	// However, a client must not rely on wl_pointer.leave and
	// wl_pointer.enter being in the same wl_pointer.frame.
	// Compositor-specific policies may require the wl_pointer.leave and
	// wl_pointer.enter event being split across multiple wl_pointer.frame
	// groups.
	Frame func()
	// AxisSource: axis source event
	//
	// Source information for scroll and other axes.
	//
	// This event does not occur on its own. It is sent before a
	// wl_pointer.frame event and carries the source information for
	// all events within that frame.
	//
	// The source specifies how this event was generated. If the source is
	// wl_pointer.axis_source.finger, a wl_pointer.axis_stop event will be
	// sent when the user lifts the finger off the device.
	//
	// If the source is wl_pointer.axis_source.wheel,
	// wl_pointer.axis_source.wheel_tilt or
	// wl_pointer.axis_source.continuous, a wl_pointer.axis_stop event may
	// or may not be sent. Whether a compositor sends an axis_stop event
	// for these sources is hardware-specific and implementation-dependent;
	// clients must not rely on receiving an axis_stop event for these
	// scroll sources and should treat scroll sequences from these scroll
	// sources as unterminated by default.
	//
	// This event is optional. If the source is unknown for a particular
	// axis event sequence, no event is sent.
	// Only one wl_pointer.axis_source event is permitted per frame.
	//
	// The order of wl_pointer.axis_discrete and wl_pointer.axis_source is
	// not guaranteed.
	//
	// Parameters:
	//   - axisSource: source of the axis event
	AxisSource func(axisSource PointerAxisSource)
	// AxisStop: axis stop event
	//
	// Stop notification for scroll and other axes.
	//
	// For some wl_pointer.axis_source types, a wl_pointer.axis_stop event
	// is sent to notify a client that the axis sequence has terminated.
	// This enables the client to implement kinetic scrolling.
	// See the wl_pointer.axis_source documentation for information on when
	// this event may be generated.
	//
	// Any wl_pointer.axis events with the same axis_source after this
	// event should be considered as the start of a new axis motion.
	//
	// The timestamp is to be interpreted identical to the timestamp in the
	// wl_pointer.axis event. The timestamp value may be the same as a
	// preceding wl_pointer.axis event.
	//
	// Parameters:
	//   - time: timestamp with millisecond granularity
	//   - axis: the axis stopped with this event
	AxisStop func(time uint32, axis PointerAxis)
	// AxisDiscrete: axis click event
	//
	// Discrete step information for scroll and other axes.
	//
	// This event carries the axis value of the wl_pointer.axis event in
	// discrete steps (e.g. mouse wheel clicks).
	//
	// This event is deprecated with wl_pointer version 8 - this event is not
	// sent to clients supporting version 8 or later.
	//
	// This event does not occur on its own, it is coupled with a
	// wl_pointer.axis event that represents this axis value on a
	// continuous scale. The protocol guarantees that each axis_discrete
	// event is always followed by exactly one axis event with the same
	// axis number within the same wl_pointer.frame. Note that the protocol
	// allows for other events to occur between the axis_discrete and
	// its coupled axis event, including other axis_discrete or axis
	// events. A wl_pointer.frame must not contain more than one axis_discrete
	// event per axis type.
	//
	// This event is optional; continuous scrolling devices
	// like two-finger scrolling on touchpads do not have discrete
	// steps and do not generate this event.
	//
	// The discrete value carries the directional information. e.g. a value
	// of -2 is two steps towards the negative direction of this axis.
	//
	// The axis number is identical to the axis number in the associated
	// axis event.
	//
	// The order of wl_pointer.axis_discrete and wl_pointer.axis_source is
	// not guaranteed.
	//
	// Parameters:
	//   - axis: axis type
	//   - discrete: number of steps
	AxisDiscrete func(axis PointerAxis, discrete int32)
	// AxisValue120: axis high-resolution scroll event
	//
	// Discrete high-resolution scroll information.
	//
	// This event carries high-resolution wheel scroll information,
	// with each multiple of 120 representing one logical scroll step
	// (a wheel detent). For example, an axis_value120 of 30 is one quarter of
	// a logical scroll step in the positive direction, a value120 of
	// -240 are two logical scroll steps in the negative direction within the
	// same hardware event.
	// Clients that rely on discrete scrolling should accumulate the
	// value120 to multiples of 120 before processing the event.
	//
	// The value120 must not be zero.
	//
	// This event replaces the wl_pointer.axis_discrete event in clients
	// supporting wl_pointer version 8 or later.
	//
	// Where a wl_pointer.axis_source event occurs in the same
	// wl_pointer.frame, the axis source applies to this event.
	//
	// The order of wl_pointer.axis_value120 and wl_pointer.axis_source is
	// not guaranteed.
	//
	// Parameters:
	//   - axis: axis type
	//   - value120: scroll distance as fraction of 120
	AxisValue120 func(axis PointerAxis, value120 int32)
	// AxisRelativeDirection: axis relative physical direction event
	//
	// Relative directional information of the entity causing the axis
	// motion.
	//
	// For a wl_pointer.axis event, the wl_pointer.axis_relative_direction
	// event specifies the movement direction of the entity causing the
	// wl_pointer.axis event. For example:
	// - if a user's fingers on a touchpad move down and this
	// causes a wl_pointer.axis vertical_scroll down event, the physical
	// direction is 'identical'
	// - if a user's fingers on a touchpad move down and this causes a
	// wl_pointer.axis vertical_scroll up scroll up event ('natural
	// scrolling'), the physical direction is 'inverted'.
	//
	// A client may use this information to adjust scroll motion of
	// components. Specifically, enabling natural scrolling causes the
	// content to change direction compared to traditional scrolling.
	// Some widgets like volume control sliders should usually match the
	// physical direction regardless of whether natural scrolling is
	// active. This event enables clients to match the scroll direction of
	// a widget to the physical direction.
	//
	// This event does not occur on its own, it is coupled with a
	// wl_pointer.axis event that represents this axis value.
	// The protocol guarantees that each axis_relative_direction event is
	// always followed by exactly one axis event with the same
	// axis number within the same wl_pointer.frame. Note that the protocol
	// allows for other events to occur between the axis_relative_direction
	// and its coupled axis event.
	//
	// The axis number is identical to the axis number in the associated
	// axis event.
	//
	// The order of wl_pointer.axis_relative_direction,
	// wl_pointer.axis_discrete and wl_pointer.axis_source is not
	// guaranteed.
	//
	// Parameters:
	//   - axis: axis type
	//   - direction: physical direction relative to axis motion
	AxisRelativeDirection func(axis PointerAxis, direction PointerAxisRelativeDirection)
	// Warp: pointer warp event
	//
	// Notification of pointer location change within a surface.
	//
	// This location change is not due to events on the input device,
	// but because either the surface under the pointer was moved and
	// thus the relative position of the pointer changed, or because
	// the compositor changed the pointer position in response to an
	// event like pointer confinement being exited.
	//
	// The arguments surface_x and surface_y are the location relative to
	// the focused surface.
	//
	// This event must not occur in the same wl_pointer.frame as a
	// wl_pointer.enter or wl_pointer.motion event.
	//
	// Parameters:
	//   - surfaceX: surface-local x coordinate
	//   - surfaceY: surface-local y coordinate
	Warp func(surfaceX Fixed, surfaceY Fixed)
}

var PointerInterface = Interface[*Pointer]{
	Name:       "wl_pointer",
	MaxVersion: 11,
	New:        newPointerFromProxyBase,
}

// SetCursor: set the pointer surface
//
// Set the pointer surface, i.e., the surface that contains the
// pointer image (cursor). This request gives the surface the role
// of a cursor. If the surface already has another role, it raises
// a protocol error.
//
// The cursor actually changes only if the pointer
// focus for this device is one of the requesting client's surfaces
// or the surface parameter is the current pointer surface. If
// there was a previous surface set with this request it is
// replaced. If surface is NULL, the pointer image is hidden.
//
// The parameters hotspot_x and hotspot_y define the position of
// the pointer surface relative to the pointer location. Its
// top-left corner is always at (x, y) - (hotspot_x, hotspot_y),
// where (x, y) are the coordinates of the pointer location, in
// surface-local coordinates.
//
// On wl_surface.offset requests to the pointer surface, hotspot_x
// and hotspot_y are decremented by the x and y parameters
// passed to the request. The offset must be applied by
// wl_surface.commit as usual.
//
// The hotspot can also be updated by passing the currently set
// pointer surface to this request with new values for hotspot_x
// and hotspot_y.
//
// The input region is ignored for wl_surfaces with the role of
// a cursor. When the use as a cursor ends, the wl_surface is
// unmapped.
//
// The serial parameter must match the latest wl_pointer.enter
// serial number sent to the client. Otherwise the request will be
// ignored.
//
// Parameters:
//   - serial: serial number of the enter event
//   - surface: pointer surface
//   - hotspotX: surface-local x coordinate
//   - hotspotY: surface-local y coordinate
func (p *Pointer) SetCursor(serial uint32, surface *Surface, hotspotX int32, hotspotY int32) error {
	var surfaceID uint32
	if surface != nil {
		surfaceID = surface.ID()
	}
	e := NewEncoder().Uint32(serial).ID(surfaceID).Int32(hotspotX).Int32(hotspotY)
	return p.Conn().Send(p.ID(), opReqPointerSetCursor, e)
}

// Release: release the pointer object
//
// Using this request a client can tell the server that it is not going to
// use the pointer object anymore.
//
// This request destroys the pointer proxy object, so clients must not call
// wl_pointer_destroy() after using this request.
func (p *Pointer) Release() error {
	if p.Version() < 3 {
		return fmt.Errorf("wlcore: release requiere versión >= 3, hay %d", p.Version())
	}
	err := p.Conn().Send(p.ID(), opReqPointerRelease, NewEncoder())
	p.Conn().destroy(p)
	return err
}

func (p *Pointer) Dispatch(opcode uint16, dec *Decoder) error {
	switch opcode {
	case opEvtPointerEnter:
		serial := dec.Uint32()
		surfaceID := dec.ID()
		surfaceX := dec.Fixed()
		surfaceY := dec.Fixed()
		if err := dec.Err(); err != nil {
			return err
		}
		surface, _ := p.Conn().Lookup(surfaceID).(*Surface)
		if p.listener.Enter != nil {
			p.listener.Enter(serial, surface, surfaceX, surfaceY)
		}
	case opEvtPointerLeave:
		serial := dec.Uint32()
		surfaceID := dec.ID()
		if err := dec.Err(); err != nil {
			return err
		}
		surface, _ := p.Conn().Lookup(surfaceID).(*Surface)
		if p.listener.Leave != nil {
			p.listener.Leave(serial, surface)
		}
	case opEvtPointerMotion:
		time := dec.Uint32()
		surfaceX := dec.Fixed()
		surfaceY := dec.Fixed()
		if err := dec.Err(); err != nil {
			return err
		}
		if p.listener.Motion != nil {
			p.listener.Motion(time, surfaceX, surfaceY)
		}
	case opEvtPointerButton:
		serial := dec.Uint32()
		time := dec.Uint32()
		button := dec.Uint32()
		state := PointerButtonState(dec.Uint32())
		if err := dec.Err(); err != nil {
			return err
		}
		if p.listener.Button != nil {
			p.listener.Button(serial, time, button, state)
		}
	case opEvtPointerAxis:
		time := dec.Uint32()
		axis := PointerAxis(dec.Uint32())
		value := dec.Fixed()
		if err := dec.Err(); err != nil {
			return err
		}
		if p.listener.Axis != nil {
			p.listener.Axis(time, axis, value)
		}
	case opEvtPointerFrame:
		if err := dec.Err(); err != nil {
			return err
		}
		if p.listener.Frame != nil {
			p.listener.Frame()
		}
	case opEvtPointerAxisSource:
		axisSource := PointerAxisSource(dec.Uint32())
		if err := dec.Err(); err != nil {
			return err
		}
		if p.listener.AxisSource != nil {
			p.listener.AxisSource(axisSource)
		}
	case opEvtPointerAxisStop:
		time := dec.Uint32()
		axis := PointerAxis(dec.Uint32())
		if err := dec.Err(); err != nil {
			return err
		}
		if p.listener.AxisStop != nil {
			p.listener.AxisStop(time, axis)
		}
	case opEvtPointerAxisDiscrete:
		axis := PointerAxis(dec.Uint32())
		discrete := dec.Int32()
		if err := dec.Err(); err != nil {
			return err
		}
		if p.listener.AxisDiscrete != nil {
			p.listener.AxisDiscrete(axis, discrete)
		}
	case opEvtPointerAxisValue120:
		axis := PointerAxis(dec.Uint32())
		value120 := dec.Int32()
		if err := dec.Err(); err != nil {
			return err
		}
		if p.listener.AxisValue120 != nil {
			p.listener.AxisValue120(axis, value120)
		}
	case opEvtPointerAxisRelativeDirection:
		axis := PointerAxis(dec.Uint32())
		direction := PointerAxisRelativeDirection(dec.Uint32())
		if err := dec.Err(); err != nil {
			return err
		}
		if p.listener.AxisRelativeDirection != nil {
			p.listener.AxisRelativeDirection(axis, direction)
		}
	case opEvtPointerWarp:
		surfaceX := dec.Fixed()
		surfaceY := dec.Fixed()
		if err := dec.Err(); err != nil {
			return err
		}
		if p.listener.Warp != nil {
			p.listener.Warp(surfaceX, surfaceY)
		}
	default:
		return fmt.Errorf("wlcore: opcode %d desconocido en wl_pointer", opcode)
	}
	return nil
}

type PointerError uint32

const (
	PointerErrorRole PointerError = 0 // given wl_surface has another role
)

// PointerButtonState: physical button state
//
// Describes the physical state of a button that produced the button
// event.
type PointerButtonState uint32

const (
	PointerButtonStateReleased PointerButtonState = 0 // the button is not pressed
	PointerButtonStatePressed  PointerButtonState = 1 // the button is pressed
)

// PointerAxis: axis types
//
// Describes the axis types of scroll events.
type PointerAxis uint32

const (
	PointerAxisVerticalScroll   PointerAxis = 0 // vertical axis
	PointerAxisHorizontalScroll PointerAxis = 1 // horizontal axis
)

// PointerAxisSource: axis source types
//
// Describes the source types for axis events. This indicates to the
// client how an axis event was physically generated; a client may
// adjust the user interface accordingly. For example, scroll events
// from a "finger" source may be in a smooth coordinate space with
// kinetic scrolling whereas a "wheel" source may be in discrete steps
// of a number of lines.
//
// The "continuous" axis source is a device generating events in a
// continuous coordinate space, but using something other than a
// finger. One example for this source is button-based scrolling where
// the vertical motion of a device is converted to scroll events while
// a button is held down.
//
// The "wheel tilt" axis source indicates that the actual device is a
// wheel but the scroll event is not caused by a rotation but a
// (usually sideways) tilt of the wheel.
type PointerAxisSource uint32

const (
	PointerAxisSourceWheel      PointerAxisSource = 0 // a physical wheel rotation
	PointerAxisSourceFinger     PointerAxisSource = 1 // finger on a touch surface
	PointerAxisSourceContinuous PointerAxisSource = 2 // continuous coordinate space
	PointerAxisSourceWheelTilt  PointerAxisSource = 3 // a physical wheel tilt
)

// PointerAxisRelativeDirection: axis relative direction
//
// This specifies the direction of the physical motion that caused a
// wl_pointer.axis event, relative to the wl_pointer.axis direction.
type PointerAxisRelativeDirection uint32

const (
	PointerAxisRelativeDirectionIdentical PointerAxisRelativeDirection = 0 // physical motion matches axis direction
	PointerAxisRelativeDirectionInverted  PointerAxisRelativeDirection = 1 // physical motion is the inverse of the axis direction
)

const (
	opReqPointerSetCursor             = 0
	opReqPointerRelease               = 1
	opEvtPointerEnter                 = 0
	opEvtPointerLeave                 = 1
	opEvtPointerMotion                = 2
	opEvtPointerButton                = 3
	opEvtPointerAxis                  = 4
	opEvtPointerFrame                 = 5
	opEvtPointerAxisSource            = 6
	opEvtPointerAxisStop              = 7
	opEvtPointerAxisDiscrete          = 8
	opEvtPointerAxisValue120          = 9
	opEvtPointerAxisRelativeDirection = 10
	opEvtPointerWarp                  = 11
)
