// Code generated by waygenerator. DO NOT EDIT.

package wlcore

import "fmt"

type Registry struct {
	ProxyBase
	listener RegistryListener
}

var _ Proxy = (*Registry)(nil)

func newRegistry(id, version uint32, conn *Conn) *Registry {
	r := &Registry{ProxyBase: NewProxyBase(id, version, conn)}
	r.OnClear = func() { r.listener = RegistryListener{} }
	return r
}

func (r *Registry) SetListener(l RegistryListener) { r.listener = l }

type RegistryListener struct {
	Global       func(name uint32, interface_ string, version uint32)
	GlobalRemove func(name uint32)
}

var RegistryInterface = Interface[*Registry]{
	Name:       "wl_registry",
	MaxVersion: 1,
	New:        func(b ProxyBase) *Registry { return &Registry{ProxyBase: b} },
}

func (r *Registry) bindRaw(name uint32, iface string, version, newID uint32) error {
	e := NewEncoder().Uint32(name).String(iface).Uint32(version).ID(newID)
	return r.Conn().Send(r.ID(), opReqRegistryBind, e)
}

func (r *Registry) Dispatch(opcode uint16, dec *Decoder) error {
	switch opcode {
	case opEvtRegistryGlobal:
		name := dec.Uint32()
		interface_ := dec.String()
		version := dec.Uint32()
		if err := dec.Err(); err != nil {
			return err
		}
		if r.listener.Global != nil {
			r.listener.Global(name, interface_, version)
		}
	case opEvtRegistryGlobalRemove:
		name := dec.Uint32()
		if err := dec.Err(); err != nil {
			return err
		}
		if r.listener.GlobalRemove != nil {
			r.listener.GlobalRemove(name)
		}
	default:
		return fmt.Errorf("wlcore: opcode %d desconocido en wl_registry", opcode)
	}
	return nil
}

const (
	opReqRegistryBind         = 0
	opEvtRegistryGlobal       = 0
	opEvtRegistryGlobalRemove = 1
)
