// Code generated by waygenerator. DO NOT EDIT.

package wlcore

import "fmt"

type Region struct {
	ProxyBase
	listener RegionListener
}

var _ Proxy = (*Region)(nil)

func newRegion(id, version uint32, conn *Conn) *Region {
	r := &Region{ProxyBase: NewProxyBase(id, version, conn)}
	return r
}

func (r *Region) SetListener(l RegionListener) { r.listener = l }

type RegionListener struct {
}

var RegionInterface = Interface[*Region]{
	Name:       "wl_region",
	MaxVersion: 7,
	New:        func(b ProxyBase) *Region { return &Region{ProxyBase: b} },
}

func (r *Region) Destroy() error {
	err := r.Conn().Send(r.ID(), opReqRegionDestroy, NewEncoder())
	r.Conn().destroy(r)
	return err
}

func (r *Region) Add(x int32, y int32, width int32, height int32) error {
	e := NewEncoder().Int32(x).Int32(y).Int32(width).Int32(height)
	return r.Conn().Send(r.ID(), opReqRegionAdd, e)
}

func (r *Region) Subtract(x int32, y int32, width int32, height int32) error {
	e := NewEncoder().Int32(x).Int32(y).Int32(width).Int32(height)
	return r.Conn().Send(r.ID(), opReqRegionSubtract, e)
}

func (r *Region) Dispatch(opcode uint16, dec *Decoder) error {
	switch opcode {
	default:
		return fmt.Errorf("wlcore: opcode %d desconocido en wl_region", opcode)
	}
}

const (
	opReqRegionDestroy  = 0
	opReqRegionAdd      = 1
	opReqRegionSubtract = 2
)
