// Code generated by waygenerator. DO NOT EDIT.

package wlcore

import "fmt"

// Region: region interface
//
// A region object describes an area.
//
// Region objects are used to describe the opaque and input
// regions of a surface.
type Region struct {
	ProxyBase
	listener RegionListener
}

var _ Proxy = (*Region)(nil)

func newRegion(id, version uint32, conn *Conn) *Region {
	return newRegionFromProxyBase(NewProxyBase(id, version, conn))
}

func newRegionFromProxyBase(base ProxyBase) *Region {
	r := &Region{ProxyBase: base}
	return r
}

// SetListener installs the handlers for wl_region's events, replacing any
// already installed. A nil field ignores that event; a file descriptor
// arriving in an ignored event is closed, not leaked.
func (r *Region) SetListener(l RegionListener) { r.listener = l }

// RegionListener holds the handlers for wl_region's events. Its zero value
// ignores every event. See [Region.SetListener].
type RegionListener struct {
}

// RegionInterface describes wl_region for [Registry.Bind]: the name it
// carries on the wire and version 1, the highest this binding implements.
// Bind negotiates that against the version the compositor advertises, so a
// call site never repeats either value.
var RegionInterface = Interface[*Region]{
	Name:       "wl_region",
	MaxVersion: 1,
	New:        newRegionFromProxyBase,
}

// Destroy: destroy region
//
// Destroy the region.  This will invalidate the object ID.
func (r *Region) Destroy() error {
	err := r.Conn().Send(r.ID(), opReqRegionDestroy, NewEncoder())
	r.Conn().Destroy(r)
	return err
}

// Add: add rectangle to region
//
// Add the specified rectangle to the region.
//
// Parameters:
//   - x: region-local x coordinate
//   - y: region-local y coordinate
//   - width: rectangle width
//   - height: rectangle height
func (r *Region) Add(x int32, y int32, width int32, height int32) error {
	e := NewEncoder().Int32(x).Int32(y).Int32(width).Int32(height)
	return r.Conn().Send(r.ID(), opReqRegionAdd, e)
}

// Subtract: subtract rectangle from region
//
// Subtract the specified rectangle from the region.
//
// Parameters:
//   - x: region-local x coordinate
//   - y: region-local y coordinate
//   - width: rectangle width
//   - height: rectangle height
func (r *Region) Subtract(x int32, y int32, width int32, height int32) error {
	e := NewEncoder().Int32(x).Int32(y).Int32(width).Int32(height)
	return r.Conn().Send(r.ID(), opReqRegionSubtract, e)
}

// Dispatch decodes one wl_region event and calls the matching field of the
// listener. The connection calls it while pumping messages; it is exported
// only because the runtime's Proxy interface requires it.
func (r *Region) Dispatch(opcode uint16, dec *Decoder) error {
	switch opcode {
	default:
		return fmt.Errorf("wlcore: unknown opcode %d in wl_region", opcode)
	}
}

const (
	opReqRegionDestroy  = 0
	opReqRegionAdd      = 1
	opReqRegionSubtract = 2
)
