// Code generated by waygenerator. DO NOT EDIT.

package wlcore

import "fmt"

// Registry: global registry object
//
// The singleton global registry object.  The server has a number of
// global objects that are available to all clients.  These objects
// typically represent an actual object in the server (for example,
// an input device) or they are singleton objects that provide
// extension functionality.
//
// When a client creates a registry object, the registry object
// will emit a global event for each global currently in the
// registry.  Globals come and go as a result of device or
// monitor hotplugs, reconfiguration or other events, and the
// registry will send out global and global_remove events to
// keep the client up to date with the changes.  To mark the end
// of the initial burst of events, the client can use the
// wl_display.sync request immediately after calling
// wl_display.get_registry.
//
// A client can bind to a global object by using the bind
// request.  This creates a client-side handle that lets the object
// emit events to the client and lets the client invoke requests on
// the object.
type Registry struct {
	ProxyBase
	listener RegistryListener
}

var _ Proxy = (*Registry)(nil)

func newRegistry(id, version uint32, conn *Conn) *Registry {
	return newRegistryFromProxyBase(NewProxyBase(id, version, conn))
}

func newRegistryFromProxyBase(base ProxyBase) *Registry {
	r := &Registry{ProxyBase: base}
	r.OnClear = func() { r.listener = RegistryListener{} }
	return r
}

func (r *Registry) SetListener(l RegistryListener) { r.listener = l }

type RegistryListener struct {
	// Global: announce global object
	//
	// Notify the client of global objects.
	//
	// The event notifies the client that a global object with
	// the given name is now available, and it implements the
	// given version of the given interface.
	//
	// Parameters:
	//   - name: numeric name of the global object
	//   - iface: interface implemented by the object
	//   - version: interface version
	Global func(name uint32, iface string, version uint32)
	// GlobalRemove: announce removal of global object
	//
	// Notify the client of removed global objects.
	//
	// This event notifies the client that the global identified
	// by name is no longer available.  If the client bound to
	// the global using the bind request, the client should now
	// destroy that object.
	//
	// The object remains valid and requests to the object will be
	// ignored until the client destroys it, to avoid races between
	// the global going away and a client sending a request to it.
	//
	// Parameters:
	//   - name: numeric name of the global object
	GlobalRemove func(name uint32)
}

var RegistryInterface = Interface[*Registry]{
	Name:       "wl_registry",
	MaxVersion: 1,
	New:        newRegistryFromProxyBase,
}

func (r *Registry) bindRaw(name uint32, iface string, version, newID uint32) error {
	e := NewEncoder().Uint32(name).String(iface).Uint32(version).ID(newID)
	return r.Conn().Send(r.ID(), opReqRegistryBind, e)
}

func (r *Registry) Dispatch(opcode uint16, dec *Decoder) error {
	switch opcode {
	case opEvtRegistryGlobal:
		name := dec.Uint32()
		iface := dec.String()
		version := dec.Uint32()
		if err := dec.Err(); err != nil {
			return err
		}
		if r.listener.Global != nil {
			r.listener.Global(name, iface, version)
		}
	case opEvtRegistryGlobalRemove:
		name := dec.Uint32()
		if err := dec.Err(); err != nil {
			return err
		}
		if r.listener.GlobalRemove != nil {
			r.listener.GlobalRemove(name)
		}
	default:
		return fmt.Errorf("wlcore: unknown opcode %d in wl_registry", opcode)
	}
	return nil
}

const (
	opReqRegistryBind         = 0
	opEvtRegistryGlobal       = 0
	opEvtRegistryGlobalRemove = 1
)
