// Code generated by waygenerator. DO NOT EDIT.

package wlcore

import "fmt"

type Seat struct {
	ProxyBase
	listener SeatListener
}

var _ Proxy = (*Seat)(nil)

func newSeat(id, version uint32, conn *Conn) *Seat {
	return newSeatFromProxyBase(NewProxyBase(id, version, conn))
}

func newSeatFromProxyBase(base ProxyBase) *Seat {
	s := &Seat{ProxyBase: base}
	s.OnClear = func() { s.listener = SeatListener{} }
	return s
}

func (s *Seat) SetListener(l SeatListener) { s.listener = l }

type SeatListener struct {
	Capabilities func(capabilities SeatCapability)
	Name         func(name string)
}

var SeatInterface = Interface[*Seat]{
	Name:       "wl_seat",
	MaxVersion: 11,
	New:        newSeatFromProxyBase,
}

func (s *Seat) GetPointer() (*Pointer, error) {
	id := s.Conn().NewID()
	x := newPointerFromProxyBase(NewProxyBase(id, s.Version(), s.Conn()))
	s.Conn().Register(x)

	e := NewEncoder().ID(id)
	if err := s.Conn().Send(s.ID(), opReqSeatGetPointer, e); err != nil {
		return nil, err
	}
	return x, nil
}

func (s *Seat) GetKeyboard() (*Keyboard, error) {
	id := s.Conn().NewID()
	x := newKeyboardFromProxyBase(NewProxyBase(id, s.Version(), s.Conn()))
	s.Conn().Register(x)

	e := NewEncoder().ID(id)
	if err := s.Conn().Send(s.ID(), opReqSeatGetKeyboard, e); err != nil {
		return nil, err
	}
	return x, nil
}

func (s *Seat) GetTouch() (*Touch, error) {
	id := s.Conn().NewID()
	x := newTouchFromProxyBase(NewProxyBase(id, s.Version(), s.Conn()))
	s.Conn().Register(x)

	e := NewEncoder().ID(id)
	if err := s.Conn().Send(s.ID(), opReqSeatGetTouch, e); err != nil {
		return nil, err
	}
	return x, nil
}

func (s *Seat) Release() error {
	if s.Version() < 5 {
		return fmt.Errorf("wlcore: release requiere versión >= 5, hay %d", s.Version())
	}
	err := s.Conn().Send(s.ID(), opReqSeatRelease, NewEncoder())
	s.Conn().destroy(s)
	return err
}

func (s *Seat) Dispatch(opcode uint16, dec *Decoder) error {
	switch opcode {
	case opEvtSeatCapabilities:
		capabilities := SeatCapability(dec.Uint32())
		if err := dec.Err(); err != nil {
			return err
		}
		if s.listener.Capabilities != nil {
			s.listener.Capabilities(capabilities)
		}
	case opEvtSeatName:
		name := dec.String()
		if err := dec.Err(); err != nil {
			return err
		}
		if s.listener.Name != nil {
			s.listener.Name(name)
		}
	default:
		return fmt.Errorf("wlcore: opcode %d desconocido en wl_seat", opcode)
	}
	return nil
}

type SeatCapability uint32

const (
	SeatCapabilityPointer  SeatCapability = 1
	SeatCapabilityKeyboard SeatCapability = 2
	SeatCapabilityTouch    SeatCapability = 4
)

func (v SeatCapability) Has(flag SeatCapability) bool { return v&flag != 0 }

type SeatError uint32

const (
	SeatErrorMissingCapability SeatError = 0
)

const (
	opReqSeatGetPointer   = 0
	opReqSeatGetKeyboard  = 1
	opReqSeatGetTouch     = 2
	opReqSeatRelease      = 3
	opEvtSeatCapabilities = 0
	opEvtSeatName         = 1
)
