// Code generated by waygenerator. DO NOT EDIT.

package wlcore

import "fmt"

type Shell struct {
	ProxyBase
	listener ShellListener
}

var _ Proxy = (*Shell)(nil)

func newShell(id, version uint32, conn *Conn) *Shell {
	return newShellFromProxyBase(NewProxyBase(id, version, conn))
}

func newShellFromProxyBase(base ProxyBase) *Shell {
	s := &Shell{ProxyBase: base}
	return s
}

func (s *Shell) SetListener(l ShellListener) { s.listener = l }

type ShellListener struct {
}

var ShellInterface = Interface[*Shell]{
	Name:       "wl_shell",
	MaxVersion: 1,
	New:        newShellFromProxyBase,
}

func (s *Shell) GetShellSurface(surface *Surface) (*ShellSurface, error) {
	id := s.Conn().NewID()
	x := newShellSurfaceFromProxyBase(NewProxyBase(id, s.Version(), s.Conn()))
	s.Conn().Register(x)

	e := NewEncoder().ID(id).ID(surface.ID())
	if err := s.Conn().Send(s.ID(), opReqShellGetShellSurface, e); err != nil {
		return nil, err
	}
	return x, nil
}

func (s *Shell) Dispatch(opcode uint16, dec *Decoder) error {
	switch opcode {
	default:
		return fmt.Errorf("wlcore: opcode %d desconocido en wl_shell", opcode)
	}
}

type ShellError uint32

const (
	ShellErrorRole ShellError = 0
)

const (
	opReqShellGetShellSurface = 0
)
