// Code generated by waygenerator. DO NOT EDIT.

package wlcore

import "fmt"

type ShellSurface struct {
	ProxyBase
	listener ShellSurfaceListener
}

var _ Proxy = (*ShellSurface)(nil)

func newShellSurface(id, version uint32, conn *Conn) *ShellSurface {
	return newShellSurfaceFromProxyBase(NewProxyBase(id, version, conn))
}

func newShellSurfaceFromProxyBase(base ProxyBase) *ShellSurface {
	s := &ShellSurface{ProxyBase: base}
	s.OnClear = func() { s.listener = ShellSurfaceListener{} }
	return s
}

func (s *ShellSurface) SetListener(l ShellSurfaceListener) { s.listener = l }

type ShellSurfaceListener struct {
	Ping      func(serial uint32)
	Configure func(edges ShellSurfaceResize, width int32, height int32)
	PopupDone func()
}

var ShellSurfaceInterface = Interface[*ShellSurface]{
	Name:       "wl_shell_surface",
	MaxVersion: 1,
	New:        newShellSurfaceFromProxyBase,
}

func (s *ShellSurface) Pong(serial uint32) error {
	e := NewEncoder().Uint32(serial)
	return s.Conn().Send(s.ID(), opReqShellSurfacePong, e)
}

func (s *ShellSurface) Move(seat *Seat, serial uint32) error {
	e := NewEncoder().ID(seat.ID()).Uint32(serial)
	return s.Conn().Send(s.ID(), opReqShellSurfaceMove, e)
}

func (s *ShellSurface) Resize(seat *Seat, serial uint32, edges ShellSurfaceResize) error {
	e := NewEncoder().ID(seat.ID()).Uint32(serial).Uint32(uint32(edges))
	return s.Conn().Send(s.ID(), opReqShellSurfaceResize, e)
}

func (s *ShellSurface) SetToplevel() error {
	e := NewEncoder()
	return s.Conn().Send(s.ID(), opReqShellSurfaceSetToplevel, e)
}

func (s *ShellSurface) SetTransient(parent *Surface, x int32, y int32, flags ShellSurfaceTransient) error {
	e := NewEncoder().ID(parent.ID()).Int32(x).Int32(y).Uint32(uint32(flags))
	return s.Conn().Send(s.ID(), opReqShellSurfaceSetTransient, e)
}

func (s *ShellSurface) SetFullscreen(method ShellSurfaceFullscreenMethod, framerate uint32, output *Output) error {
	var outputID uint32
	if output != nil {
		outputID = output.ID()
	}
	e := NewEncoder().Uint32(uint32(method)).Uint32(framerate).ID(outputID)
	return s.Conn().Send(s.ID(), opReqShellSurfaceSetFullscreen, e)
}

func (s *ShellSurface) SetPopup(seat *Seat, serial uint32, parent *Surface, x int32, y int32, flags ShellSurfaceTransient) error {
	e := NewEncoder().ID(seat.ID()).Uint32(serial).ID(parent.ID()).Int32(x).Int32(y).Uint32(uint32(flags))
	return s.Conn().Send(s.ID(), opReqShellSurfaceSetPopup, e)
}

func (s *ShellSurface) SetMaximized(output *Output) error {
	var outputID uint32
	if output != nil {
		outputID = output.ID()
	}
	e := NewEncoder().ID(outputID)
	return s.Conn().Send(s.ID(), opReqShellSurfaceSetMaximized, e)
}

func (s *ShellSurface) SetTitle(title string) error {
	e := NewEncoder().String(title)
	return s.Conn().Send(s.ID(), opReqShellSurfaceSetTitle, e)
}

func (s *ShellSurface) SetClass(class string) error {
	e := NewEncoder().String(class)
	return s.Conn().Send(s.ID(), opReqShellSurfaceSetClass, e)
}

func (s *ShellSurface) Dispatch(opcode uint16, dec *Decoder) error {
	switch opcode {
	case opEvtShellSurfacePing:
		serial := dec.Uint32()
		if err := dec.Err(); err != nil {
			return err
		}
		if s.listener.Ping != nil {
			s.listener.Ping(serial)
		}
	case opEvtShellSurfaceConfigure:
		edges := ShellSurfaceResize(dec.Uint32())
		width := dec.Int32()
		height := dec.Int32()
		if err := dec.Err(); err != nil {
			return err
		}
		if s.listener.Configure != nil {
			s.listener.Configure(edges, width, height)
		}
	case opEvtShellSurfacePopupDone:
		if err := dec.Err(); err != nil {
			return err
		}
		if s.listener.PopupDone != nil {
			s.listener.PopupDone()
		}
	default:
		return fmt.Errorf("wlcore: opcode %d desconocido en wl_shell_surface", opcode)
	}
	return nil
}

type ShellSurfaceResize uint32

const (
	ShellSurfaceResizeNone        ShellSurfaceResize = 0
	ShellSurfaceResizeTop         ShellSurfaceResize = 1
	ShellSurfaceResizeBottom      ShellSurfaceResize = 2
	ShellSurfaceResizeLeft        ShellSurfaceResize = 4
	ShellSurfaceResizeTopLeft     ShellSurfaceResize = 5
	ShellSurfaceResizeBottomLeft  ShellSurfaceResize = 6
	ShellSurfaceResizeRight       ShellSurfaceResize = 8
	ShellSurfaceResizeTopRight    ShellSurfaceResize = 9
	ShellSurfaceResizeBottomRight ShellSurfaceResize = 10
)

func (v ShellSurfaceResize) Has(flag ShellSurfaceResize) bool { return v&flag != 0 }

type ShellSurfaceTransient uint32

const (
	ShellSurfaceTransientInactive ShellSurfaceTransient = 0x1
)

func (v ShellSurfaceTransient) Has(flag ShellSurfaceTransient) bool { return v&flag != 0 }

type ShellSurfaceFullscreenMethod uint32

const (
	ShellSurfaceFullscreenMethodDefault ShellSurfaceFullscreenMethod = 0
	ShellSurfaceFullscreenMethodScale   ShellSurfaceFullscreenMethod = 1
	ShellSurfaceFullscreenMethodDriver  ShellSurfaceFullscreenMethod = 2
	ShellSurfaceFullscreenMethodFill    ShellSurfaceFullscreenMethod = 3
)

const (
	opReqShellSurfacePong          = 0
	opReqShellSurfaceMove          = 1
	opReqShellSurfaceResize        = 2
	opReqShellSurfaceSetToplevel   = 3
	opReqShellSurfaceSetTransient  = 4
	opReqShellSurfaceSetFullscreen = 5
	opReqShellSurfaceSetPopup      = 6
	opReqShellSurfaceSetMaximized  = 7
	opReqShellSurfaceSetTitle      = 8
	opReqShellSurfaceSetClass      = 9
	opEvtShellSurfacePing          = 0
	opEvtShellSurfaceConfigure     = 1
	opEvtShellSurfacePopupDone     = 2
)
