// Code generated by waygenerator. DO NOT EDIT.

package wlcore

import "fmt"

type ShmPool struct {
	ProxyBase
	listener ShmPoolListener
}

var _ Proxy = (*ShmPool)(nil)

func newShmPool(id, version uint32, conn *Conn) *ShmPool {
	s := &ShmPool{ProxyBase: NewProxyBase(id, version, conn)}
	return s
}

func (s *ShmPool) SetListener(l ShmPoolListener) { s.listener = l }

type ShmPoolListener struct {
}

var ShmPoolInterface = Interface[*ShmPool]{
	Name:       "wl_shm_pool",
	MaxVersion: 3,
	New:        func(b ProxyBase) *ShmPool { return &ShmPool{ProxyBase: b} },
}

func (s *ShmPool) CreateBuffer(offset int32, width int32, height int32, stride int32, format ShmFormat) (*Buffer, error) {
	id := s.Conn().NewID()
	x := &Buffer{ProxyBase: NewProxyBase(id, s.Version(), s.Conn())}
	s.Conn().Register(x)

	e := NewEncoder().ID(id).Int32(offset).Int32(width).Int32(height).Int32(stride).Uint32(uint32(format))
	if err := s.Conn().Send(s.ID(), opReqShmPoolCreateBuffer, e); err != nil {
		return nil, err
	}
	return x, nil
}

func (s *ShmPool) Destroy() error {
	err := s.Conn().Send(s.ID(), opReqShmPoolDestroy, NewEncoder())
	s.Conn().destroy(s)
	return err
}

func (s *ShmPool) Resize(size int32) error {
	e := NewEncoder().Int32(size)
	return s.Conn().Send(s.ID(), opReqShmPoolResize, e)
}

func (s *ShmPool) Dispatch(opcode uint16, dec *Decoder) error {
	switch opcode {
	default:
		return fmt.Errorf("wlcore: opcode %d desconocido en wl_shm_pool", opcode)
	}
}

type ShmPoolError uint32

const (
	ShmPoolErrorInvalidFormat ShmPoolError = 0
	ShmPoolErrorInvalidStride ShmPoolError = 1
)

const (
	opReqShmPoolCreateBuffer = 0
	opReqShmPoolDestroy      = 1
	opReqShmPoolResize       = 2
)
