// Code generated by waygenerator. DO NOT EDIT.

package wlcore

import "fmt"

// Subsurface: sub-surface interface to a wl_surface
//
// An additional interface to a wl_surface object, which has been
// made a sub-surface. A sub-surface has one parent surface. A
// sub-surface's size and position are not limited to that of the parent.
// Particularly, a sub-surface is not automatically clipped to its
// parent's area.
//
// A sub-surface becomes mapped, when a non-NULL wl_buffer is applied
// and the parent surface is mapped. The order of which one happens
// first is irrelevant. A sub-surface is hidden if the parent becomes
// hidden, or if a NULL wl_buffer is applied. These rules apply
// recursively through the tree of surfaces.
//
// The behaviour of a wl_surface.commit request on a sub-surface
// depends on the sub-surface's mode. The possible modes are
// synchronized and desynchronized, see methods
// wl_subsurface.set_sync and wl_subsurface.set_desync. Synchronized
// mode caches the wl_surface state to be applied when the parent's
// state gets applied, and desynchronized mode applies the pending
// wl_surface state directly. A sub-surface is initially in the
// synchronized mode.
//
// Sub-surfaces also have another kind of state, which is managed by
// wl_subsurface requests, as opposed to wl_surface requests. This
// state includes the sub-surface position relative to the parent
// surface (wl_subsurface.set_position), and the stacking order of
// the parent and its sub-surfaces (wl_subsurface.place_above and
// .place_below). This state is applied when the parent surface's
// wl_surface state is applied, regardless of the sub-surface's mode.
// As the exception, set_sync and set_desync are effective immediately.
//
// The main surface can be thought to be always in desynchronized mode,
// since it does not have a parent in the sub-surfaces sense.
//
// Even if a sub-surface is in desynchronized mode, it will behave as
// in synchronized mode, if its parent surface behaves as in
// synchronized mode. This rule is applied recursively throughout the
// tree of surfaces. This means, that one can set a sub-surface into
// synchronized mode, and then assume that all its child and grand-child
// sub-surfaces are synchronized, too, without explicitly setting them.
//
// Destroying a sub-surface takes effect immediately. If you need to
// synchronize the removal of a sub-surface to the parent surface update,
// unmap the sub-surface first by attaching a NULL wl_buffer, update parent,
// and then destroy the sub-surface.
//
// If the parent wl_surface object is destroyed, the sub-surface is
// unmapped.
//
// A sub-surface never has the keyboard focus of any seat.
//
// The wl_surface.offset request is ignored: clients must use set_position
// instead to move the sub-surface.
type Subsurface struct {
	ProxyBase
	listener SubsurfaceListener
}

var _ Proxy = (*Subsurface)(nil)

func newSubsurface(id, version uint32, conn *Conn) *Subsurface {
	return newSubsurfaceFromProxyBase(NewProxyBase(id, version, conn))
}

func newSubsurfaceFromProxyBase(base ProxyBase) *Subsurface {
	s := &Subsurface{ProxyBase: base}
	return s
}

// SetListener installs the handlers for wl_subsurface's events, replacing
// any already installed. A nil field ignores that event; a file descriptor
// arriving in an ignored event is closed, not leaked.
func (s *Subsurface) SetListener(l SubsurfaceListener) { s.listener = l }

// SubsurfaceListener holds the handlers for wl_subsurface's events. Its
// zero value ignores every event. See [Subsurface.SetListener].
type SubsurfaceListener struct {
}

// SubsurfaceInterface describes wl_subsurface for [Registry.Bind]: the name
// it carries on the wire and version 1, the highest this binding
// implements. Bind negotiates that against the version the compositor
// advertises, so a call site never repeats either value.
var SubsurfaceInterface = Interface[*Subsurface]{
	Name:       "wl_subsurface",
	MaxVersion: 1,
	New:        newSubsurfaceFromProxyBase,
}

// Destroy: remove sub-surface interface
//
// The sub-surface interface is removed from the wl_surface object
// that was turned into a sub-surface with a
// wl_subcompositor.get_subsurface request. The wl_surface's association
// to the parent is deleted. The wl_surface is unmapped immediately.
func (s *Subsurface) Destroy() error {
	err := s.Conn().Send(s.ID(), opReqSubsurfaceDestroy, NewEncoder())
	s.Conn().Destroy(s)
	return err
}

// SetPosition: reposition the sub-surface
//
// This schedules a sub-surface position change.
// The sub-surface will be moved so that its origin (top left
// corner pixel) will be at the location x, y of the parent surface
// coordinate system. The coordinates are not restricted to the parent
// surface area. Negative values are allowed.
//
// The scheduled coordinates will take effect whenever the state of the
// parent surface is applied.
//
// If more than one set_position request is invoked by the client before
// the commit of the parent surface, the position of a new request always
// replaces the scheduled position from any previous request.
//
// The initial position is 0, 0.
//
// Parameters:
//   - x: x coordinate in the parent surface
//   - y: y coordinate in the parent surface
func (s *Subsurface) SetPosition(x int32, y int32) error {
	e := NewEncoder().Int32(x).Int32(y)
	return s.Conn().Send(s.ID(), opReqSubsurfaceSetPosition, e)
}

// PlaceAbove: restack the sub-surface
//
// This sub-surface is taken from the stack, and put back just
// above the reference surface, changing the z-order of the sub-surfaces.
// The reference surface must be one of the sibling surfaces, or the
// parent surface. Using any other surface, including this sub-surface,
// will cause a protocol error.
//
// The z-order is double-buffered. Requests are handled in order and
// applied immediately to a pending state. The final pending state is
// copied to the active state the next time the state of the parent
// surface is applied.
//
// A new sub-surface is initially added as the top-most in the stack
// of its siblings and parent.
//
// Parameters:
//   - sibling: the reference surface
func (s *Subsurface) PlaceAbove(sibling *Surface) error {
	e := NewEncoder().ID(sibling.ID())
	return s.Conn().Send(s.ID(), opReqSubsurfacePlaceAbove, e)
}

// PlaceBelow: restack the sub-surface
//
// The sub-surface is placed just below the reference surface.
// See wl_subsurface.place_above.
//
// Parameters:
//   - sibling: the reference surface
func (s *Subsurface) PlaceBelow(sibling *Surface) error {
	e := NewEncoder().ID(sibling.ID())
	return s.Conn().Send(s.ID(), opReqSubsurfacePlaceBelow, e)
}

// SetSync: set sub-surface to synchronized mode
//
// Change the commit behaviour of the sub-surface to synchronized
// mode, also described as the parent dependent mode.
//
// In synchronized mode, wl_surface.commit on a sub-surface will
// accumulate the committed state in a cache, but the state will
// not be applied and hence will not change the compositor output.
// The cached state is applied to the sub-surface immediately after
// the parent surface's state is applied. This ensures atomic
// updates of the parent and all its synchronized sub-surfaces.
// Applying the cached state will invalidate the cache, so further
// parent surface commits do not (re-)apply old state.
//
// See wl_subsurface for the recursive effect of this mode.
func (s *Subsurface) SetSync() error {
	e := NewEncoder()
	return s.Conn().Send(s.ID(), opReqSubsurfaceSetSync, e)
}

// SetDesync: set sub-surface to desynchronized mode
//
// Change the commit behaviour of the sub-surface to desynchronized
// mode, also described as independent or freely running mode.
//
// In desynchronized mode, wl_surface.commit on a sub-surface will
// apply the pending state directly, without caching, as happens
// normally with a wl_surface. Calling wl_surface.commit on the
// parent surface has no effect on the sub-surface's wl_surface
// state. This mode allows a sub-surface to be updated on its own.
//
// If cached state exists when wl_surface.commit is called in
// desynchronized mode, the pending state is added to the cached
// state, and applied as a whole. This invalidates the cache.
//
// Note: even if a sub-surface is set to desynchronized, a parent
// sub-surface may override it to behave as synchronized. For details,
// see wl_subsurface.
//
// If a surface's parent surface behaves as desynchronized, then
// the cached state is applied on set_desync.
func (s *Subsurface) SetDesync() error {
	e := NewEncoder()
	return s.Conn().Send(s.ID(), opReqSubsurfaceSetDesync, e)
}

// Dispatch decodes one wl_subsurface event and calls the matching field of
// the listener. The connection calls it while pumping messages; it is
// exported only because the runtime's Proxy interface requires it.
func (s *Subsurface) Dispatch(opcode uint16, dec *Decoder) error {
	switch opcode {
	default:
		return fmt.Errorf("wlcore: unknown opcode %d in wl_subsurface", opcode)
	}
}

// SubsurfaceError enumerates the protocol errors wl_subsurface can raise.
// The compositor reports one through wl_display.error.
type SubsurfaceError uint32

const (
	SubsurfaceErrorBadSurface SubsurfaceError = 0 // wl_surface is not a sibling or the parent
)

const (
	opReqSubsurfaceDestroy     = 0
	opReqSubsurfaceSetPosition = 1
	opReqSubsurfacePlaceAbove  = 2
	opReqSubsurfacePlaceBelow  = 3
	opReqSubsurfaceSetSync     = 4
	opReqSubsurfaceSetDesync   = 5
)
