// Code generated by waygenerator. DO NOT EDIT.

package wlcore

import "fmt"

type Subsurface struct {
	ProxyBase
	listener SubsurfaceListener
}

var _ Proxy = (*Subsurface)(nil)

func newSubsurface(id, version uint32, conn *Conn) *Subsurface {
	return newSubsurfaceFromProxyBase(NewProxyBase(id, version, conn))
}

func newSubsurfaceFromProxyBase(base ProxyBase) *Subsurface {
	s := &Subsurface{ProxyBase: base}
	return s
}

func (s *Subsurface) SetListener(l SubsurfaceListener) { s.listener = l }

type SubsurfaceListener struct {
}

var SubsurfaceInterface = Interface[*Subsurface]{
	Name:       "wl_subsurface",
	MaxVersion: 1,
	New:        newSubsurfaceFromProxyBase,
}

func (s *Subsurface) Destroy() error {
	err := s.Conn().Send(s.ID(), opReqSubsurfaceDestroy, NewEncoder())
	s.Conn().destroy(s)
	return err
}

func (s *Subsurface) SetPosition(x int32, y int32) error {
	e := NewEncoder().Int32(x).Int32(y)
	return s.Conn().Send(s.ID(), opReqSubsurfaceSetPosition, e)
}

func (s *Subsurface) PlaceAbove(sibling *Surface) error {
	e := NewEncoder().ID(sibling.ID())
	return s.Conn().Send(s.ID(), opReqSubsurfacePlaceAbove, e)
}

func (s *Subsurface) PlaceBelow(sibling *Surface) error {
	e := NewEncoder().ID(sibling.ID())
	return s.Conn().Send(s.ID(), opReqSubsurfacePlaceBelow, e)
}

func (s *Subsurface) SetSync() error {
	e := NewEncoder()
	return s.Conn().Send(s.ID(), opReqSubsurfaceSetSync, e)
}

func (s *Subsurface) SetDesync() error {
	e := NewEncoder()
	return s.Conn().Send(s.ID(), opReqSubsurfaceSetDesync, e)
}

func (s *Subsurface) Dispatch(opcode uint16, dec *Decoder) error {
	switch opcode {
	default:
		return fmt.Errorf("wlcore: opcode %d desconocido en wl_subsurface", opcode)
	}
}

type SubsurfaceError uint32

const (
	SubsurfaceErrorBadSurface SubsurfaceError = 0
)

const (
	opReqSubsurfaceDestroy     = 0
	opReqSubsurfaceSetPosition = 1
	opReqSubsurfacePlaceAbove  = 2
	opReqSubsurfacePlaceBelow  = 3
	opReqSubsurfaceSetSync     = 4
	opReqSubsurfaceSetDesync   = 5
)
