// Code generated by waygenerator. DO NOT EDIT.

package wlcore

import "fmt"

type Surface struct {
	ProxyBase
	listener SurfaceListener
}

var _ Proxy = (*Surface)(nil)

func newSurface(id, version uint32, conn *Conn) *Surface {
	return newSurfaceFromProxyBase(NewProxyBase(id, version, conn))
}

func newSurfaceFromProxyBase(base ProxyBase) *Surface {
	s := &Surface{ProxyBase: base}
	s.OnClear = func() { s.listener = SurfaceListener{} }
	return s
}

func (s *Surface) SetListener(l SurfaceListener) { s.listener = l }

type SurfaceListener struct {
	Enter                    func(output *Output)
	Leave                    func(output *Output)
	PreferredBufferScale     func(factor int32)
	PreferredBufferTransform func(transform OutputTransform)
}

var SurfaceInterface = Interface[*Surface]{
	Name:       "wl_surface",
	MaxVersion: 7,
	New:        newSurfaceFromProxyBase,
}

func (s *Surface) Destroy() error {
	err := s.Conn().Send(s.ID(), opReqSurfaceDestroy, NewEncoder())
	s.Conn().destroy(s)
	return err
}

func (s *Surface) Attach(buffer *Buffer, x int32, y int32) error {
	var bufferID uint32
	if buffer != nil {
		bufferID = buffer.ID()
	}
	e := NewEncoder().ID(bufferID).Int32(x).Int32(y)
	return s.Conn().Send(s.ID(), opReqSurfaceAttach, e)
}

func (s *Surface) Damage(x int32, y int32, width int32, height int32) error {
	e := NewEncoder().Int32(x).Int32(y).Int32(width).Int32(height)
	return s.Conn().Send(s.ID(), opReqSurfaceDamage, e)
}

func (s *Surface) Frame() (*Callback, error) {
	id := s.Conn().NewID()
	x := newCallbackFromProxyBase(NewProxyBase(id, s.Version(), s.Conn()))
	s.Conn().Register(x)

	e := NewEncoder().ID(id)
	if err := s.Conn().Send(s.ID(), opReqSurfaceFrame, e); err != nil {
		return nil, err
	}
	return x, nil
}

func (s *Surface) SetOpaqueRegion(region *Region) error {
	var regionID uint32
	if region != nil {
		regionID = region.ID()
	}
	e := NewEncoder().ID(regionID)
	return s.Conn().Send(s.ID(), opReqSurfaceSetOpaqueRegion, e)
}

func (s *Surface) SetInputRegion(region *Region) error {
	var regionID uint32
	if region != nil {
		regionID = region.ID()
	}
	e := NewEncoder().ID(regionID)
	return s.Conn().Send(s.ID(), opReqSurfaceSetInputRegion, e)
}

func (s *Surface) Commit() error {
	e := NewEncoder()
	return s.Conn().Send(s.ID(), opReqSurfaceCommit, e)
}

func (s *Surface) SetBufferTransform(transform OutputTransform) error {
	if s.Version() < 2 {
		return fmt.Errorf("wlcore: set_buffer_transform requiere versión >= 2, hay %d", s.Version())
	}
	e := NewEncoder().Uint32(uint32(transform))
	return s.Conn().Send(s.ID(), opReqSurfaceSetBufferTransform, e)
}

func (s *Surface) SetBufferScale(scale int32) error {
	if s.Version() < 3 {
		return fmt.Errorf("wlcore: set_buffer_scale requiere versión >= 3, hay %d", s.Version())
	}
	e := NewEncoder().Int32(scale)
	return s.Conn().Send(s.ID(), opReqSurfaceSetBufferScale, e)
}

func (s *Surface) DamageBuffer(x int32, y int32, width int32, height int32) error {
	if s.Version() < 4 {
		return fmt.Errorf("wlcore: damage_buffer requiere versión >= 4, hay %d", s.Version())
	}
	e := NewEncoder().Int32(x).Int32(y).Int32(width).Int32(height)
	return s.Conn().Send(s.ID(), opReqSurfaceDamageBuffer, e)
}

func (s *Surface) Offset(x int32, y int32) error {
	if s.Version() < 5 {
		return fmt.Errorf("wlcore: offset requiere versión >= 5, hay %d", s.Version())
	}
	e := NewEncoder().Int32(x).Int32(y)
	return s.Conn().Send(s.ID(), opReqSurfaceOffset, e)
}

func (s *Surface) GetRelease() (*Callback, error) {
	if s.Version() < 7 {
		return nil, fmt.Errorf("wlcore: get_release requiere versión >= 7, hay %d", s.Version())
	}
	id := s.Conn().NewID()
	x := newCallbackFromProxyBase(NewProxyBase(id, s.Version(), s.Conn()))
	s.Conn().Register(x)

	e := NewEncoder().ID(id)
	if err := s.Conn().Send(s.ID(), opReqSurfaceGetRelease, e); err != nil {
		return nil, err
	}
	return x, nil
}

func (s *Surface) Dispatch(opcode uint16, dec *Decoder) error {
	switch opcode {
	case opEvtSurfaceEnter:
		outputID := dec.ID()
		if err := dec.Err(); err != nil {
			return err
		}
		output, _ := s.Conn().Lookup(outputID).(*Output)
		if s.listener.Enter != nil {
			s.listener.Enter(output)
		}
	case opEvtSurfaceLeave:
		outputID := dec.ID()
		if err := dec.Err(); err != nil {
			return err
		}
		output, _ := s.Conn().Lookup(outputID).(*Output)
		if s.listener.Leave != nil {
			s.listener.Leave(output)
		}
	case opEvtSurfacePreferredBufferScale:
		factor := dec.Int32()
		if err := dec.Err(); err != nil {
			return err
		}
		if s.listener.PreferredBufferScale != nil {
			s.listener.PreferredBufferScale(factor)
		}
	case opEvtSurfacePreferredBufferTransform:
		transform := OutputTransform(dec.Uint32())
		if err := dec.Err(); err != nil {
			return err
		}
		if s.listener.PreferredBufferTransform != nil {
			s.listener.PreferredBufferTransform(transform)
		}
	default:
		return fmt.Errorf("wlcore: opcode %d desconocido en wl_surface", opcode)
	}
	return nil
}

type SurfaceError uint32

const (
	SurfaceErrorInvalidScale      SurfaceError = 0
	SurfaceErrorInvalidTransform  SurfaceError = 1
	SurfaceErrorInvalidSize       SurfaceError = 2
	SurfaceErrorInvalidOffset     SurfaceError = 3
	SurfaceErrorDefunctRoleObject SurfaceError = 4
	SurfaceErrorNoBuffer          SurfaceError = 5
)

const (
	opReqSurfaceDestroy                  = 0
	opReqSurfaceAttach                   = 1
	opReqSurfaceDamage                   = 2
	opReqSurfaceFrame                    = 3
	opReqSurfaceSetOpaqueRegion          = 4
	opReqSurfaceSetInputRegion           = 5
	opReqSurfaceCommit                   = 6
	opReqSurfaceSetBufferTransform       = 7
	opReqSurfaceSetBufferScale           = 8
	opReqSurfaceDamageBuffer             = 9
	opReqSurfaceOffset                   = 10
	opReqSurfaceGetRelease               = 11
	opEvtSurfaceEnter                    = 0
	opEvtSurfaceLeave                    = 1
	opEvtSurfacePreferredBufferScale     = 2
	opEvtSurfacePreferredBufferTransform = 3
)
