// Code generated by waygenerator. DO NOT EDIT.

package wlcore

import "fmt"

type Touch struct {
	ProxyBase
	listener TouchListener
}

var _ Proxy = (*Touch)(nil)

func newTouch(id, version uint32, conn *Conn) *Touch {
	return newTouchFromProxyBase(NewProxyBase(id, version, conn))
}

func newTouchFromProxyBase(base ProxyBase) *Touch {
	t := &Touch{ProxyBase: base}
	t.OnClear = func() { t.listener = TouchListener{} }
	return t
}

func (t *Touch) SetListener(l TouchListener) { t.listener = l }

type TouchListener struct {
	Down        func(serial uint32, time uint32, surface *Surface, id int32, x Fixed, y Fixed)
	Up          func(serial uint32, time uint32, id int32)
	Motion      func(time uint32, id int32, x Fixed, y Fixed)
	Frame       func()
	Cancel      func()
	Shape       func(id int32, major Fixed, minor Fixed)
	Orientation func(id int32, orientation Fixed)
}

var TouchInterface = Interface[*Touch]{
	Name:       "wl_touch",
	MaxVersion: 11,
	New:        newTouchFromProxyBase,
}

func (t *Touch) Release() error {
	if t.Version() < 3 {
		return fmt.Errorf("wlcore: release requiere versión >= 3, hay %d", t.Version())
	}
	err := t.Conn().Send(t.ID(), opReqTouchRelease, NewEncoder())
	t.Conn().destroy(t)
	return err
}

func (t *Touch) Dispatch(opcode uint16, dec *Decoder) error {
	switch opcode {
	case opEvtTouchDown:
		serial := dec.Uint32()
		time := dec.Uint32()
		surfaceID := dec.ID()
		id := dec.Int32()
		x := dec.Fixed()
		y := dec.Fixed()
		if err := dec.Err(); err != nil {
			return err
		}
		surface, _ := t.Conn().Lookup(surfaceID).(*Surface)
		if t.listener.Down != nil {
			t.listener.Down(serial, time, surface, id, x, y)
		}
	case opEvtTouchUp:
		serial := dec.Uint32()
		time := dec.Uint32()
		id := dec.Int32()
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Up != nil {
			t.listener.Up(serial, time, id)
		}
	case opEvtTouchMotion:
		time := dec.Uint32()
		id := dec.Int32()
		x := dec.Fixed()
		y := dec.Fixed()
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Motion != nil {
			t.listener.Motion(time, id, x, y)
		}
	case opEvtTouchFrame:
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Frame != nil {
			t.listener.Frame()
		}
	case opEvtTouchCancel:
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Cancel != nil {
			t.listener.Cancel()
		}
	case opEvtTouchShape:
		id := dec.Int32()
		major := dec.Fixed()
		minor := dec.Fixed()
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Shape != nil {
			t.listener.Shape(id, major, minor)
		}
	case opEvtTouchOrientation:
		id := dec.Int32()
		orientation := dec.Fixed()
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Orientation != nil {
			t.listener.Orientation(id, orientation)
		}
	default:
		return fmt.Errorf("wlcore: opcode %d desconocido en wl_touch", opcode)
	}
	return nil
}

const (
	opReqTouchRelease     = 0
	opEvtTouchDown        = 0
	opEvtTouchUp          = 1
	opEvtTouchMotion      = 2
	opEvtTouchFrame       = 3
	opEvtTouchCancel      = 4
	opEvtTouchShape       = 5
	opEvtTouchOrientation = 6
)
