// Code generated by waygenerator. DO NOT EDIT.

package wlcore

import "fmt"

// Touch: touchscreen input device
//
// The wl_touch interface represents a touchscreen
// associated with a seat.
//
// Touch interactions can consist of one or more contacts.
// For each contact, a series of events is generated, starting
// with a down event, followed by zero or more motion events,
// and ending with an up event. Events relating to the same
// contact point can be identified by the ID of the sequence.
type Touch struct {
	ProxyBase
	listener TouchListener
}

var _ Proxy = (*Touch)(nil)

func newTouch(id, version uint32, conn *Conn) *Touch {
	return newTouchFromProxyBase(NewProxyBase(id, version, conn))
}

func newTouchFromProxyBase(base ProxyBase) *Touch {
	t := &Touch{ProxyBase: base}
	t.OnClear = func() { t.listener = TouchListener{} }
	return t
}

func (t *Touch) SetListener(l TouchListener) { t.listener = l }

type TouchListener struct {
	// Down: touch down event and beginning of a touch sequence
	//
	// A new touch point has appeared on the surface. This touch point is
	// assigned a unique ID. Future events from this touch point reference
	// this ID. The ID ceases to be valid after a touch up event and may be
	// reused in the future.
	//
	// Parameters:
	//   - serial: serial number of the touch down event
	//   - time: timestamp with millisecond granularity
	//   - surface: surface touched
	//   - id: the unique ID of this touch point
	//   - x: surface-local x coordinate
	//   - y: surface-local y coordinate
	Down func(serial uint32, time uint32, surface *Surface, id int32, x Fixed, y Fixed)
	// Up: end of a touch event sequence
	//
	// The touch point has disappeared. No further events will be sent for
	// this touch point and the touch point's ID is released and may be
	// reused in a future touch down event.
	//
	// Parameters:
	//   - serial: serial number of the touch up event
	//   - time: timestamp with millisecond granularity
	//   - id: the unique ID of this touch point
	Up func(serial uint32, time uint32, id int32)
	// Motion: update of touch point coordinates
	//
	// A touch point has changed coordinates.
	//
	// Parameters:
	//   - time: timestamp with millisecond granularity
	//   - id: the unique ID of this touch point
	//   - x: surface-local x coordinate
	//   - y: surface-local y coordinate
	Motion func(time uint32, id int32, x Fixed, y Fixed)
	// Frame: end of touch frame event
	//
	// Indicates the end of a set of events that logically belong together.
	// A client is expected to accumulate the data in all events within the
	// frame before proceeding.
	//
	// A wl_touch.frame terminates at least one event but otherwise no
	// guarantee is provided about the set of events within a frame. A client
	// must assume that any state not updated in a frame is unchanged from the
	// previously known state.
	Frame func()
	// Cancel: touch session cancelled
	//
	// Sent if the compositor decides the touch stream is a global
	// gesture. No further events are sent to the clients from that
	// particular gesture. Touch cancellation applies to all touch points
	// currently active on this client's surface. The client is
	// responsible for finalizing the touch points, future touch points on
	// this surface may reuse the touch point ID.
	//
	// No frame event is required after the cancel event.
	Cancel func()
	// Shape: update shape of touch point
	//
	// Sent when a touchpoint has changed its shape.
	//
	// This event does not occur on its own. It is sent before a
	// wl_touch.frame event and carries the new shape information for
	// any previously reported, or new touch points of that frame.
	//
	// Other events describing the touch point such as wl_touch.down,
	// wl_touch.motion or wl_touch.orientation may be sent within the
	// same wl_touch.frame. A client should treat these events as a single
	// logical touch point update. The order of wl_touch.shape,
	// wl_touch.orientation and wl_touch.motion is not guaranteed.
	// A wl_touch.down event is guaranteed to occur before the first
	// wl_touch.shape event for this touch ID but both events may occur within
	// the same wl_touch.frame.
	//
	// A touchpoint shape is approximated by an ellipse through the major and
	// minor axis length. The major axis length describes the longer diameter
	// of the ellipse, while the minor axis length describes the shorter
	// diameter. Major and minor are orthogonal and both are specified in
	// surface-local coordinates. The center of the ellipse is always at the
	// touchpoint location as reported by wl_touch.down or wl_touch.motion.
	//
	// This event is only sent by the compositor if the touch device supports
	// shape reports. The client has to make reasonable assumptions about the
	// shape if it did not receive this event.
	//
	// Parameters:
	//   - id: the unique ID of this touch point
	//   - major: length of the major axis in surface-local coordinates
	//   - minor: length of the minor axis in surface-local coordinates
	Shape func(id int32, major Fixed, minor Fixed)
	// Orientation: update orientation of touch point
	//
	// Sent when a touchpoint has changed its orientation.
	//
	// This event does not occur on its own. It is sent before a
	// wl_touch.frame event and carries the new shape information for
	// any previously reported, or new touch points of that frame.
	//
	// Other events describing the touch point such as wl_touch.down,
	// wl_touch.motion or wl_touch.shape may be sent within the
	// same wl_touch.frame. A client should treat these events as a single
	// logical touch point update. The order of wl_touch.shape,
	// wl_touch.orientation and wl_touch.motion is not guaranteed.
	// A wl_touch.down event is guaranteed to occur before the first
	// wl_touch.orientation event for this touch ID but both events may occur
	// within the same wl_touch.frame.
	//
	// The orientation describes the clockwise angle of a touchpoint's major
	// axis to the positive surface y-axis and is normalized to the -180 to
	// +180 degree range. The granularity of orientation depends on the touch
	// device, some devices only support binary rotation values between 0 and
	// 90 degrees.
	//
	// This event is only sent by the compositor if the touch device supports
	// orientation reports.
	//
	// Parameters:
	//   - id: the unique ID of this touch point
	//   - orientation: angle between major axis and positive surface y-axis in degrees
	Orientation func(id int32, orientation Fixed)
}

var TouchInterface = Interface[*Touch]{
	Name:       "wl_touch",
	MaxVersion: 11,
	New:        newTouchFromProxyBase,
}

// Release: release the touch object
func (t *Touch) Release() error {
	if t.Version() < 3 {
		return fmt.Errorf("wlcore: release requiere versión >= 3, hay %d", t.Version())
	}
	err := t.Conn().Send(t.ID(), opReqTouchRelease, NewEncoder())
	t.Conn().destroy(t)
	return err
}

func (t *Touch) Dispatch(opcode uint16, dec *Decoder) error {
	switch opcode {
	case opEvtTouchDown:
		serial := dec.Uint32()
		time := dec.Uint32()
		surfaceID := dec.ID()
		id := dec.Int32()
		x := dec.Fixed()
		y := dec.Fixed()
		if err := dec.Err(); err != nil {
			return err
		}
		surface, _ := t.Conn().Lookup(surfaceID).(*Surface)
		if t.listener.Down != nil {
			t.listener.Down(serial, time, surface, id, x, y)
		}
	case opEvtTouchUp:
		serial := dec.Uint32()
		time := dec.Uint32()
		id := dec.Int32()
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Up != nil {
			t.listener.Up(serial, time, id)
		}
	case opEvtTouchMotion:
		time := dec.Uint32()
		id := dec.Int32()
		x := dec.Fixed()
		y := dec.Fixed()
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Motion != nil {
			t.listener.Motion(time, id, x, y)
		}
	case opEvtTouchFrame:
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Frame != nil {
			t.listener.Frame()
		}
	case opEvtTouchCancel:
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Cancel != nil {
			t.listener.Cancel()
		}
	case opEvtTouchShape:
		id := dec.Int32()
		major := dec.Fixed()
		minor := dec.Fixed()
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Shape != nil {
			t.listener.Shape(id, major, minor)
		}
	case opEvtTouchOrientation:
		id := dec.Int32()
		orientation := dec.Fixed()
		if err := dec.Err(); err != nil {
			return err
		}
		if t.listener.Orientation != nil {
			t.listener.Orientation(id, orientation)
		}
	default:
		return fmt.Errorf("wlcore: opcode %d desconocido en wl_touch", opcode)
	}
	return nil
}

const (
	opReqTouchRelease     = 0
	opEvtTouchDown        = 0
	opEvtTouchUp          = 1
	opEvtTouchMotion      = 2
	opEvtTouchFrame       = 3
	opEvtTouchCancel      = 4
	opEvtTouchShape       = 5
	opEvtTouchOrientation = 6
)
