// Package fractionalscale contains the bindings for fractional-scale-v1,
// which lets a compositor ask for a scale that is not a whole number --
// 1.25 or 1.5 on a laptop panel, where wl_surface.set_buffer_scale can
// only say 1 or 2.
//
// Bind [FractionalScaleManagerInterface] from the registry and call
// [FractionalScaleManager.GetFractionalScale] on a wl_surface. The
// compositor then sends preferred_scale events carrying the scale as an
// integer multiple of 120: 180 means 1.5.
//
// This protocol only reports the scale. Acting on it takes the viewporter
// package: render the buffer at the physical size the scale implies, then
// set the viewport destination to the logical size. Without that, the
// compositor scales the buffer itself and the result is blurry.
//
// Staging protocol -- it can still change upstream.
//
// Generated by waygenerator from protocols/fractional-scale-v1.xml. Do not
// edit the .gen.go files.
package fractionalscale
