// Code generated by waygenerator. DO NOT EDIT.

package fractionalscale

import (
	"fmt"

	"github.com/romycode/ggui/wayland/wlcore"
)

// FractionalScaleManager: fractional surface scale information
//
// A global interface for requesting surfaces to use fractional scales.
type FractionalScaleManager struct {
	wlcore.ProxyBase
	listener FractionalScaleManagerListener
}

var _ wlcore.Proxy = (*FractionalScaleManager)(nil)

func newFractionalScaleManager(id, version uint32, conn *wlcore.Conn) *FractionalScaleManager {
	return newFractionalScaleManagerFromProxyBase(wlcore.NewProxyBase(id, version, conn))
}

func newFractionalScaleManagerFromProxyBase(base wlcore.ProxyBase) *FractionalScaleManager {
	f := &FractionalScaleManager{ProxyBase: base}
	return f
}

// SetListener installs the handlers for wp_fractional_scale_manager_v1's
// events, replacing any already installed. A nil field ignores that event;
// a file descriptor arriving in an ignored event is closed, not leaked.
func (f *FractionalScaleManager) SetListener(l FractionalScaleManagerListener) { f.listener = l }

// FractionalScaleManagerListener holds the handlers for
// wp_fractional_scale_manager_v1's events. Its zero value ignores every
// event. See [FractionalScaleManager.SetListener].
type FractionalScaleManagerListener struct {
}

// FractionalScaleManagerInterface describes wp_fractional_scale_manager_v1
// for [wlcore.Registry.Bind]: the name it carries on the wire and version
// 1, the highest this binding implements. Bind negotiates that against the
// version the compositor advertises, so a call site never repeats either
// value.
var FractionalScaleManagerInterface = wlcore.Interface[*FractionalScaleManager]{
	Name:       "wp_fractional_scale_manager_v1",
	MaxVersion: 1,
	New:        newFractionalScaleManagerFromProxyBase,
}

// Destroy: unbind the fractional surface scale interface
//
// Informs the server that the client will not be using this protocol
// object anymore. This does not affect any other objects,
// wp_fractional_scale_v1 objects included.
func (f *FractionalScaleManager) Destroy() error {
	err := f.Conn().Send(f.ID(), opReqFractionalScaleManagerDestroy, wlcore.NewEncoder())
	f.Conn().Destroy(f)
	return err
}

// GetFractionalScale: extend surface interface for scale information
//
// Create an add-on object for the the wl_surface to let the compositor
// request fractional scales. If the given wl_surface already has a
// wp_fractional_scale_v1 object associated, the fractional_scale_exists
// protocol error is raised.
//
// Parameters:
//   - surface: the surface
func (f *FractionalScaleManager) GetFractionalScale(surface *wlcore.Surface) (*FractionalScale, error) {
	id := f.Conn().NewID()
	x := newFractionalScaleFromProxyBase(wlcore.NewProxyBase(id, f.Version(), f.Conn()))
	f.Conn().Register(x)

	e := wlcore.NewEncoder().ID(id).ID(surface.ID())
	if err := f.Conn().Send(f.ID(), opReqFractionalScaleManagerGetFractionalScale, e); err != nil {
		return nil, err
	}
	return x, nil
}

// Dispatch decodes one wp_fractional_scale_manager_v1 event and calls the
// matching field of the listener. The connection calls it while pumping
// messages; it is exported only because the runtime's Proxy interface
// requires it.
func (f *FractionalScaleManager) Dispatch(opcode uint16, dec *wlcore.Decoder) error {
	switch opcode {
	default:
		return fmt.Errorf("fractionalscale: unknown opcode %d in wp_fractional_scale_manager_v1", opcode)
	}
}

// FractionalScaleManagerError enumerates the protocol errors
// wp_fractional_scale_manager_v1 can raise. The compositor reports one
// through wl_display.error.
type FractionalScaleManagerError uint32

const (
	FractionalScaleManagerErrorFractionalScaleExists FractionalScaleManagerError = 0 // the surface already has a fractional_scale object associated
)

const (
	opReqFractionalScaleManagerDestroy            = 0
	opReqFractionalScaleManagerGetFractionalScale = 1
)
